import type { Content } from './types';

export const en: Content = {
  meta: {
    title: 'Maykon Meneghel — the playable CV',
    description:
      'Senior full-stack engineer with a Master in AI. Firmware, PCBs, CAD, MQTT, Kubernetes, Swift and Flutter — explained through mini-games you can play right on the page.',
  },
  nav: { chapters: 'Chapters', family: 'The family', contact: 'Contact', resume: 'Résumé' },
  hero: {
    kicker: 'Senior Full-Stack Engineer · M.Sc. in Bioengineering · AI Specialist',
    name: 'Maykon Meneghel',
    headline: 'I build the whole stack — from the copper trace to the neural network.',
    sub: 'Most CVs tell you what someone can do. This one lets you try it. Every chapter below is a working mini-game: you will route a PCB, subscribe to an MQTT topic, scale a cluster under load and train a model — without leaving this page.',
    cta: 'Start the tour',
    scrollHint: 'scroll',
    boot: [
      'meneghel.me boot v2.0',
      'probing hardware ....... ESP32 · PIC18F4550 · ATmega · ATtiny',
      'mounting languages ..... swift · dart · python · typescript · c/c++ · java',
      'starting services ...... docker · kubernetes · mqtt · rest',
      'loading intelligence ... pytorch · gan · nlp',
      'ready.',
    ],
  },
  chapters: [
    {
      id: '01', codename: 'SILICON', slug: 'silicon',
      title: 'It starts with a single pin',
      lede: 'Long before there is an app, there is a microcontroller deciding — millions of times per second — whether one wire is high or low. Fourteen firmwares taught me that everything above depends on getting this right.',
      panel: 'pwm_playground.c',
      takeaway: 'You just dimmed an LED without ever changing its voltage. That is <b>PWM</b>: the pin is only ever fully on or fully off — it simply switches faster than your eye can follow.',
      stack: ['C/C++', 'ESP32', 'PIC18F4550', 'ATmega', 'Timers & PWM'],
    },
    {
      id: '02', codename: 'COPPER', slug: 'copper',
      title: 'Then it needs a board',
      lede: 'A schematic is a promise. The PCB is where you keep it. Every board I have fabricated started as this exact puzzle: get every signal where it belongs, on a surface where nothing may cross.',
      panel: 'router.pcb',
      takeaway: 'Two traces cannot cross on the same layer. That single constraint is the reason real boards have 2, 4, sometimes 12 layers stacked on top of each other.',
      stack: ['Altium', 'EAGLE', 'SMD & THT', 'Gerber', 'Design for manufacturing'],
    },
    {
      id: '03', codename: 'STEEL', slug: 'steel',
      title: 'And a body to survive the field',
      lede: 'A sensor buried in wet soil for two years does not care how elegant your firmware is. It cares about the enclosure. So I model it myself — every part, every tolerance, every seal.',
      panel: 'soil_probe.sldasm',
      takeaway: 'Hardware is the one layer you cannot patch remotely. That is why the mechanical design happens <b>before</b> the first line of firmware, not after.',
      stack: ['SolidWorks', '3D modelling', 'Tolerancing', 'IP sealing', '3D printing'],
    },
    {
      id: '04', codename: 'SIGNAL', slug: 'signal',
      title: 'Now make a thousand of them talk',
      lede: 'One device is a project. A thousand devices is an architecture. MQTT is how they speak without ever knowing one another — and topic wildcards are the whole trick.',
      panel: 'broker · mqtt://meneghel.me:8883',
      takeaway: '<b>+</b> matches exactly one level. <b>#</b> matches everything below it. That one rule is how a single broker fans out to thousands of devices without any of them holding a list of the others.',
      stack: ['MQTT', 'Mosquitto', 'AWS IoT Core', 'QoS 0/1/2', 'Pub/Sub'],
    },
    {
      id: '05', codename: 'SERVICE', slug: 'service',
      title: 'Somebody has to remember all of it',
      lede: 'Messages are ephemeral; the business is not. Behind every device sits an API and a database, and the difference between a fast product and a slow one is usually one decision made here.',
      panel: 'psql · meneghel_db',
      takeaway: 'Without an index the database reads <b>every row</b> to answer you. With one, it jumps straight there. Same query, same data, same server — a thousand times faster.',
      stack: ['Node.js', 'Express', 'Restify', 'MongoDB', 'PostgreSQL', 'REST'],
    },
    {
      id: '06', codename: 'SWARM', slug: 'swarm',
      title: 'One box is never enough',
      lede: 'Traffic does not arrive politely. It arrives all at once, at 3am, on launch day. Containers and Kubernetes are how you answer that without waking up.',
      panel: 'kubectl · production',
      takeaway: 'You did not make the code faster — you made <b>more of it</b>. Horizontal scaling trades money for latency, and an autoscaler makes that trade for you, automatically.',
      stack: ['Docker', 'Kubernetes', 'HPA', 'Load balancing', 'CI/CD'],
    },
    {
      id: '07', codename: 'MIND', slug: 'mind',
      title: 'Teach the machine to decide',
      lede: 'This is where my postgraduate work in AI and my Master in Bioengineering stop being lines on a diploma. A model is not magic: it is a boundary, drawn and redrawn until the mistakes stop.',
      panel: 'perceptron.py — epoch 0',
      takeaway: 'The model never saw your rule. It only saw your mistakes, and moved the line a little after each one. Repeat that a few hundred times and you get what people call <b>learning</b>.',
      stack: ['PyTorch', 'GANs', 'NLP', 'Classification & regression', 'Data mining'],
    },
    {
      id: '08', codename: 'GLASS', slug: 'glass',
      title: 'Finally, something you can touch',
      lede: 'Twelve native iOS apps, one featured by Apple. The user never sees the broker, the cluster or the model — they see a screen. So the screen has to be worth all of it.',
      panel: 'ContentView.swift / main.dart',
      takeaway: 'Same screen, same API, two ecosystems. Knowing both is not about picking a winner — it is about being able to <b>choose</b> when the product demands it.',
      stack: ['Swift', 'SwiftUI', 'Flutter', 'Dart', 'Kotlin', 'App Store'],
    },
    {
      id: '09', codename: 'SYSTEM', slug: 'system',
      title: 'Now watch all of it run at once',
      lede: 'Nine chapters, one packet. Press play and follow a single soil reading from the sensor in the ground all the way to the chart in someone’s hand.',
      panel: 'trace · end-to-end',
      takeaway: 'This is the actual answer to "what do you do?". Not one layer — <b>the seams between them</b>, which is where products are really won or lost.',
      stack: ['System design', 'Observability', 'Distributed systems'],
    },
  ],
  record: {
    eyebrow: '10 · RECORD',
    title: 'The receipts',
    lede: 'Nine chapters of demonstration. This one is just evidence. Drag through the years and watch what was running at the same time — because the honest headline of this timeline is not any single job, it is how rarely there was only one.',
    lanes: {
      education: 'Education',
      research: 'Research',
      industry: 'Industry',
      venture: 'Ventures',
    },
    roles: {
      grad: 'B.Eng. Control & Automation Engineering',
      msc: 'M.Sc. Bioengineering',
      academy: 'Postgraduate specialization, iOS Development',
      aiSpec: 'Specialization, Applied Artificial Intelligence',
      pucLab: 'Trainee, Laboratory of Automation and Systems',
      araucaria: 'Software Engineer — applied research, AI and embedded health',
      freelance: 'Software Developer, freelance',
      residency: 'Trainee · Apple Residency',
      junior: 'Junior Developer · Apple Project',
      techLead: 'Tech Lead · Apple Internship',
      fullstack: 'Full Stack Developer · Apple Project',
      senior: 'Senior Developer · Apple Project',
      ghel: 'Technology Advisor · Renault Project',
      holding: 'Administrative Advisor — the family holding',
      tradx: 'COO & Co-founder',
    },
    scrubber: {
      simultaneous: '{n} roles at once',
      one: '1 role',
      none: 'nothing on record yet',
      today: 'today',
      drag: 'drag the year',
    },
    ventures: {
      title: 'Six companies',
      lede: 'Founded or co-founded. Some grew, some did not — which is the point of founding six.',
      founder: 'Founder',
      coFounder: 'Co-founder',
      sectors: { fintech: 'fintech', agritech: 'agritech', smartHome: 'smart home', proptech: 'proptech', edtech: 'edtech' },
    },
    publications: {
      title: 'Published and awarded',
      lede: 'Peer-reviewed work, mostly at the seam between engineering and health.',
      items: {
        soilInstrument: 'Instrument for Measuring Factors and/or Natural Elements of the Soil',
        fesTool: 'A Tool to Select FES Parameters for chronic SCI',
        fallDetector: 'Indoors Wi-Fi Fall Detector Buckle for the Elderly',
        inSilicoFes: 'Application, in silico, of electrical stimuli in a neuro-muscular model compatible with chronic spinal cord injury',
        balanceModel: 'Mathematical modeling of the balance maintenance system using system identification techniques',
        stockGan: 'Forecasting financial series with Generative Adversarial Networks',
      },
    },
    press: {
      title: 'In the press',
      items: {
        hubli: 'Hubli, built at the Apple Developer Academy, featured by Apple',
        neonWave: 'Neon Wave, an iOS game covered by MacMagazine',
      },
    },
  },
  signal: {
    levels: ['site', 'area', 'device', 'reading'],
    anatomyLede: 'A topic is a path. Every device on this farm publishes to one built from the same four levels — so a subscription is really a question about which levels you care about.',
    legendPlus: 'matches exactly one level, whatever is in it',
    legendHash: 'matches everything below it, and has to be the last level',
    yourToken: 'you wrote',
    noToken: '—',
    subLabel: 'Your subscription',
    placeholder: 'farm/greenhouse/#',
    broker: 'Broker — everything being published',
    inbox: 'Your inbox — what reached you',
    delivered: 'delivered',
    dropped: 'not delivered',
    missionsTitle: 'Three subscriptions to get right',
    missionsLede: 'Any filter that selects exactly the right topics counts. There is more than one correct answer to each.',
    missions: [
      { id: 'greenhouse', goal: 'Everything the greenhouse publishes — and nothing else.' },
      { id: 'temps',      goal: 'Every temperature reading, wherever it comes from.' },
      { id: 'moisture',   goal: 'Every moisture reading on the farm, but not the one at home.' },
    ],
    solved: 'solved',
    invalidHash: '# has to be the last level, on its own',
    invalidPlus: '+ has to fill a whole level, on its own',
    invalidEmpty: 'a topic level cannot be empty',
    emptyInbox: 'nothing matched yet',
    allSolved: 'All three. You now know MQTT topic filters better than most people who use them daily.',
  },
  swarm: {
    lede: 'Traffic on this service spikes every few seconds, the way a launch day does. Add replicas and the latency falls; add too many and you are paying for idle machines. Then hand it to the autoscaler and watch where it still loses.',
    traffic: 'Incoming',
    replicas: 'Replicas',
    latency: 'p99 latency',
    dropped: 'Requests dropped',
    cost: 'Cost',
    saturation: 'Saturation',
    auto: 'Autoscaler',
    autoHint: 'Targeting 60% saturation. A new pod takes about 4s to become ready — which is why requests still drop on the way up.',
    manualHint: 'You are scaling by hand. The spike arrives whether you are ready or not.',
    ready: 'ready',
    starting: 'starting',
    reset: 'Reset counters',
    spike: 'spike',
    healthy: 'healthy',
    strained: 'strained',
    failing: 'dropping traffic',
    wasteful: 'over-provisioned',
  },
  mind: {
    lede: 'Each dot is a motor that was running at some temperature and some vibration, and later turned out fine or turned out broken. The model has never been told the rule. Press train and watch it look for the line.',
    axisX: 'temperature →',
    axisY: 'vibration →',
    healthy: 'healthy',
    failing: 'failing',
    adding: 'clicking adds',
    train: 'Train',
    pause: 'Pause',
    clear: 'Clear',
    presetSeparable: 'Separable',
    presetXor: 'XOR',
    steps: 'Corrections',
    accuracy: 'Accuracy',
    wrong: 'Still wrong',
    weights: 'Weights',
    hintPlace: 'Click anywhere to add a reading. Switch class to place the other kind.',
    hintConverged: 'It stopped. Not because it was told to — because there was nothing left it got wrong.',
    hintStuck: 'It will never settle. No single straight line can split this arrangement, and one perceptron is exactly one straight line. Stacking them is how you get a curve — which is the whole reason deep networks exist.',
  },
  service: {
    lede: 'A table of sensor readings, 240,000 rows deep. Pick a query, decide which columns get an index, and run it. The strip below is the table; watch how much of it the database has to touch.',
    table: 'readings · 240,000 rows',
    indexes: 'CREATE INDEX ON',
    query: 'Query',
    run: 'Run',
    running: 'Running…',
    rows: 'Rows examined',
    time: 'Query time',
    speedup: 'vs full scan',
    writes: 'Write cost',
    queryLabels: {
      point: 'one row by id',
      selective: 'one sensor · 5%',
      broad: 'most of the table · 60%',
    },
    hints: {
      'no-index': 'There is no index on that column, so the database has no choice. It opens the table at the first row and reads every one of the 240,000 to be sure it has not missed any.',
      'index-used': 'The index went straight there — eighteen steps down the tree, then the rows themselves. Same query, same data, same machine.',
      'not-selective': 'The index exists, and the planner refused to use it. This query wants 60% of the table, and jumping around an index for that costs more than reading everything in order. Building it bought you nothing here — and it still slows down every single write.',
    },
    treeLabel: 'index · B-tree',
    heapLabel: 'table',
  },
  copper: {
    lede: 'This is not an illustration. It is AGROM.brd, the board I laid out in 2017 for the soil probe — 70 mm across, two copper layers, 54 components — read straight out of the EAGLE file and drawn here. Pick a net and follow it.',
    layersLabel: 'Layers',
    view2d: 'Flat',
    view3d: 'Stack',
    viewSolid: 'Assembled',
    flip: 'Turn over',
    componentsWord: 'components',
    underneathWord: 'underneath',
    hintSolid: 'The same board with its parts on it, built from the IDF file EAGLE exported to the mechanical CAD in 2017 — every footprint, position, rotation and side is out of that file. Nineteen of the 59 parts are mounted underneath. Turn it over and you will find them.',
    explode: 'Separation',
    spin: 'drag to turn',
    hintStack: 'This is the same board, seen edge-on. Two sheets of copper with 1.6 mm of fibreglass between them, and 34 plated posts stitching them together. Every yellow post is a via — the only way a signal gets from one face to the other.',
    both: 'Both',
    topOnly: 'Top only',
    bottomOnly: 'Bottom only',
    netsLabel: 'Nets',
    allNets: 'All',
    segments: 'Segments',
    crossings: 'Layer changes',
    length: 'Copper length',
    legendTop: 'top copper',
    legendBottom: 'bottom copper',
    legendVia: 'via',
    hintIdle: 'Red runs on the top face, blue on the bottom. Every yellow ring is a via: a plated hole where a track drops through to the other side.',
    hintCrossings: 'The {net} net changes layer {n} times. Switch to one layer and watch it break into pieces — those gaps are where it is running on the face you just hid.',
    hintFlat: 'The {net} net never leaves its layer. Nothing was in its way, so it never had to dive.',
    hintOneLayer: 'Half the board just vanished. Everything missing is running on the other face — and the only reason it can is that the two faces are stitched together by vias.',
  },
  ui: {
    duty: 'Duty cycle',
    brightness: 'Perceived brightness',
    frequency: 'Frequency',
    play: 'Play',
    pause: 'Pause',
    reset: 'Reset',
    subscribe: 'Subscribe',
    publish: 'Publish',
    matched: 'matched',
    dropped: 'not delivered',
    replicas: 'Replicas',
    traffic: 'Incoming traffic',
    latency: 'p99 latency',
    dropped_req: 'Dropped requests',
    cost: 'Cost',
    train: 'Train',
    epoch: 'Epoch',
    accuracy: 'Accuracy',
    wip: 'Interactive build in progress',
    wipNote: 'The layout is final; this panel is being wired up.',
    learned: 'What you just learned',
  },
};
