import type { Content } from './types';

export const en: Content = {
  meta: {
    title: 'Maykon Meneghel — the playable CV',
    description:
      'Senior full-stack engineer with a Master in AI. Firmware, PCBs, CAD, MQTT, Kubernetes, Swift and Flutter — explained through mini-games you can play right on the page.',
  },
  nav: { chapters: 'Chapters', family: 'The family', contact: 'Contact', resume: 'Résumé' },
  hero: {
    kicker: 'Senior Full-Stack Engineer · Agribusiness & financial markets',
    name: 'Maykon Meneghel',
    headline: 'I build the whole stack — from the copper trace to the neural network.',
    sub: 'Most CVs tell you what someone can do. This one lets you try it. Every chapter below is a working mini-game: you will route a PCB, subscribe to an MQTT topic, scale a cluster under load and train a model — without leaving this page.',
    proof: [
      'Twelve native iOS apps · one featured by Apple',
      'COO & co-founder · Tradx',
      'M.Sc. Bioengineering · postgraduate specialization in applied AI',
      'Clean Architecture for SwiftUI · 30★ on GitHub',
    ],
    links: [
      { label: 'LinkedIn', href: 'https://www.linkedin.com/in/maykonmeneghel/' },
      { label: 'GitHub', href: 'https://github.com/maykonmeneghel' },
    ],
    cta: 'Start the tour',
    scrollHint: 'scroll',
    boot: [
      'meneghel.me boot v2.0',
      'probing hardware ....... ESP32 · PIC18F4550 · ATmega · ATtiny',
      'mounting languages ..... swift · dart · python · typescript · c/c++ · java',
      'starting services ...... docker · kubernetes · mqtt · rest',
      'loading intelligence ... pytorch · gan · nlp',
      'ready.',
    ],
  },
  acts: [
    {
      before: 'silicon',
      label: 'Act one',
      title: 'One machine, taken apart',
      lede: 'The next eight chapters are a single product: a soil probe I designed, built and put in the ground between 2016 and 2019. It is here because it is the one thing I own end to end — the board, the enclosure, the protocol, the database, the cluster and the app are all mine — so the whole stack can be walked from a pin to a screen without ever changing the subject.',
    },
    {
      before: 'mind',
      label: 'Act two',
      title: 'And where that went',
      lede: '2019 onward. The Apple Developer Academy moved my centre of gravity from boards to products, and the engineering underneath stayed exactly the same. These three chapters are the work since — including the two things I am doing right now.',
    },
  ],
  chapters: [

    {
      id: '01', codename: 'SILICON', slug: 'silicon',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'It starts with a single pin',
      lede: 'Long before there is an app, there is a microcontroller deciding — millions of times per second — whether one wire is high or low. Fourteen firmwares taught me that everything above depends on getting this right.',
      panel: 'pwm_playground.c',
      takeaway: 'You just dimmed an LED without ever changing its voltage. That is <b>PWM</b>: the pin is only ever fully on or fully off — it simply switches faster than your eye can follow.',
      stack: ['C/C++', 'ESP32', 'PIC18F4550', 'ATmega', 'Timers & PWM'],
    },
    {
      id: '02', codename: 'COPPER', slug: 'copper',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Then it needs a board',
      lede: 'A schematic is a promise. The PCB is where you keep it. Every board I have fabricated started as this exact puzzle: get every signal where it belongs, on a surface where nothing may cross.',
      panel: 'router.pcb',
      takeaway: 'Two traces cannot cross on the same layer. That single constraint is the reason real boards have 2, 4, sometimes 12 layers stacked on top of each other.',
      stack: ['Altium', 'EAGLE', 'SMD & THT', 'Gerber', 'Design for manufacturing'],
    },
    {
      id: '03', codename: 'STEEL', slug: 'steel',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'And a body to survive the field',
      lede: 'A sensor buried in wet soil for two years does not care how elegant your firmware is. It cares about the enclosure. So I model it myself — every part, every tolerance, every seal.',
      panel: 'soil_probe.sldasm',
      takeaway: 'Hardware is the one layer you cannot patch remotely. That is why the mechanical design happens <b>before</b> the first line of firmware, not after.',
      stack: ['SolidWorks', '3D modelling', 'Tolerancing', 'IP sealing', '3D printing'],
    },
    {
      id: '04', codename: 'SIGNAL', slug: 'signal',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Now make a thousand of them talk',
      lede: 'One device is a project. A thousand devices is an architecture. MQTT is how they speak without ever knowing one another — and topic wildcards are the whole trick.',
      panel: 'broker · mqtt://meneghel.me:8883',
      takeaway: '<b>+</b> matches exactly one level. <b>#</b> matches everything below it. That one rule is how a single broker fans out to thousands of devices without any of them holding a list of the others.',
      stack: ['MQTT', 'Mosquitto', 'AWS IoT Core', 'QoS 0/1/2', 'Pub/Sub'],
    },
    {
      id: '05', codename: 'SERVICE', slug: 'service',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Somebody has to remember all of it',
      lede: 'Messages are ephemeral; the business is not. Behind every device sits an API and a database, and the difference between a fast product and a slow one is usually one decision made here.',
      panel: 'psql · meneghel_db',
      takeaway: 'Without an index the database reads <b>every row</b> to answer you. With one, it jumps straight there. Same query, same data, same server — a thousand times faster.',
      stack: ['Node.js', 'Express', 'Restify', 'MongoDB', 'PostgreSQL', 'REST'],
    },
    {
      id: '06', codename: 'SWARM', slug: 'swarm',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'One box is never enough',
      lede: 'Traffic does not arrive politely. It arrives all at once, at 3am, on launch day. Containers and Kubernetes are how you answer that without waking up.',
      panel: 'kubectl · production',
      takeaway: 'You did not make the code faster — you made <b>more of it</b>. Horizontal scaling trades money for latency, and an autoscaler makes that trade for you, automatically.',
      stack: ['Docker', 'Kubernetes', 'HPA', 'Load balancing', 'CI/CD'],
    },
    {
      id: '07', codename: 'GLASS', slug: 'glass',
      era: 'Swift & Flutter · 2019 → today',
      title: 'Finally, something you can touch',
      lede: 'Twelve native iOS apps, one featured by Apple. The user never sees the broker, the cluster or the model — they see a screen. So the screen has to be worth all of it.',
      panel: 'ContentView.swift / main.dart',
      takeaway: 'Same screen, same API, two ecosystems. Knowing both is not about picking a winner — it is about being able to <b>choose</b> when the product demands it.',
      stack: ['Swift', 'SwiftUI', 'Flutter', 'Dart', 'Kotlin', 'App Store'],
    },
    {
      id: '08', codename: 'SYSTEM', slug: 'system',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Now watch all of it run at once',
      lede: 'Seven chapters, one packet. Press play and follow a single soil reading from the sensor in the ground all the way to the chart in someone’s hand.',
      panel: 'trace · end-to-end',
      takeaway: 'This is the actual answer to "what do you do?". Not one layer — <b>the seams between them</b>, which is where products are really won or lost.',
      stack: ['System design', 'Observability', 'Distributed systems'],
    },
    {
      id: '09', codename: 'MIND', slug: 'mind',
      era: 'StockGAN · 2021',
      title: 'Teach the machine to guess what happens next',
      lede: 'In 2021 I built a generative adversarial network for time series from scratch — the work where my postgraduate specialization in AI and my Master in Bioengineering stop being lines on a diploma — two networks, one trying to invent the next reading and one trying to catch it lying. I trained it on financial data. It runs here on the soil probe from the chapters above, unchanged, because a time series does not know what it measures.',
      panel: 'gan_model.py — train_step()',
      takeaway: 'Two models, one loss function, and a knob between them. Grade the forecaster on being close and it answers with the average of everything, which is safe and useless. Grade it on being believable and it answers with something that moves like the sensor and knows nothing. <b>Every model I ship is that trade made on purpose</b>, written down, and measured.',
      stack: ['TensorFlow / Keras', 'GANs', 'LSTM', 'Time series', 'PCA & XGBoost feature selection'],
    },
    {
      id: '10', codename: 'FLOW', slug: 'flow',
      era: 'Tradx · 2022 → today',
      title: 'And then I built the tool',
      lede: 'A forecast has to live somewhere. Tradx is where mine does — the company I co-founded in 2022 and run as COO, a desk where a trading strategy is a graph you wire rather than code you write.',
      panel: 'tradx · strategy graph',
      takeaway: 'A backtest is a <b>hypothesis</b>, not a result. Anyone can tune a curve until it is beautiful on the data they already have; the entire craft is knowing what that number is worth on the data they do not.',
      stack: ['Node.js', 'NestJS', 'Flutter', 'MongoDB', 'Redis + BullMQ', 'Backtesting engine', 'Paper trading'],
    },
    {
      id: '11', codename: 'LEDGER', slug: 'ledger',
      era: 'Tradx · 2022 → today',
      title: 'An order is not a trade',
      lede: 'The chapter before this one produced a signal. This one is what happens to it. A strategy emits orders; an engine decides which of them become trades, and the distance between those two numbers is where a trading desk is actually built or lost.',
      panel: 'tradx · execution engine',
      takeaway: 'The engine refused thirty-eight orders and reported a funds problem. It did not have one. <b>A sell against a long releases buying power</b> — an engine that checks the order instead of the resulting exposure will block the trades that reduce risk and call it prudence.',
      stack: ['NestJS', 'Order lifecycle', 'Position netting', 'Idempotency', 'Redis + BullMQ', 'Paper trading'],
    },
    {
      id: '12', codename: 'FIELD', slug: 'field',
      era: 'Gaussian splatting · today',
      title: 'And now the object is made of light',
      lede: 'What I spend my days on now: Gaussian Splatting. A scene stops being a surface someone modelled and becomes a cloud of oriented gaussians, fitted by gradient descent until renders of them match the photographs. Real reconstructions start from a camera walking around a room. The demo below deliberately does not — it uses a part you already met in chapter 03, because the only way to see what the method changes is to watch the same object built both ways.',
      panel: 'gaussian splatting · viewer',
      takeaway: 'A mesh says where the <b>surfaces</b> are, and an engineer drew every one. A splat field says where the <b>light</b> is, and nobody drew any of it — it was fitted until the render stopped disagreeing with the photograph.',
      stack: ['Gaussian Splatting', '3DGS', 'PyTorch', 'CUDA', 'Photogrammetry', 'Radiance fields'],
    },
  ],
  record: {
    eyebrow: '13 · RECORD',
    title: 'The receipts',
    lede: 'Nine chapters of demonstration. This one is just evidence. Drag through the years and watch what was running at the same time — because the honest headline of this timeline is not any single job, it is how rarely there was only one.',
    lanes: {
      education: 'Education',
      research: 'Research',
      industry: 'Industry',
      venture: 'Ventures',
    },
    roles: {
      grad: 'B.Eng. Control & Automation Engineering',
      msc: 'M.Sc. Bioengineering',
      academy: 'Postgraduate specialization, iOS Development',
      aiSpec: 'Specialization, Applied Artificial Intelligence',
      pucLab: 'Trainee, Laboratory of Automation and Systems',
      araucaria: 'Software Engineer — applied research, AI and embedded health',
      freelance: 'Software Developer, freelance',
      residency: 'Trainee · Apple Residency',
      junior: 'Junior Developer · Apple Project',
      techLead: 'Tech Lead · Apple Internship',
      fullstack: 'Full Stack Developer · Apple Project',
      senior: 'Senior Developer · Apple Project',
      ghel: 'Technology Advisor · Renault Project',
      holding: 'Administrative Advisor — the family holding',
      tradx: 'COO & Co-founder',
    },
    scrubber: {
      simultaneous: '{n} roles at once',
      one: '1 role',
      none: 'nothing on record yet',
      today: 'today',
      drag: 'drag the year',
    },
    ventures: {
      title: 'Six companies',
      lede: 'Founded or co-founded. Some grew, some did not — which is the point of founding six.',
      founder: 'Founder',
      coFounder: 'Co-founder',
      sectors: { fintech: 'fintech', agritech: 'agritech', smartHome: 'smart home', proptech: 'proptech', edtech: 'edtech' },
    },
    publications: {
      title: 'Published and awarded',
      lede: 'Peer-reviewed work, mostly at the seam between engineering and health.',
      read: 'read the paper',
      code: 'source',
      items: {
        soilInstrument: 'Instrument for Measuring Factors and/or Natural Elements of the Soil',
        fesTool: 'A Tool to Select FES Parameters for chronic SCI',
        fallDetector: 'Indoors Wi-Fi Fall Detector Buckle for the Elderly',
        inSilicoFes: 'Application, in silico, of electrical stimuli in a neuro-muscular model compatible with chronic spinal cord injury',
        balanceModel: 'Mathematical modeling of the balance maintenance system using system identification techniques',
        stockGan: 'Forecasting financial series with Generative Adversarial Networks',
      },
    },
    press: {
      title: 'In the press',
      items: {
        hubli: 'Hubli, built at the Apple Developer Academy, featured by Apple',
        neonWave: 'Neon Wave, an iOS game covered by MacMagazine',
      },
    },
    closing: {
      line: 'Senior full-stack, from the solder joint to the model in production — in agribusiness and in financial markets.',
      note: 'The board, the firmware, the broker, the database, the cluster, the model and the screen on the phone. I have yet to meet the other person who does both ends of both.',
    },
  },
  signal: {
    levels: ['site', 'area', 'device', 'reading'],
    anatomyLede: 'A topic is a path. Every device on this farm publishes to one built from the same four levels — so a subscription is really a question about which levels you care about.',
    legendPlus: 'matches exactly one level, whatever is in it',
    legendHash: 'matches everything below it, and has to be the last level',
    yourToken: 'you wrote',
    noToken: '—',
    subLabel: 'Your subscription',
    placeholder: 'farm/greenhouse/#',
    broker: 'Broker — everything being published',
    inbox: 'Your inbox — what reached you',
    delivered: 'delivered',
    dropped: 'not delivered',
    missionsTitle: 'Three subscriptions to get right',
    missionsLede: 'Any filter that selects exactly the right topics counts. There is more than one correct answer to each.',
    missions: [
      { id: 'greenhouse', goal: 'Everything the greenhouse publishes — and nothing else.' },
      { id: 'temps',      goal: 'Every temperature reading, wherever it comes from.' },
      { id: 'moisture',   goal: 'Every moisture reading on the farm, but not the one at home.' },
    ],
    solved: 'solved',
    invalidHash: '# has to be the last level, on its own',
    invalidPlus: '+ has to fill a whole level, on its own',
    invalidEmpty: 'a topic level cannot be empty',
    emptyInbox: 'nothing matched yet',
    allSolved: 'All three. You now know MQTT topic filters better than most people who use them daily.',
  },
  swarm: {
    lede: 'Traffic on this service spikes every few seconds, the way a launch day does. Add replicas and the latency falls; add too many and you are paying for idle machines. Then hand it to the autoscaler and watch where it still loses.',
    traffic: 'Incoming',
    replicas: 'Replicas',
    latency: 'p99 latency',
    dropped: 'Requests dropped',
    cost: 'Cost',
    saturation: 'Saturation',
    auto: 'Autoscaler',
    autoHint: 'Targeting 60% saturation. A new pod takes about 4s to become ready — which is why requests still drop on the way up.',
    manualHint: 'You are scaling by hand. The spike arrives whether you are ready or not.',
    ready: 'ready',
    starting: 'starting',
    reset: 'Reset counters',
    spike: 'spike',
    healthy: 'healthy',
    strained: 'strained',
    failing: 'dropping traffic',
    wasteful: 'over-provisioned',
  },
  mind: {
    lede: 'In 2021 I wrote a GAN that forecasts the next value of a time series — generator, discriminator and training loop from scratch. I trained it on thirty years of daily bars, because that is where clean history was free, but the network reads log returns and has no idea what the numbers measure. So here it is running on the soil probe from the chapters above. The part worth showing is this: the discriminator never judges a predicted reading on its own. The reading is glued onto the nine real ones before it, and the network has to say whether the whole window came off the sensor. That is the game. You are the discriminator.',
    paper: 'StockGAN · LSTM(128) · window of 10 · trained on 30 years of daily bars, running here on soil-1',
    reading: 'soil-1 · greenhouse · % moisture',
    question: 'One of these two windows ends with a reading the probe actually took. The other ends with one the generator invented. Which is which?',
    slotA: 'Window A',
    slotB: 'Window B',
    pick: 'Choose',
    real: 'REAL',
    generated: 'GENERATED',
    criticSays: 'discriminator scored it',
    next: 'Next window',
    reset: 'Start over',
    rounds: 'Rounds',
    you: 'You',
    network: 'The discriminator',
    fooled: 'It fooled the critic',
    lambdaLabel: 'λ — how much of the generator’s grade comes from fooling the critic instead of landing near the right number',
    lambdaHis: 'what I shipped',
    meterTruth: 'Close to the truth',
    meterReal: 'Moves like the sensor',
    arch: 'What is actually in the file',
    archGen: 'generator      LSTM(128, stateful) → Dropout(0.3) → Dense(n_features)',
    archDisc: 'discriminator  LSTM(128, stateful) → Dropout(0.1) → Dense(1, sigmoid)',
    archNote: 'RMSprop on a polynomial decay from 2.5e-4 down to 1e-4 over a thousand steps. Cross-entropy with label smoothing at 0.2, so the discriminator is never allowed to be completely sure of anything. Both the real and the generated target multiplied by noise at σ = 0.25 while training, so it cannot win by noticing which numbers are too clean. Twelve indicators — MACD, EMA, RSI, Bollinger, ROC, volatility — cut down by PCA and XGBoost before the network ever saw them; on a soil probe those same twelve become moving averages and rate of change of moisture, which is exactly the point: the architecture changed domain and the feature pipeline barely blinked. The loss functions on this page are ports of the real ones, constants included; the generator here is a stand-in that reproduces the trade-off without carrying 128 LSTM units into your browser.',
    hintStart: 'Pick one. Nine real readings, and a tenth that is either the probe or my generator.',
    hintRight: 'Right.',
    hintWrong: 'Wrong — and look at the two scores underneath. That is the same judgement the network makes, on the same window.',
    hintLow: 'Down here the generator is graded on squared error almost alone, so it answers with the conditional mean: the safest possible guess. It is the most accurate thing it can say and it is obviously fake — the step is a third the size of a real one. Every forecaster trained on MSE alone has this problem, and most of them never find out.',
    hintHigh: 'Up here it is graded only on fooling the critic. The readings finally move the way the sensor moves, and the numbers are further from the next hour than they have ever been. It looks right. It is not right.',
    hintHis: '0.6 is what I shipped: leaning toward the critic, and paying about two tenths of a point of error for it. No setting wins both meters — which is exactly why that number is a decision and not a default.',
    verdict: 'You are at {you} across these rounds. The network is at {net} on the same windows.',
  },
  ledger: {
    lede: 'One account, one instrument, twenty lots a click. Buy and sell by hand and watch what each order does to the funds available — then switch the funds check over and do it again.',
    modeLabel: 'Funds check',
    modeGross: 'Order notional',
    modeNet: 'Net exposure',
    price: 'Price',
    position: 'Position',
    equityLabel: 'Equity',
    lockedLabel: 'Tied up',
    availableLabel: 'Available',
    flat: 'flat',
    buy: 'Buy 20',
    sell: 'Sell 20',
    reset: 'Reset',
    replay: 'Replay the session',
    replayTitle: 'The same forty orders, both ways',
    grossLabel: 'Checked against the order',
    netLabel: 'Checked against the exposure',
    hintStart: 'Start with a couple of buys, then try to sell out of them. Watch what the sell does to the funds available under each check.',
    hintAccepted: 'Filled — {side} {qty} at {price}.',
    hintFunds: 'Rejected. The engine wants {need} tied up and the account is worth {have} — even when the order would have made the position smaller.',
    hintReplay: '{filled} of {orders} orders filled\n{trips} round trips\n{pnl} realised',
  },
  service: {
    lede: 'A table of sensor readings, 240,000 rows deep. Pick a query, decide which columns get an index, and run it. The strip below is the table; watch how much of it the database has to touch.',
    table: 'readings · 240,000 rows',
    indexes: 'CREATE INDEX ON',
    query: 'Query',
    run: 'Run',
    running: 'Running…',
    rows: 'Rows examined',
    time: 'Query time',
    speedup: 'vs full scan',
    writes: 'Write cost',
    queryLabels: {
      point: 'one row by id',
      selective: 'one sensor · 5%',
      broad: 'most of the table · 60%',
    },
    hints: {
      'no-index': 'There is no index on that column, so the database has no choice. It opens the table at the first row and reads every one of the 240,000 to be sure it has not missed any.',
      'index-used': 'The index went straight there — eighteen steps down the tree, then the rows themselves. Same query, same data, same machine.',
      'not-selective': 'The index exists, and the planner refused to use it. This query wants 60% of the table, and jumping around an index for that costs more than reading everything in order. Building it bought you nothing here — and it still slows down every single write.',
    },
    treeLabel: 'index · B-tree',
    heapLabel: 'table',
  },
  copper: {
    lede: 'This is not an illustration. It is AGROM.brd, the board I laid out in 2017 for the soil probe — 70 mm across, two copper layers, 54 components — read straight out of the EAGLE file and drawn here. Pick a net and follow it.',
    viewLabel: 'View',
    layersLabel: 'Layers',
    view2d: 'Flat',
    view3d: 'Stack',
    viewSolid: 'Assembled',
    flip: 'Turn over',
    componentsWord: 'components',
    underneathWord: 'underneath',
    hintSolid: 'The same board with its parts on it, built from the IDF file EAGLE exported to the mechanical CAD in 2017 — every footprint, position, rotation and side is out of that file. Nineteen of the 59 parts are mounted underneath. Turn it over and you will find them.',
    explode: 'Separation',
    spin: 'drag to turn',
    hintStack: 'This is the same board, seen edge-on. Two sheets of copper with 1.6 mm of fibreglass between them, and 34 plated posts stitching them together. Every yellow post is a via — the only way a signal gets from one face to the other.',
    both: 'Both',
    topOnly: 'Top only',
    bottomOnly: 'Bottom only',
    netsLabel: 'Nets',
    allNets: 'All',
    segments: 'Segments',
    crossings: 'Layer changes',
    length: 'Copper length',
    legendTop: 'top copper',
    legendBottom: 'bottom copper',
    legendVia: 'via',
    hintIdle: 'Red runs on the top face, blue on the bottom. Every yellow ring is a via: a plated hole where a track drops through to the other side.',
    hintCrossings: 'The {net} net changes layer {n} times. Switch to one layer and watch it break into pieces — those gaps are where it is running on the face you just hid.',
    hintFlat: 'The {net} net never leaves its layer. Nothing was in its way, so it never had to dive.',
    hintOneLayer: 'Half the board just vanished. Everything missing is running on the other face — and the only reason it can is that the two faces are stitched together by vias.',
  },
  steel: {
    lede: 'The assemblies the mechanical project is organised into, one folder each, rebuilt from the drawings they were machined to. Pick one, pull it apart, and read what it is made of.',
    productLabel: 'Product',
    explode: 'Exploded view',
    zoom: 'Zoom',
    reset: 'Reset view',
    loading: 'loading the printed parts…',
    spin: 'drag to turn',
    autoSpin: 'Spin',
    pieces: 'Pieces',
    span: 'Largest dimension',
    provenance: 'Turned and cut parts are built from their dimensioned drawings. Printed parts are their real STLs. The arrangement is matched to the 2017 renders, because the SolidWorks assemblies cannot be read.',
    processTitle: 'The giveaway is the folder structure',
    processLede: 'The mechanical project is not filed by part. It is filed by how each part gets made — which is the difference between modelling something and specifying it.',
    processes: [
      { label: 'Turning & machining', count: 11, note: 'each with a dimensioned drawing' },
      { label: 'Laser cutting', count: 5, note: 'flat acrylic, drawn and toleranced' },
      { label: '3D printing', count: 7, note: 'the parts loaded here as STLs' },
      { label: 'Bought in', count: 14, note: 'sensors, cells, connectors' },
      { label: 'Cable assembly', count: 1, note: 'a four-way loom' },
    ],
    drawings: '16 dimensioned drawings · 82 line items across 7 bills of material',
    products: {
      'station': { name: 'Full weather station', kind: 'the complete station', blurb: 'Every assembly below, standing where the 2017 render puts it.' },
      'cabeca-os': { name: 'Head 1 · Soil only', kind: 'soil-only head', blurb: 'The machined collar, the printed spine and cap, laser-cut acrylic, and two photovoltaic cells.' },
      'cabeca-ws': { name: 'Head 2 · Weather station', kind: 'weather-station head', blurb: 'The same head, carrying a UV sensor and a TIL-78 where the cells were.' },
      'corpo': { name: 'Mast', kind: 'the mast', blurb: 'A cone, four couplings, six spacers and the metre-long tube. The spacers are what set the depths the buried sensors sit at.' },
      'painel': { name: 'Solar array', kind: 'solar array', blurb: 'Two panels on two machined brackets.' },
      'pcb': { name: 'PCB', kind: 'the board, in the mechanical model', blurb: 'The laminate and both populated faces — the same IDF export chapter 02 builds its board from.' },
      'air': { name: 'Sensor 0 · AIR', kind: 'surface unit', blurb: 'The rod, its machined seat, and the printed battery cradle with its lid.' },
      'thd': { name: 'Sensor 1 · THD', kind: 'buried soil sensor', blurb: 'A ribbed machined body under a laser-cut acrylic cap, potted in epoxy, with an M12 lead.' },
      'gas': { name: 'Sensor 5 · GAS STATION', kind: 'gas sensor bank', blurb: 'MQ-2, MQ-7 and MQ-8 with a barometer, on a printed mount under a vented cap.' },
    },
  },
  system: {
    lede: 'One moisture reading, from the pin in the ground to the number on a phone. Press play. Then break something — click any stage — and run it again, because the interesting part is not that it works.',
    play: 'Send a reading',
    running: 'in flight…',
    again: 'Send another',
    repair: 'Repair all',
    total: 'End to end',
    verdictArrived: 'Arrived. Eight layers, one number, and nobody had to think about any of it.',
    verdictFailed: 'Stopped at {stage}.',
    breakHint: 'Click a stage to break it.',
    silentBadge: 'still returns a number',
    goto: 'chapter',
    stages: {
      silicon: { name: 'Silicon', does: 'The ADC samples the probe', payload: 'ADC 2871 / 4095', broken: 'The pin reads nothing. Every number above this is now a guess about a wire.' },
      copper:  { name: 'Copper',  does: 'Across the board to the radio', payload: '1.63 V', broken: 'A hairline crack in a trace. Intermittent — the worst kind, because it passes on the bench.' },
      steel:   { name: 'Steel',   does: 'Out through the sealed head', payload: 'M12 · IP67', broken: 'Water past the seal. The reading still arrives, on time, and it is wrong. Nothing alerts.' },
      signal:  { name: 'Signal',  does: 'Published to the broker', payload: 'farm/greenhouse/soil-1/moisture', broken: 'The broker is unreachable. The device keeps measuring perfectly and nobody is listening.' },
      service: { name: 'Service', does: 'Written to the database', payload: 'INSERT → reading_id 128374', broken: 'The API answers and the write fails. The dashboard confidently shows yesterday.' },
      swarm:   { name: 'Swarm',   does: 'Handled by a replica', payload: 'pod 7/12', broken: 'No replica free. 503 — and the retries make the queue worse than the outage.' },
      model:   { name: 'Model',   does: 'Classified by the model', payload: 'healthy · 0.94', broken: 'The model answers, confidently, about soil it has never seen. A number, and no way to know it is wrong.' },
      glass:   { name: 'Glass',   does: 'Rendered on the phone', payload: '43 % moisture', broken: 'Everything upstream worked. The screen shows nothing, because nobody built the empty state.' },
    },
  },
  glass: {
    lede: 'One card, written twice and shown on both phones. Change anything below and watch the two dialects say the same thing — because they are two ways of phrasing a screen, not two different screens.',
    accent: 'Accent',
    layout: 'Arrangement',
    radius: 'Corner radius',
    stacked: 'Stacked',
    inline: 'Inline',
    device: 'Device',
    iphone: 'iPhone',
    android: 'Android',
    card: {
      sensor: 'soil-1 · greenhouse', status: 'healthy', age: '2 s',
      delta: '2.4', depth: '40 cm', depthLabel: 'depth', soil: '22.4 °C', soilLabel: 'soil',
    },
    noteTitle: 'Watch what each one has to change',
    note: 'SwiftUI swaps VStack for HStack and keeps the same spacing: parameter. Flutter swaps Column for Row — every SizedBox has to change axis with it, height becoming width, {n} of them here, and the value has to be wrapped in Expanded to share the row at all. Neither is wrong; one is more places to be wrong.',
    swiftOnAndroid: 'SwiftUI does not run here. Flutter does — which is the whole reason to know both.',
  },
  flow: {
    lede: 'This is what Tradx does, in miniature. You do not write the loop — you wire the logic, and the engine runs it over the candles. Move the parameters and watch the graph and the trades change together.',
    period: 'RSI period',
    buyLevel: 'Enter above',
    sellLevel: 'Leave below',
    run: 'Run',
    inSample: 'Tune on this half',
    outSample: 'The half you never saw',
    trades: 'Trades',
    returnPct: 'Return',
    winRate: 'Win rate',
    nodes: {
      source: 'Market data', rsi: 'RSI indicator', crossUp: 'Cross up',
      crossDown: 'Cross down', entry: 'Market entry', exit: 'Market exit',
    },
    hintIn: 'Tune it until the number is beautiful. That is the easy part, and it is what every backtest screenshot on the internet is showing you.',
    hintOut: 'Same graph, same parameters, a stretch of market it has never been fitted to.',
    reveal: 'Across all 75,429 parameter combinations, the set that returned most on the half you tuned on came 22,949th on the half you had not seen. First place to twenty-two thousandth. That is why a backtest is a hypothesis and not a result, and why the beautiful number is the easy part.',
  },
  field: {
    lede: 'One object, built twice. On the left of the switch it is the mesh from chapter 03, the one the part was printed from. On the right it is a field of gaussians over that same mesh — scattered here rather than fitted, so the two can sit side by side and the difference is the method and nothing else.',
    mesh: 'Mesh', splats: 'Gaussians',
    count: 'Gaussians', size: 'Spread', spin: 'drag to turn',
    primitives: 'Primitives', authored: 'Authored by hand',
    authoredMesh: 'every triangle', authoredSplat: 'none of them',
    hintMesh: '997 triangles, each one placed by somebody in SolidWorks in 2017.',
    hintSplats: 'Nobody placed these. In a real reconstruction they start as noise and are moved, stretched and recoloured by gradient descent until the render stops disagreeing with the photographs — which is why the count runs to hundreds of thousands and nobody minds.',
    loading: 'loading the mesh…',
  },
  ui: {
    duty: 'Duty cycle',
    brightness: 'Perceived brightness',
    frequency: 'Frequency',
    play: 'Play',
    pause: 'Pause',
    reset: 'Reset',
    subscribe: 'Subscribe',
    publish: 'Publish',
    matched: 'matched',
    dropped: 'not delivered',
    replicas: 'Replicas',
    traffic: 'Incoming traffic',
    latency: 'p99 latency',
    dropped_req: 'Dropped requests',
    cost: 'Cost',
    train: 'Train',
    epoch: 'Epoch',
    accuracy: 'Accuracy',
    wip: 'Interactive build in progress',
    wipNote: 'The layout is final; this panel is being wired up.',
    learned: 'What you just learned',
  },
};
