import type { Content } from './types';

export const en: Content = {
  meta: {
    title: 'Maykon Meneghel — the playable CV',
    description:
      'Senior full-stack engineer with a Master in AI. Firmware, PCBs, CAD, MQTT, Kubernetes, Swift and Flutter — explained through mini-games you can play right on the page.',
  },
  nav: { chapters: 'Chapters', family: 'The family', contact: 'Contact', resume: 'Résumé' },
  hero: {
    kicker: 'Senior Mobile Engineer · iOS & Flutter · and the APIs behind them',
    name: 'Maykon Meneghel',
    headline: 'I ship the app and the API it talks to.',
    sub: 'Most CVs tell you what someone can do. This one lets you try it. Every chapter is a working mini-game: write the same screen twice in SwiftUI and Flutter, plan a query, scale a service under load, and watch an order become a trade — without leaving this page.',
    proof: [
      'Tradx · published on the Mac App Store',
      'Trainee to Senior in four years on a production Apple engagement',
      'Clean Architecture for SwiftUI · 30★ on GitHub',
      'Apple Developer Academy · postgraduate iOS specialization',
    ],
    links: [
      { label: 'LinkedIn', href: 'https://www.linkedin.com/in/maykonmeneghel/' },
      { label: 'GitHub', href: 'https://github.com/maykonmeneghel' },
      { label: 'Tradx on the App Store', href: 'https://apps.apple.com/us/app/tradx/id6743033919' },
    ],
    cv: 'Download CV (PDF)',
    cta: 'Start the tour',
    scrollHint: 'scroll',
    boot: [
      'meneghel.me boot v2.0',
      'loading platforms ...... ios 17 · android 14 · swift 6 · dart 3',
      'mounting frameworks .... swiftui · uikit · flutter · jetpack compose',
      'starting services ...... node · nestjs · java · docker · kubernetes',
      'loading intelligence ... pytorch · gan · gaussian splatting',
      'ready.',
    ],
  },
  acts: [
    {
      before: 'glass',
      label: 'Act one',
      title: 'The screen',
      lede: 'Seven years of shipping apps, native and cross-platform. Two years at the Apple Developer Academy, four on a production Apple engagement that took me from trainee to senior, and a desktop trading client of my own on the Mac App Store. This is the part of the stack I am hired for.',
    },
    {
      before: 'service',
      label: 'Act two',
      title: 'What the app talks to',
      lede: 'An app is only as good as what answers it. These four chapters are the other half of the same job — the API, the database it reads, the cluster it runs on, and a trading engine where the order the app sends is not the trade that comes back.',
    },
    {
      before: 'mind',
      label: 'Act three',
      title: 'And the models underneath',
      lede: 'Where the postgraduate work in AI stops being a line on a diploma: a GAN written from scratch, and the Gaussian Splatting work I do now.',
    },
  ],
  hardwarePage: {
    title: 'Maykon Meneghel — the hardware years',
    description: 'Before the apps: a soil probe designed, routed, machined and put in the ground. Firmware, PCB, CAD and MQTT, all playable.',
    back: 'Back to the portfolio',
    kicker: 'The plus',
    heading: 'Before the apps, I made the thing that sends the data',
    lede: 'These four chapters used to open the site, and they are the reason people came away calling me an IoT engineer. They are still here because a soil probe designed, routed, machined and buried is not a common thing for a mobile engineer to have done — and because knowing what a packet costs before it reaches your app changes how you build the app.',
    outro: 'That is where it started. The work it turned into is on the other page.',
    backCta: 'See what I build now',
  },
  chapters: [
    {
      track: 'mobile', codename: 'THREAD', slug: 'thread',
      era: 'iOS & Flutter · 2019 → today',
      title: 'The frame is sixteen milliseconds long',
      lede: 'Every argument a mobile team has about concurrency is really an argument about one number. A screen owes a frame every 16.7 ms, and everything — async/await, actors, isolates, cancellation — is about what you are allowed to do inside it. Below is the same list loaded three ways, with the frame graph a profiler would show you.',
      panel: 'instruments · frame timing',
      takeaway: 'The middle button is the whole chapter. <b>await suspends a function, it does not move it</b> — the continuation resumes on the main actor and the expensive work still lands in a frame. Async code that never leaves the main thread is the most common performance bug in mobile, and it is invisible until somebody profiles it.',
      stack: ['Swift Concurrency', 'async/await', 'actors', '@MainActor', 'Combine', 'Isolates', 'compute()', 'Instruments', 'Task cancellation', '60 fps'],
    },
    {
      track: 'mobile', codename: 'GLASS', slug: 'glass',
      era: 'Swift & Flutter · 2019 → today',
      title: 'The card that survives the real world',
      lede: 'Anyone can build the card in the design. The job is building the one that is still readable when the person holding the phone has set text to the largest accessibility size, is in split view, in a language whose words run longer, reading right to left, on a connection that never delivered the image. A designer hands you one state. You ship six.',
      panel: 'PositionRow.swift / position_row.dart',
      takeaway: 'The layout drawn to the comp survives one of the seven conditions below — the one it was drawn for. <b>The difference is not taste, it is which question the layout asks</b>: not "is the type large?" but "does this fit?". Ask the second one and a longer translation stops being a bug report.',
      stack: ['SwiftUI', 'UIKit', 'Flutter', 'Dynamic Type', 'VoiceOver', 'Localization', 'RTL', 'Adaptive layout', 'Accessibility', 'Design systems'],
    },
    {
      track: 'platform', codename: 'SERVICE', slug: 'service',
      era: 'Backend · 2018 → today',
      title: 'Somebody has to remember all of it',
      lede: 'Messages are ephemeral; the business is not. Behind every device sits an API and a database, and the difference between a fast product and a slow one is usually one decision made here.',
      panel: 'psql · meneghel_db',
      takeaway: 'Without an index the database reads <b>every row</b> to answer you. With one, it jumps straight there. Same query, same data, same server — a thousand times faster.',
      stack: ['Node.js', 'Express', 'Restify', 'MongoDB', 'PostgreSQL', 'REST'],
    },
    {
      track: 'platform', codename: 'SWARM', slug: 'swarm',
      era: 'Backend · 2018 → today',
      title: 'One box is never enough',
      lede: 'Traffic does not arrive politely. It arrives all at once, at 3am, on launch day. Containers and Kubernetes are how you answer that without waking up.',
      panel: 'kubectl · production',
      takeaway: 'You did not make the code faster — you made <b>more of it</b>. Horizontal scaling trades money for latency, and an autoscaler makes that trade for you, automatically.',
      stack: ['Docker', 'Kubernetes', 'HPA', 'Load balancing', 'CI/CD'],
    },
    {
      track: 'platform', codename: 'FLOW', slug: 'flow',
      era: 'Tradx · 2022 → today',
      title: 'And then I built the tool',
      lede: 'A forecast has to live somewhere. Tradx is where mine does — the company I co-founded in 2022 and run as COO, a desk where a trading strategy is a graph you wire rather than code you write.',
      panel: 'tradx · strategy graph',
      takeaway: 'A backtest is a <b>hypothesis</b>, not a result. Anyone can tune a curve until it is beautiful on the data they already have; the entire craft is knowing what that number is worth on the data they do not.',
      stack: ['Node.js', 'NestJS', 'Flutter', 'MongoDB', 'Redis + BullMQ', 'Backtesting engine', 'Paper trading'],
    },
    {
      track: 'platform', codename: 'LEDGER', slug: 'ledger',
      era: 'Tradx · 2022 → today',
      title: 'An order is not a trade',
      lede: 'The chapter before this one produced a signal. This one is what happens to it. A strategy emits orders; an engine decides which of them become trades, and the distance between those two numbers is where a trading desk is actually built or lost.',
      panel: 'tradx · execution engine',
      takeaway: 'The engine refused thirty-eight orders and reported a funds problem. It did not have one. <b>A sell against a long releases buying power</b> — an engine that checks the order instead of the resulting exposure will block the trades that reduce risk and call it prudence.',
      stack: ['NestJS', 'Order lifecycle', 'Position netting', 'Idempotency', 'Redis + BullMQ', 'Paper trading'],
    },
    {
      track: 'ai', codename: 'MIND', slug: 'mind',
      era: 'StockGAN · 2021',
      title: 'Teach the machine to guess what happens next',
      lede: 'In 2021 I built a generative adversarial network for time series from scratch — the work where my postgraduate specialization in AI and my Master in Bioengineering stop being lines on a diploma — two networks, one trying to invent the next reading and one trying to catch it lying. I trained it on financial data. It runs here on the soil probe from the chapters above, unchanged, because a time series does not know what it measures.',
      panel: 'gan_model.py — train_step()',
      takeaway: 'Two models, one loss function, and a knob between them. Grade the forecaster on being close and it answers with the average of everything, which is safe and useless. Grade it on being believable and it answers with something that moves like the sensor and knows nothing. <b>Every model I ship is that trade made on purpose</b>, written down, and measured.',
      stack: ['TensorFlow / Keras', 'GANs', 'LSTM', 'Time series', 'PCA & XGBoost feature selection'],
    },
    {
      track: 'ai', codename: 'FIELD', slug: 'field',
      era: 'Gaussian splatting · today',
      title: 'And now the object is made of light',
      lede: 'What I spend my days on now: Gaussian Splatting. A scene stops being a surface someone modelled and becomes a cloud of oriented gaussians, fitted by gradient descent until renders of them match the photographs. Real reconstructions start from a camera walking around a room. The demo below deliberately does not — it uses a part you already met in chapter 03, because the only way to see what the method changes is to watch the same object built both ways.',
      panel: 'gaussian splatting · viewer',
      takeaway: 'A mesh says where the <b>surfaces</b> are, and an engineer drew every one. A splat field says where the <b>light</b> is, and nobody drew any of it — it was fitted until the render stopped disagreeing with the photograph.',
      stack: ['Gaussian Splatting', '3DGS', 'PyTorch', 'CUDA', 'Photogrammetry', 'Radiance fields'],
    },


    {
      track: 'hardware', codename: 'SILICON', slug: 'silicon',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'It starts with a single pin',
      lede: 'Long before there is an app, there is a microcontroller deciding — millions of times per second — whether one wire is high or low. Fourteen firmwares taught me that everything above depends on getting this right.',
      panel: 'pwm_playground.c',
      takeaway: 'You just dimmed an LED without ever changing its voltage. That is <b>PWM</b>: the pin is only ever fully on or fully off — it simply switches faster than your eye can follow.',
      stack: ['C/C++', 'ESP32', 'PIC18F4550', 'ATmega', 'Timers & PWM'],
    },
    {
      track: 'hardware', codename: 'COPPER', slug: 'copper',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Then it needs a board',
      lede: 'A schematic is a promise. The PCB is where you keep it. Every board I have fabricated started as this exact puzzle: get every signal where it belongs, on a surface where nothing may cross.',
      panel: 'router.pcb',
      takeaway: 'Two traces cannot cross on the same layer. That single constraint is the reason real boards have 2, 4, sometimes 12 layers stacked on top of each other.',
      stack: ['Altium', 'EAGLE', 'SMD & THT', 'Gerber', 'Design for manufacturing'],
    },
    {
      track: 'hardware', codename: 'STEEL', slug: 'steel',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'And a body to survive the field',
      lede: 'A sensor buried in wet soil for two years does not care how elegant your firmware is. It cares about the enclosure. So I model it myself — every part, every tolerance, every seal.',
      panel: 'soil_probe.sldasm',
      takeaway: 'Hardware is the one layer you cannot patch remotely. That is why the mechanical design happens <b>before</b> the first line of firmware, not after.',
      stack: ['SolidWorks', '3D modelling', 'Tolerancing', 'IP sealing', '3D printing'],
    },
    {
      track: 'hardware', codename: 'SIGNAL', slug: 'signal',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Now make a thousand of them talk',
      lede: 'One device is a project. A thousand devices is an architecture. MQTT is how they speak without ever knowing one another — and topic wildcards are the whole trick.',
      panel: 'broker · mqtt://meneghel.me:8883',
      takeaway: '<b>+</b> matches exactly one level. <b>#</b> matches everything below it. That one rule is how a single broker fans out to thousands of devices without any of them holding a list of the others.',
      stack: ['MQTT', 'Mosquitto', 'AWS IoT Core', 'QoS 0/1/2', 'Pub/Sub'],
    },
  ],
  record: {
    eyebrow: '12 · RECORD',
    title: 'The receipts',
    lede: 'Nine chapters of demonstration. This one is just evidence. Drag through the years and watch what was running at the same time — because the honest headline of this timeline is not any single job, it is how rarely there was only one.',
    lanes: {
      education: 'Education',
      research: 'Research',
      industry: 'Industry',
      venture: 'Ventures',
    },
    roles: {
      grad: 'B.Eng. Control & Automation Engineering',
      msc: 'M.Sc. Bioengineering',
      academy: 'Postgraduate specialization, iOS Development',
      aiSpec: 'Specialization, Applied Artificial Intelligence',
      pucLab: 'Trainee, Laboratory of Automation and Systems',
      araucaria: 'Software Engineer — applied research, AI and embedded health',
      freelance: 'Software Developer, freelance',
      residency: 'Trainee · Apple Residency',
      junior: 'Junior Developer · Apple Project',
      techLead: 'Tech Lead · Apple Internship',
      fullstack: 'Full Stack Developer · Apple Project',
      senior: 'Senior Developer · Apple Project',
      ghel: 'Technology Advisor · Renault Project',
      holding: 'Administrative Advisor — the family holding',
      tradx: 'COO & Co-founder',
    },
    scrubber: {
      simultaneous: '{n} roles at once',
      one: '1 role',
      none: 'nothing on record yet',
      today: 'today',
      drag: 'drag the year',
    },
    ventures: {
      title: 'Six companies',
      lede: 'Founded or co-founded. Some grew, some did not — which is the point of founding six.',
      founder: 'Founder',
      coFounder: 'Co-founder',
      sectors: { fintech: 'fintech', agritech: 'agritech', smartHome: 'smart home', proptech: 'proptech', edtech: 'edtech' },
    },
    publications: {
      title: 'Published and awarded',
      lede: 'Peer-reviewed work, mostly at the seam between engineering and health.',
      read: 'read the paper',
      code: 'source',
      items: {
        soilInstrument: 'Instrument for Measuring Factors and/or Natural Elements of the Soil',
        fesTool: 'A Tool to Select FES Parameters for chronic SCI',
        fallDetector: 'Indoors Wi-Fi Fall Detector Buckle for the Elderly',
        inSilicoFes: 'Application, in silico, of electrical stimuli in a neuro-muscular model compatible with chronic spinal cord injury',
        balanceModel: 'Mathematical modeling of the balance maintenance system using system identification techniques',
        stockGan: 'Forecasting financial series with Generative Adversarial Networks',
      },
    },
    press: {
      title: 'In the press',
      items: {
        hubli: 'Hubli, built at the Apple Developer Academy, featured by Apple',
        neonWave: 'Neon Wave, an iOS game covered by MacMagazine',
      },
    },
    closing: {
      line: 'Senior full-stack, from the solder joint to the model in production — in agribusiness and in financial markets.',
      note: 'The board, the firmware, the broker, the database, the cluster, the model and the screen on the phone. I have yet to meet the other person who does both ends of both.',
    },
    contact: {
      title: 'Talk to me',
      lede: 'If any of this is the shape of a problem you have, I would like to hear about it. Email or LinkedIn, whichever you prefer — the CV is a two-page PDF and the code is on GitHub.',
      linkedin: 'Message me on LinkedIn',
      github: 'Read my code',
      email: 'Email me',
      cv: 'Download my CV',
    },
    skills: {
      title: 'What I work with',
      lede: 'Everything below is credited by a chapter on this page or sitting in a public repository. Nothing here is aspirational.',
      groups: {
        ios: 'iOS · Swift',
        cross: 'Cross-platform',
        release: 'Shipping & release',
        languages: 'Languages',
        backend: 'Backend & APIs',
        data: 'Data',
        cloud: 'Cloud & DevOps',
        frontend: 'Web',
        ai: 'AI & 3D',
        embedded: 'Embedded & hardware',
        ways: 'Ways of working',
      },
    },
  },
  signal: {
    levels: ['site', 'area', 'device', 'reading'],
    anatomyLede: 'A topic is a path. Every device on this farm publishes to one built from the same four levels — so a subscription is really a question about which levels you care about.',
    legendPlus: 'matches exactly one level, whatever is in it',
    legendHash: 'matches everything below it, and has to be the last level',
    yourToken: 'you wrote',
    noToken: '—',
    subLabel: 'Your subscription',
    placeholder: 'farm/greenhouse/#',
    broker: 'Broker — everything being published',
    inbox: 'Your inbox — what reached you',
    delivered: 'delivered',
    dropped: 'not delivered',
    missionsTitle: 'Three subscriptions to get right',
    missionsLede: 'Any filter that selects exactly the right topics counts. There is more than one correct answer to each.',
    missions: [
      { id: 'greenhouse', goal: 'Everything the greenhouse publishes — and nothing else.' },
      { id: 'temps',      goal: 'Every temperature reading, wherever it comes from.' },
      { id: 'moisture',   goal: 'Every moisture reading on the farm, but not the one at home.' },
    ],
    solved: 'solved',
    invalidHash: '# has to be the last level, on its own',
    invalidPlus: '+ has to fill a whole level, on its own',
    invalidEmpty: 'a topic level cannot be empty',
    emptyInbox: 'nothing matched yet',
    allSolved: 'All three. You now know MQTT topic filters better than most people who use them daily.',
  },
  swarm: {
    lede: 'Traffic on this service spikes every few seconds, the way a launch day does. Add replicas and the latency falls; add too many and you are paying for idle machines. Then hand it to the autoscaler and watch where it still loses.',
    traffic: 'Incoming',
    replicas: 'Replicas',
    latency: 'p99 latency',
    dropped: 'Requests dropped',
    cost: 'Cost',
    saturation: 'Saturation',
    auto: 'Autoscaler',
    autoHint: 'Targeting 60% saturation. A new pod takes about 4s to become ready — which is why requests still drop on the way up.',
    manualHint: 'You are scaling by hand. The spike arrives whether you are ready or not.',
    ready: 'ready',
    starting: 'starting',
    reset: 'Reset counters',
    spike: 'spike',
    healthy: 'healthy',
    strained: 'strained',
    failing: 'dropping traffic',
    wasteful: 'over-provisioned',
  },
  mind: {
    lede: 'In 2021 I wrote a GAN that forecasts the next value of a time series — generator, discriminator and training loop from scratch. I trained it on thirty years of daily bars, because that is where clean history was free, but the network reads log returns and has no idea what the numbers measure. So here it is running on the soil probe from the chapters above. The part worth showing is this: the discriminator never judges a predicted reading on its own. The reading is glued onto the nine real ones before it, and the network has to say whether the whole window came off the sensor. That is the game. You are the discriminator.',
    paper: 'StockGAN · LSTM(128) · window of 10 · trained on 30 years of daily bars, running here on soil-1',
    reading: 'soil-1 · greenhouse · % moisture',
    question: 'One of these two windows ends with a reading the probe actually took. The other ends with one the generator invented. Which is which?',
    slotA: 'Window A',
    slotB: 'Window B',
    pick: 'Choose',
    real: 'REAL',
    generated: 'GENERATED',
    criticSays: 'discriminator scored it',
    next: 'Next window',
    reset: 'Start over',
    rounds: 'Rounds',
    you: 'You',
    network: 'The discriminator',
    fooled: 'It fooled the critic',
    lambdaLabel: 'λ — how much of the generator’s grade comes from fooling the critic instead of landing near the right number',
    lambdaHis: 'what I shipped',
    meterTruth: 'Close to the truth',
    meterReal: 'Moves like the sensor',
    arch: 'What is actually in the file',
    archGen: 'generator      LSTM(128, stateful) → Dropout(0.3) → Dense(n_features)',
    archDisc: 'discriminator  LSTM(128, stateful) → Dropout(0.1) → Dense(1, sigmoid)',
    archNote: 'RMSprop on a polynomial decay from 2.5e-4 down to 1e-4 over a thousand steps. Cross-entropy with label smoothing at 0.2, so the discriminator is never allowed to be completely sure of anything. Both the real and the generated target multiplied by noise at σ = 0.25 while training, so it cannot win by noticing which numbers are too clean. Twelve indicators — MACD, EMA, RSI, Bollinger, ROC, volatility — cut down by PCA and XGBoost before the network ever saw them; on a soil probe those same twelve become moving averages and rate of change of moisture, which is exactly the point: the architecture changed domain and the feature pipeline barely blinked. The loss functions on this page are ports of the real ones, constants included; the generator here is a stand-in that reproduces the trade-off without carrying 128 LSTM units into your browser.',
    hintStart: 'Pick one. Nine real readings, and a tenth that is either the probe or my generator.',
    hintRight: 'Right.',
    hintWrong: 'Wrong — and look at the two scores underneath. That is the same judgement the network makes, on the same window.',
    hintLow: 'Down here the generator is graded on squared error almost alone, so it answers with the conditional mean: the safest possible guess. It is the most accurate thing it can say and it is obviously fake — the step is a third the size of a real one. Every forecaster trained on MSE alone has this problem, and most of them never find out.',
    hintHigh: 'Up here it is graded only on fooling the critic. The readings finally move the way the sensor moves, and the numbers are further from the next hour than they have ever been. It looks right. It is not right.',
    hintHis: '0.6 is what I shipped: leaning toward the critic, and paying about two tenths of a point of error for it. No setting wins both meters — which is exactly why that number is a decision and not a default.',
    verdict: 'You are at {you} across these rounds. The network is at {net} on the same windows.',
  },
  thread: {
    lede: 'A screen owes a frame every 16.7 ms. This one is loading twenty-four rows, and the only thing that changes between the three buttons is where the decode happens. Watch the frame graph, not the list.',
    pickLabel: 'Where the work runs',
    device: 'iPhone · 60 Hz',
    frozen: 'not responding',
    frameTimes: 'Frame times',
    budget: '16.7 ms budget',
    onBudget: 'on budget',
    dropped: 'dropped',
    worst: 'Worst frame',
    droppedFrames: 'Dropped frames',
    jank: 'Jank',
    wasted: 'Wasted after leaving',
    leave: 'Leave the screen at frame 6',
    cancelOn: 'cancel the work',
    cancelOff: 'let it finish',
    strategies: {
      sync: {
        name: 'On the main thread',
        hint: 'One frame that lasts almost three hundred milliseconds. The list does not stutter — it stops, and the operating system starts thinking about whether your app is still alive. Every mobile engineer has shipped this once.',
        swift: '// Everything, right now, on the main actor.\n@MainActor\nfunc load(_ rows: [Row]) {\n  for row in rows {\n    let image = decode(row.data)   // blocks the frame\n    cache[row.id] = image\n  }\n}',
        dart: '// Everything, right now, on the UI isolate.\nvoid load(List<Row> rows) {\n  for (final row in rows) {\n    final image = decode(row.data);  // blocks the frame\n    cache[row.id] = image;\n  }\n}',
      },
      await: {
        name: 'await, still on main',
        hint: 'This is the one that catches people. The freeze is gone and the jank is not: await suspends the function, it does not move it. The continuation resumes on the main actor and the decode happens there, so every row still overruns the budget. It looks fixed and it is not.',
        swift: '// Awaited — and still on the main actor.\n@MainActor\nfunc load(_ rows: [Row]) async {\n  for row in rows {\n    let image = await decode(row.data)\n    cache[row.id] = image          // resumes here, on main\n  }\n}',
        dart: '// Awaited — and still on the UI isolate.\nFuture<void> load(List<Row> rows) async {\n  for (final row in rows) {\n    final image = await decode(row.data);\n    cache[row.id] = image;           // resumes here, on the UI isolate\n  }\n}',
      },
      offMain: {
        name: 'Off the main actor',
        hint: 'Now the decode belongs to an actor — or an isolate — and the frame only pays to receive the finished row. Nothing is dropped, the worst frame is inside the budget, and the list scrolls the way it should have all along.',
        swift: '// The decode belongs to something that is not the UI.\nactor Decoder {\n  func decode(_ data: Data) -> UIImage { ... }\n}\n\nfunc load(_ rows: [Row]) async {\n  await withTaskGroup(of: (Row.ID, UIImage).self) { group in\n    for row in rows {\n      group.addTask { (row.id, await decoder.decode(row.data)) }\n    }\n    for await (id, image) in group {\n      await MainActor.run { cache[id] = image }\n    }\n  }\n}',
        dart: '// compute() moves the work to another isolate.\nFuture<void> load(List<Row> rows) async {\n  await Future.wait(rows.map((row) async {\n    final image = await compute(decodeBytes, row.data);\n    cache[row.id] = image;\n  }));\n}',
      },
    },
  },
  ledger: {
    lede: 'One account, one instrument, twenty lots a click. Buy and sell by hand and watch what each order does to the funds available — then switch the funds check over and do it again.',
    modeLabel: 'Funds check',
    modeGross: 'Order notional',
    modeNet: 'Net exposure',
    price: 'Price',
    position: 'Position',
    equityLabel: 'Equity',
    lockedLabel: 'Tied up',
    availableLabel: 'Available',
    flat: 'flat',
    buy: 'Buy 20',
    sell: 'Sell 20',
    reset: 'Reset',
    replay: 'Replay the session',
    replayTitle: 'The same forty orders, both ways',
    grossLabel: 'Checked against the order',
    netLabel: 'Checked against the exposure',
    hintStart: 'Start with a couple of buys, then try to sell out of them. Watch what the sell does to the funds available under each check.',
    hintAccepted: 'Filled — {side} {qty} at {price}.',
    hintFunds: 'Rejected. The engine wants {need} tied up and the account is worth {have} — even when the order would have made the position smaller.',
    hintReplay: '{filled} of {orders} orders filled\n{trips} round trips\n{pnl} realised',
  },
  service: {
    lede: 'A table of sensor readings, 240,000 rows deep. Pick a query, decide which columns get an index, and run it. The strip below is the table; watch how much of it the database has to touch.',
    table: 'readings · 240,000 rows',
    indexes: 'CREATE INDEX ON',
    query: 'Query',
    run: 'Run',
    running: 'Running…',
    rows: 'Rows examined',
    time: 'Query time',
    speedup: 'vs full scan',
    writes: 'Write cost',
    queryLabels: {
      point: 'one row by id',
      selective: 'one sensor · 5%',
      broad: 'most of the table · 60%',
    },
    hints: {
      'no-index': 'There is no index on that column, so the database has no choice. It opens the table at the first row and reads every one of the 240,000 to be sure it has not missed any.',
      'index-used': 'The index went straight there — eighteen steps down the tree, then the rows themselves. Same query, same data, same machine.',
      'not-selective': 'The index exists, and the planner refused to use it. This query wants 60% of the table, and jumping around an index for that costs more than reading everything in order. Building it bought you nothing here — and it still slows down every single write.',
    },
    treeLabel: 'index · B-tree',
    heapLabel: 'table',
  },
  copper: {
    lede: 'This is not an illustration. It is AGROM.brd, the board I laid out in 2017 for the soil probe — 70 mm across, two copper layers, 54 components — read straight out of the EAGLE file and drawn here. Pick a net and follow it.',
    viewLabel: 'View',
    layersLabel: 'Layers',
    view2d: 'Flat',
    view3d: 'Stack',
    viewSolid: 'Assembled',
    flip: 'Turn over',
    componentsWord: 'components',
    underneathWord: 'underneath',
    hintSolid: 'The same board with its parts on it, built from the IDF file EAGLE exported to the mechanical CAD in 2017 — every footprint, position, rotation and side is out of that file. Nineteen of the 59 parts are mounted underneath. Turn it over and you will find them.',
    explode: 'Separation',
    spin: 'drag to turn',
    hintStack: 'This is the same board, seen edge-on. Two sheets of copper with 1.6 mm of fibreglass between them, and 34 plated posts stitching them together. Every yellow post is a via — the only way a signal gets from one face to the other.',
    both: 'Both',
    topOnly: 'Top only',
    bottomOnly: 'Bottom only',
    netsLabel: 'Nets',
    allNets: 'All',
    segments: 'Segments',
    crossings: 'Layer changes',
    length: 'Copper length',
    legendTop: 'top copper',
    legendBottom: 'bottom copper',
    legendVia: 'via',
    hintIdle: 'Red runs on the top face, blue on the bottom. Every yellow ring is a via: a plated hole where a track drops through to the other side.',
    hintCrossings: 'The {net} net changes layer {n} times. Switch to one layer and watch it break into pieces — those gaps are where it is running on the face you just hid.',
    hintFlat: 'The {net} net never leaves its layer. Nothing was in its way, so it never had to dive.',
    hintOneLayer: 'Half the board just vanished. Everything missing is running on the other face — and the only reason it can is that the two faces are stitched together by vias.',
  },
  steel: {
    lede: 'The assemblies the mechanical project is organised into, one folder each, rebuilt from the drawings they were machined to. Pick one, pull it apart, and read what it is made of.',
    productLabel: 'Product',
    explode: 'Exploded view',
    zoom: 'Zoom',
    reset: 'Reset view',
    loading: 'loading the printed parts…',
    spin: 'drag to turn',
    autoSpin: 'Spin',
    pieces: 'Pieces',
    span: 'Largest dimension',
    provenance: 'Turned and cut parts are built from their dimensioned drawings. Printed parts are their real STLs. The arrangement is matched to the 2017 renders, because the SolidWorks assemblies cannot be read.',
    processTitle: 'The giveaway is the folder structure',
    processLede: 'The mechanical project is not filed by part. It is filed by how each part gets made — which is the difference between modelling something and specifying it.',
    processes: [
      { label: 'Turning & machining', count: 11, note: 'each with a dimensioned drawing' },
      { label: 'Laser cutting', count: 5, note: 'flat acrylic, drawn and toleranced' },
      { label: '3D printing', count: 7, note: 'the parts loaded here as STLs' },
      { label: 'Bought in', count: 14, note: 'sensors, cells, connectors' },
      { label: 'Cable assembly', count: 1, note: 'a four-way loom' },
    ],
    drawings: '16 dimensioned drawings · 82 line items across 7 bills of material',
    products: {
      'station': { name: 'Full weather station', kind: 'the complete station', blurb: 'Every assembly below, standing where the 2017 render puts it.' },
      'cabeca-os': { name: 'Head 1 · Soil only', kind: 'soil-only head', blurb: 'The machined collar, the printed spine and cap, laser-cut acrylic, and two photovoltaic cells.' },
      'cabeca-ws': { name: 'Head 2 · Weather station', kind: 'weather-station head', blurb: 'The same head, carrying a UV sensor and a TIL-78 where the cells were.' },
      'corpo': { name: 'Mast', kind: 'the mast', blurb: 'A cone, four couplings, six spacers and the metre-long tube. The spacers are what set the depths the buried sensors sit at.' },
      'painel': { name: 'Solar array', kind: 'solar array', blurb: 'Two panels on two machined brackets.' },
      'pcb': { name: 'PCB', kind: 'the board, in the mechanical model', blurb: 'The laminate and both populated faces — the same IDF export chapter 02 builds its board from.' },
      'air': { name: 'Sensor 0 · AIR', kind: 'surface unit', blurb: 'The rod, its machined seat, and the printed battery cradle with its lid.' },
      'thd': { name: 'Sensor 1 · THD', kind: 'buried soil sensor', blurb: 'A ribbed machined body under a laser-cut acrylic cap, potted in epoxy, with an M12 lead.' },
      'gas': { name: 'Sensor 5 · GAS STATION', kind: 'gas sensor bank', blurb: 'MQ-2, MQ-7 and MQ-8 with a barometer, on a printed mount under a vented cap.' },
    },
  },
  glass: {
    lede: 'One card, two builds. On the left is the card as it comes off a comp: one row, one line each, a height in points. On the right is the same card built to survive. Turn the conditions on and watch which one is still readable — the type size a person actually set, a narrow split view, a translation that runs longer, a right-to-left locale, an image that never arrived, an error with nowhere to go.',
    dynamicType: 'Dynamic Type',
    width: 'Available width',
    conditions: 'Conditions',
    longString: 'Longer translation',
    rtl: 'Right to left',
    noImage: 'Image never arrived',
    reset: 'Reset',
    errorText: 'We could not reach the broker. Your positions are safe.',
    stateLabel: 'View state',
    states: {
      loading: 'Loading',
      empty: 'Empty',
      error: 'Error',
      content: 'Content',
    },
    emptyTitle: 'No open positions',
    emptyBody: 'When you open one it will show up here, with its profit and loss.',
    emptyCta: 'Browse markets',
    errorTitle: 'Could not load your positions',
    errorCta: 'Try again',
    variants: {
      fixed: 'Built to the comp',
      adaptive: 'Built to survive',
    },
    failures: {
      none: 'nothing broken',
      'title-truncated': 'the title is cut off with an ellipsis',
      'value-collides': 'the number runs into the title',
      'subtitle-clipped': 'the subtitle is clipped',
      'mirrored-wrong': 'the chevron still points the wrong way and the number is on the wrong side',
      'image-hole': 'a forty-point empty square where the image never arrived',
      'error-hidden': 'the error has nowhere to go and is truncated to nothing',
      'target-too-small': 'the row is under the forty-four point minimum',
      'no-skeleton': 'the same card with empty labels, which reads as a bug rather than as loading',
      'no-empty-state': 'a blank card with a chevron that leads nowhere',
    },
    swift: '// The whole fix is three decisions.\nHStack(alignment: .firstTextBaseline, spacing: 12) {\n  if let image { Thumbnail(image) }        // no image, no box\n  VStack(alignment: .leading, spacing: 2) {\n    Text(position.symbol)\n      .font(.headline)\n      .lineLimit(nil)                      // let it wrap\n    if let error { Text(error).foregroundStyle(.red) }\n    else { Text(position.summary).font(.subheadline) }\n  }\n  Spacer(minLength: 12)\n  Text(position.pnl, format: .currency(code: code))\n    .monospacedDigit()\n}\n.padding(.horizontal, 16).padding(.vertical, 12)\n.frame(minHeight: 44)                      // grows, never clips\n.dynamicTypeSize(...DynamicTypeSize.accessibility5)\n.accessibilityElement(children: .combine)\n.accessibilityLabel(position.spokenLabel)',
    dart: '// Same three decisions, same order.\nRow(\n  crossAxisAlignment: CrossAxisAlignment.start,\n  children: [\n    if (image != null) Thumbnail(image!),\n    const SizedBox(width: 12),\n    Expanded(                              // min-width: 0, in Flutter\n      child: Column(\n        crossAxisAlignment: CrossAxisAlignment.start,\n        children: [\n          Text(p.symbol, style: t.titleMedium, softWrap: true),\n          error != null\n            ? Text(error!, style: t.bodySmall!.copyWith(color: cs.error))\n            : Text(p.summary, style: t.bodySmall),\n        ],\n      ),\n    ),\n    const SizedBox(width: 12),\n    Text(p.pnl, style: t.titleMedium),\n  ],\n)\n// Directionality mirrors the row; Semantics gives it one spoken label.',
  },
  flow: {
    lede: 'This is what Tradx does, in miniature. You do not write the loop — you wire the logic, and the engine runs it over the candles. Move the parameters and watch the graph and the trades change together.',
    period: 'RSI period',
    buyLevel: 'Enter above',
    sellLevel: 'Leave below',
    run: 'Run',
    inSample: 'Tune on this half',
    outSample: 'The half you never saw',
    trades: 'Trades',
    returnPct: 'Return',
    winRate: 'Win rate',
    nodes: {
      source: 'Market data', rsi: 'RSI indicator', crossUp: 'Cross up',
      crossDown: 'Cross down', entry: 'Market entry', exit: 'Market exit',
    },
    hintIn: 'Tune it until the number is beautiful. That is the easy part, and it is what every backtest screenshot on the internet is showing you.',
    hintOut: 'Same graph, same parameters, a stretch of market it has never been fitted to.',
    reveal: 'Across all 75,429 parameter combinations, the set that returned most on the half you tuned on came 22,949th on the half you had not seen. First place to twenty-two thousandth. That is why a backtest is a hypothesis and not a result, and why the beautiful number is the easy part.',
  },
  field: {
    lede: 'One object, built twice. On the left of the switch it is the mesh from chapter 03, the one the part was printed from. On the right it is a field of gaussians over that same mesh — scattered here rather than fitted, so the two can sit side by side and the difference is the method and nothing else.',
    mesh: 'Mesh', splats: 'Gaussians',
    count: 'Gaussians', size: 'Spread', spin: 'drag to turn',
    primitives: 'Primitives', authored: 'Authored by hand',
    authoredMesh: 'every triangle', authoredSplat: 'none of them',
    hintMesh: '997 triangles, each one placed by somebody in SolidWorks in 2017.',
    hintSplats: 'Nobody placed these. In a real reconstruction they start as noise and are moved, stretched and recoloured by gradient descent until the render stops disagreeing with the photographs — which is why the count runs to hundreds of thousands and nobody minds.',
    loading: 'loading the mesh…',
  },
  ui: {
    hardwareCta: 'Play the hardware chapters',
    duty: 'Duty cycle',
    brightness: 'Perceived brightness',
    frequency: 'Frequency',
    play: 'Play',
    pause: 'Pause',
    reset: 'Reset',
    subscribe: 'Subscribe',
    publish: 'Publish',
    matched: 'matched',
    dropped: 'not delivered',
    replicas: 'Replicas',
    traffic: 'Incoming traffic',
    latency: 'p99 latency',
    dropped_req: 'Dropped requests',
    cost: 'Cost',
    train: 'Train',
    epoch: 'Epoch',
    accuracy: 'Accuracy',
    wip: 'Interactive build in progress',
    wipNote: 'The layout is final; this panel is being wired up.',
    learned: 'What you just learned',
  },
};
