import type { Content } from './types';

export const es: Content = {
  meta: {
    title: 'Maykon Meneghel — el currículum jugable',
    description:
      'Ingeniero full-stack sénior con máster y posgrado en IA. Firmware, PCBs, CAD, MQTT, Kubernetes, Swift y Flutter — explicados con minijuegos que puedes jugar en la propia página.',
  },
  nav: { chapters: 'Capítulos', family: 'La familia', contact: 'Contacto', resume: 'Currículum' },
  hero: {
    kicker: 'Ingeniero Full-Stack Sénior · Máster en Bioingeniería · Especialista en IA',
    name: 'Maykon Meneghel',
    headline: 'Construyo la pila entera — de la pista de cobre a la red neuronal.',
    sub: 'La mayoría de los currículums cuentan lo que alguien sabe hacer. Este te deja probarlo. Cada capítulo de abajo es un minijuego que funciona: vas a enrutar una PCB, suscribirte a un tópico MQTT, escalar un clúster bajo carga y entrenar un modelo — sin salir de esta página.',
    cta: 'Empezar el recorrido',
    scrollHint: 'desliza',
    boot: [
      'meneghel.me boot v2.0',
      'detectando hardware .... ESP32 · PIC18F4550 · ATmega · ATtiny',
      'montando lenguajes ..... swift · dart · python · typescript · c/c++ · java',
      'levantando servicios ... docker · kubernetes · mqtt · rest',
      'cargando inteligencia .. pytorch · gan · pln',
      'listo.',
    ],
  },
  chapters: [
    {
      id: '01', codename: 'SILICIO', slug: 'silicon',
      title: 'Todo empieza en un solo pin',
      lede: 'Mucho antes de que exista una app, hay un microcontrolador decidiendo —millones de veces por segundo— si un cable está en alto o en bajo. Catorce firmwares me enseñaron que todo lo de arriba depende de acertar aquí.',
      panel: 'pwm_playground.c',
      takeaway: 'Acabas de atenuar un LED sin cambiar nunca su tensión. Eso es <b>PWM</b>: el pin solo está completamente encendido o completamente apagado — simplemente conmuta más rápido de lo que tu ojo puede seguir.',
      stack: ['C/C++', 'ESP32', 'PIC18F4550', 'ATmega', 'Timers y PWM'],
    },
    {
      id: '02', codename: 'COBRE', slug: 'copper',
      title: 'Luego necesita una placa',
      lede: 'Un esquemático es una promesa. La PCB es donde se cumple. Cada placa que he fabricado empezó exactamente con este rompecabezas: llevar cada señal a su sitio, en una superficie donde nada puede cruzarse.',
      panel: 'router.pcb',
      takeaway: 'Dos pistas no pueden cruzarse en la misma capa. Esa única restricción es la razón por la que las placas reales tienen 2, 4, a veces 12 capas apiladas.',
      stack: ['Altium', 'EAGLE', 'SMD y THT', 'Gerber', 'Diseño para manufactura'],
    },
    {
      id: '03', codename: 'ACERO', slug: 'steel',
      title: 'Y un cuerpo que sobreviva al campo',
      lede: 'Un sensor enterrado en tierra empapada durante dos años no se preocupa por lo elegante que sea tu firmware. Se preocupa por la carcasa. Por eso la modelo yo mismo: cada pieza, cada tolerancia, cada sello.',
      panel: 'soil_probe.sldasm',
      takeaway: 'El hardware es la única capa que no puedes parchear en remoto. Por eso el diseño mecánico ocurre <b>antes</b> de la primera línea de firmware, no después.',
      stack: ['SolidWorks', 'Modelado 3D', 'Tolerancias', 'Sellado IP', 'Impresión 3D'],
    },
    {
      id: '04', codename: 'SEÑAL', slug: 'signal',
      title: 'Ahora haz que mil de ellos hablen',
      lede: 'Un dispositivo es un proyecto. Mil dispositivos son una arquitectura. MQTT es cómo se hablan sin conocerse nunca — y los comodines de tópico son todo el truco.',
      panel: 'broker · mqtt://meneghel.me:8883',
      takeaway: '<b>+</b> coincide con exactamente un nivel. <b>#</b> coincide con todo lo que hay debajo. Esa única regla es cómo un solo broker reparte a miles de dispositivos sin que ninguno guarde la lista de los demás.',
      stack: ['MQTT', 'Mosquitto', 'AWS IoT Core', 'QoS 0/1/2', 'Pub/Sub'],
    },
    {
      id: '05', codename: 'SERVICIO', slug: 'service',
      title: 'Alguien tiene que recordarlo todo',
      lede: 'Los mensajes son efímeros; el negocio no. Detrás de cada dispositivo hay una API y una base de datos, y la diferencia entre un producto rápido y uno lento suele ser una decisión tomada aquí.',
      panel: 'psql · meneghel_db',
      takeaway: 'Sin índice, la base lee <b>todas las filas</b> para responderte. Con uno, salta directo al punto. Misma consulta, mismos datos, mismo servidor — mil veces más rápido.',
      stack: ['Node.js', 'Express', 'Restify', 'MongoDB', 'PostgreSQL', 'REST'],
    },
    {
      id: '06', codename: 'ENJAMBRE', slug: 'swarm',
      title: 'Una sola máquina nunca alcanza',
      lede: 'El tráfico no llega con educación. Llega de golpe, a las 3 de la mañana, el día del lanzamiento. Los contenedores y Kubernetes son cómo respondes a eso sin despertarte.',
      panel: 'kubectl · production',
      takeaway: 'No hiciste el código más rápido — hiciste <b>más copias de él</b>. El escalado horizontal cambia dinero por latencia, y un autoscaler hace ese cambio por ti, solo.',
      stack: ['Docker', 'Kubernetes', 'HPA', 'Balanceo de carga', 'CI/CD'],
    },
    {
      id: '07', codename: 'MENTE', slug: 'mind',
      title: 'Enseña a la máquina a decidir',
      lede: 'Aquí es donde mi posgrado en IA y mi máster en Bioingeniería dejan de ser líneas en un diploma. Un modelo no es magia: es una frontera, dibujada y redibujada hasta que los errores paran.',
      panel: 'perceptron.py — época 0',
      takeaway: 'El modelo nunca vio tu regla. Solo vio tus errores, y movió la línea un poco después de cada uno. Repite eso unos cientos de veces y tienes lo que llaman <b>aprendizaje</b>.',
      stack: ['PyTorch', 'GANs', 'PLN', 'Clasificación y regresión', 'Minería de datos'],
    },
    {
      id: '08', codename: 'CRISTAL', slug: 'glass',
      title: 'Por fin, algo que puedes tocar',
      lede: 'Doce apps iOS nativas, una destacada por Apple. El usuario nunca ve el broker, el clúster ni el modelo — ve una pantalla. Así que la pantalla tiene que valer todo eso.',
      panel: 'ContentView.swift / main.dart',
      takeaway: 'Misma pantalla, misma API, dos ecosistemas. Saber los dos no va de elegir un ganador — va de poder <b>elegir</b> cuando el producto lo exija.',
      stack: ['Swift', 'SwiftUI', 'Flutter', 'Dart', 'Kotlin', 'App Store'],
    },
    {
      id: '09', codename: 'SISTEMA', slug: 'system',
      title: 'Ahora míralo todo funcionando a la vez',
      lede: 'Nueve capítulos, un paquete. Dale a play y sigue una sola lectura de suelo, desde el sensor enterrado hasta el gráfico en la mano de alguien.',
      panel: 'trace · extremo a extremo',
      takeaway: 'Esta es la respuesta real a "¿a qué te dedicas?". No a una capa — a <b>las costuras entre ellas</b>, que es donde los productos se ganan o se pierden de verdad.',
      stack: ['Diseño de sistemas', 'Observabilidad', 'Sistemas distribuidos'],
    },
  ],
  record: {
    eyebrow: '10 · TRAYECTORIA',
    title: 'Las pruebas',
    lede: 'Nueve capítulos de demostración. Este es solo evidencia. Arrastra por los años y mira qué estaba corriendo a la vez — porque el titular honesto de esta línea de tiempo no es ningún empleo concreto, es lo poco que hubo uno solo.',
    lanes: {
      education: 'Formación',
      research: 'Investigación',
      industry: 'Industria',
      venture: 'Emprendimientos',
    },
    roles: {
      grad: 'Ing. de Control y Automatización',
      msc: 'Máster en Bioingeniería',
      academy: 'Posgrado de especialización, Desarrollo iOS',
      aiSpec: 'Especialización en Inteligencia Artificial Aplicada',
      pucLab: 'Becario, Laboratorio de Automatización y Sistemas',
      araucaria: 'Ingeniero de Software — investigación aplicada, IA y salud embebida',
      freelance: 'Desarrollador de Software, autónomo',
      residency: 'Trainee · Apple Residency',
      junior: 'Desarrollador Júnior · Proyecto Apple',
      techLead: 'Tech Lead · Apple Internship',
      fullstack: 'Desarrollador Full Stack · Proyecto Apple',
      senior: 'Desarrollador Sénior · Proyecto Apple',
      ghel: 'Technology Advisor · Proyecto Renault',
      holding: 'Consejero Administrativo — el holding familiar',
      tradx: 'COO y Cofundador',
    },
    scrubber: {
      simultaneous: '{n} funciones a la vez',
      one: '1 función',
      none: 'nada registrado todavía',
      today: 'hoy',
      drag: 'arrastra el año',
    },
    ventures: {
      title: 'Seis empresas',
      lede: 'Fundadas o cofundadas. Algunas crecieron, otras no — que es justamente el motivo de fundar seis.',
      founder: 'Fundador',
      coFounder: 'Cofundador',
      sectors: { fintech: 'fintech', agritech: 'agritech', smartHome: 'casa inteligente', proptech: 'proptech', edtech: 'edtech' },
    },
    publications: {
      title: 'Publicado y premiado',
      lede: 'Trabajo revisado por pares, casi todo en la costura entre ingeniería y salud.',
      items: {
        soilInstrument: 'Instrumento para la Medición de Factores y/o Elementos Naturales del Suelo',
        fesTool: 'A Tool to Select FES Parameters for chronic SCI',
        fallDetector: 'Indoors Wi-Fi Fall Detector Buckle for the Elderly',
        inSilicoFes: 'Aplicación, in silico, de estímulos eléctricos en un modelo neuromuscular compatible con lesión medular crónica',
        balanceModel: 'Modelado matemático del sistema de mantenimiento del equilibrio mediante identificación de sistemas',
        stockGan: 'Predicción de Series Financieras con Redes Generativas Adversarias',
      },
    },
    press: {
      title: 'En la prensa',
      items: {
        hubli: 'Hubli, creado en la Apple Developer Academy, destacado por Apple',
        neonWave: 'Neon Wave, juego de iOS cubierto por MacMagazine',
      },
    },
  },
  signal: {
    levels: ['sitio', 'área', 'dispositivo', 'medida'],
    anatomyLede: 'Un tópico es una ruta. Cada dispositivo de esta granja publica en una ruta formada por los mismos cuatro niveles — así que una suscripción es, en el fondo, una pregunta sobre qué niveles te importan.',
    legendPlus: 'coincide con exactamente un nivel, sea cual sea su contenido',
    legendHash: 'coincide con todo lo que venga debajo, y tiene que ser el último nivel',
    yourToken: 'escribiste',
    noToken: '—',
    subLabel: 'Tu suscripción',
    placeholder: 'farm/greenhouse/#',
    broker: 'Broker — todo lo que se está publicando',
    inbox: 'Tu bandeja — lo que te llegó',
    delivered: 'entregados',
    dropped: 'no entregados',
    missionsTitle: 'Tres suscripciones que acertar',
    missionsLede: 'Vale cualquier filtro que seleccione exactamente los tópicos correctos. Cada misión tiene más de una respuesta válida.',
    missions: [
      { id: 'greenhouse', goal: 'Todo lo que publica el invernadero — y nada más.' },
      { id: 'temps',      goal: 'Cada lectura de temperatura, venga de donde venga.' },
      { id: 'moisture',   goal: 'Cada lectura de humedad de la granja, pero no la de casa.' },
    ],
    solved: 'resuelta',
    invalidHash: 'el # tiene que ser el último nivel, solo',
    invalidPlus: 'el + tiene que ocupar un nivel entero, solo',
    invalidEmpty: 'un nivel del tópico no puede quedar vacío',
    emptyInbox: 'nada ha coincidido todavía',
    allSolved: 'Las tres. Ya entiendes los filtros de tópico MQTT mejor que mucha gente que los usa a diario.',
  },
  swarm: {
    lede: 'El tráfico de este servicio se dispara cada pocos segundos, como en un día de lanzamiento. Añade réplicas y la latencia baja; añade demasiadas y pagas por máquinas ociosas. Después déjaselo al autoscaler y mira dónde sigue perdiendo.',
    traffic: 'Entrada',
    replicas: 'Réplicas',
    latency: 'Latencia p99',
    dropped: 'Peticiones perdidas',
    cost: 'Coste',
    saturation: 'Saturación',
    auto: 'Autoscaler',
    autoHint: 'Apuntando al 60% de saturación. Un pod nuevo tarda unos 4s en estar listo — por eso siguen cayendo peticiones en la subida.',
    manualHint: 'Estás escalando a mano. El pico llega estés listo o no.',
    ready: 'listos',
    starting: 'arrancando',
    reset: 'Poner a cero',
    spike: 'pico',
    healthy: 'saludable',
    strained: 'bajo presión',
    failing: 'perdiendo tráfico',
    wasteful: 'sobredimensionado',
  },
  mind: {
    lede: 'Cada punto es un motor que funcionaba a cierta temperatura y cierta vibración, y que después resultó estar bien o resultó estar roto. Nadie le ha dicho la regla al modelo. Pulsa entrenar y míralo buscar la línea.',
    axisX: 'temperatura →',
    axisY: 'vibración →',
    healthy: 'sano',
    failing: 'en fallo',
    adding: 'al hacer clic añades',
    train: 'Entrenar',
    pause: 'Pausar',
    clear: 'Limpiar',
    presetSeparable: 'Separable',
    presetXor: 'XOR',
    steps: 'Correcciones',
    accuracy: 'Precisión',
    wrong: 'Aún erróneos',
    weights: 'Pesos',
    hintPlace: 'Haz clic donde quieras para añadir una lectura. Cambia de clase para colocar del otro tipo.',
    hintConverged: 'Se detuvo. No porque se lo dijeran — porque ya no quedaba nada que fallara.',
    hintStuck: 'Nunca se va a asentar. Ninguna recta puede separar esta disposición, y un perceptrón es exactamente una recta. Apilarlos es como se consigue una curva — y esa es justamente la razón de que existan las redes profundas.',
  },
  service: {
    lede: 'Una tabla de lecturas de sensor, 240.000 filas. Elige una consulta, decide qué columnas llevan índice, y ejecútala. La franja de abajo es la tabla; fíjate en cuánta tiene que tocar la base de datos.',
    table: 'readings · 240.000 filas',
    indexes: 'CREATE INDEX ON',
    query: 'Consulta',
    run: 'Ejecutar',
    running: 'Ejecutando…',
    rows: 'Filas leídas',
    time: 'Tiempo de consulta',
    speedup: 'vs recorrido completo',
    writes: 'Coste de escritura',
    queryLabels: {
      point: 'una fila por id',
      selective: 'un sensor · 5%',
      broad: 'casi toda la tabla · 60%',
    },
    hints: {
      'no-index': 'No hay índice en esa columna, así que la base no tiene opción. Abre la tabla por la primera fila y lee las 240.000 para asegurarse de no dejarse ninguna.',
      'index-used': 'El índice fue directo — dieciocho pasos árbol abajo, y luego las filas. Misma consulta, mismos datos, misma máquina.',
      'not-selective': 'El índice existe, y el planificador se negó a usarlo. Esta consulta quiere el 60% de la tabla, y andar saltando por un índice para eso cuesta más que leerlo todo en orden. Crearlo no te dio nada aquí — y aun así ralentiza cada escritura.',
    },
    treeLabel: 'índice · árbol B',
    heapLabel: 'tabla',
  },
  copper: {
    lede: 'Esto no es una ilustración. Es AGROM.brd, la placa que enruté en 2017 para la sonda de suelo — 70 mm de diámetro, dos capas de cobre, 54 componentes — leída directamente del archivo de EAGLE y dibujada aquí. Elige una net y síguela.',
    layersLabel: 'Capas',
    view2d: 'Plana',
    view3d: 'Apilada',
    viewSolid: 'Montada',
    flip: 'Dar la vuelta',
    componentsWord: 'componentes',
    underneathWord: 'debajo',
    hintSolid: 'La misma placa con sus componentes, construida a partir del archivo IDF que EAGLE exportó al CAD mecánico en 2017 — cada footprint, posición, rotación y cara sale de ahí. Diecinueve de las 59 piezas van montadas debajo. Dale la vuelta y las encuentras.',
    explode: 'Separación',
    spin: 'arrastra para girar',
    hintStack: 'Es la misma placa, vista de canto. Dos láminas de cobre con 1,6 mm de fibra de vidrio entre ellas, y 34 postes metalizados cosiéndolas. Cada poste amarillo es una vía — la única forma de que una señal pase de una cara a la otra.',
    both: 'Ambas',
    topOnly: 'Solo la de arriba',
    bottomOnly: 'Solo la de abajo',
    netsLabel: 'Nets',
    allNets: 'Todas',
    segments: 'Segmentos',
    crossings: 'Cambios de capa',
    length: 'Longitud de cobre',
    legendTop: 'cobre superior',
    legendBottom: 'cobre inferior',
    legendVia: 'vía',
    hintIdle: 'El rojo corre por la cara superior, el azul por la inferior. Cada anillo amarillo es una vía: un agujero metalizado por donde la pista baja al otro lado.',
    hintCrossings: 'La net {net} cambia de capa {n} veces. Cambia a una sola capa y mírala partirse en trozos — esos huecos son donde va por la cara que acabas de ocultar.',
    hintFlat: 'La net {net} nunca sale de su capa. Nada se le puso delante, así que nunca tuvo que bajar.',
    hintOneLayer: 'Media placa ha desaparecido. Todo lo que falta va por la otra cara — y lo único que lo hace posible es que ambas caras están cosidas por vías.',
  },
  steel: {
    lede: 'Siete piezas que modelé en SolidWorks e imprimí, cargadas aquí desde los mismos STL que fueron a la impresora. Dale la vuelta a una.',
    partsLabel: 'Pieza',
    loading: 'cargando mallas…',
    spin: 'arrastra para girar',
    autoSpin: 'Girar',
    triangles: 'Triángulos',
    sourceTris: 'En el STL',
    span: 'Dimensión mayor',
    processTitle: 'La prueba está en la estructura de carpetas',
    processLede: 'El proyecto mecánico no está archivado por pieza. Está archivado por cómo se fabrica cada una — que es la diferencia entre modelar algo y especificarlo.',
    processes: [
      { label: 'Torno y mecanizado', count: 11, note: 'cada una con plano acotado' },
      { label: 'Corte láser', count: 5, note: 'acrílico plano, dibujado y tolerado' },
      { label: 'Impresión 3D', count: 7, note: 'las piezas que giras aquí' },
      { label: 'Compra', count: 14, note: 'sensores, celdas, conectores' },
      { label: 'Montaje de cables', count: 1, note: 'un mazo de cuatro vías' },
    ],
    parts: {
      'barra-central': { kind: 'columna central', blurb: 'La espina alrededor de la cual se monta todo el cabezal.' },
      'suporte-bateria': { kind: 'cuna de la batería', blurb: 'Sujeta la celda de plomo dentro del mástil.' },
      'tampa-suporte-bateria': { kind: 'tapa de la cuna', blurb: 'Cierra la cuna frente a la intemperie.' },
      'suporte-gas': { kind: 'soporte de sensores de gas', blurb: 'Lleva los sensores MQ-2, MQ-7 y MQ-8.' },
      'tampa-gas': { kind: 'tapa de sensores de gas', blurb: 'Tapa ventilada, para que los sensores respiren.' },
      'tampa-os': { kind: 'tapa del cabezal de suelo', blurb: 'Tapa superior del cabezal de solo suelo.' },
      'tampa-ws': { kind: 'tapa de la estación', blurb: 'Tapa superior del cabezal de estación meteorológica.' },
    },
    drawings: '16 planos acotados',
    hint: 'Estas mallas están decimadas — unos mil triángulos cada una, desde hasta quince mil — porque una página web no debe cargar un archivo de impresión. Las siluetas son las reales.',
  },
  ui: {
    duty: 'Ciclo de trabajo',
    brightness: 'Brillo percibido',
    frequency: 'Frecuencia',
    play: 'Ejecutar',
    pause: 'Pausar',
    reset: 'Reiniciar',
    subscribe: 'Suscribir',
    publish: 'Publicar',
    matched: 'entregado',
    dropped: 'no entregado',
    replicas: 'Réplicas',
    traffic: 'Tráfico entrante',
    latency: 'Latencia p99',
    dropped_req: 'Peticiones perdidas',
    cost: 'Coste',
    train: 'Entrenar',
    epoch: 'Época',
    accuracy: 'Precisión',
    wip: 'Interactividad en construcción',
    wipNote: 'El layout es el definitivo; este panel se está cableando.',
    learned: 'Lo que acabas de aprender',
  },
};
