import type { Content } from './types';

export const es: Content = {
  meta: {
    title: 'Maykon Meneghel — el currículum jugable',
    description:
      'Ingeniero full-stack sénior con máster y posgrado en IA. Firmware, PCBs, CAD, MQTT, Kubernetes, Swift y Flutter — explicados con minijuegos que puedes jugar en la propia página.',
  },
  nav: { chapters: 'Capítulos', family: 'La familia', contact: 'Contacto', resume: 'Currículum' },
  hero: {
    kicker: 'Ingeniero Full-Stack Sénior · Agro y mercados financieros',
    name: 'Maykon Meneghel',
    headline: 'Construyo la pila entera — de la pista de cobre a la red neuronal.',
    sub: 'La mayoría de los currículums cuentan lo que alguien sabe hacer. Este te deja probarlo. Cada capítulo de abajo es un minijuego que funciona: vas a enrutar una PCB, suscribirte a un tópico MQTT, escalar un clúster bajo carga y entrenar un modelo — sin salir de esta página.',
    proof: [
      'Doce apps iOS nativas · una destacada por Apple',
      'COO y cofundador · Tradx',
      'Máster en Bioingeniería · posgrado en IA aplicada',
      'Clean Architecture para SwiftUI · 30★ en GitHub',
    ],
    links: [
      { label: 'LinkedIn', href: 'https://www.linkedin.com/in/maykonmeneghel/' },
      { label: 'GitHub', href: 'https://github.com/maykonmeneghel' },
    ],
    cv: 'Descargar CV (PDF)',
    cta: 'Empezar el recorrido',
    scrollHint: 'desliza',
    boot: [
      'meneghel.me boot v2.0',
      'detectando hardware .... ESP32 · PIC18F4550 · ATmega · ATtiny',
      'montando lenguajes ..... swift · dart · python · typescript · c/c++ · java',
      'levantando servicios ... docker · kubernetes · mqtt · rest',
      'cargando inteligencia .. pytorch · gan · pln',
      'listo.',
    ],
  },
  acts: [
    {
      before: 'silicon',
      label: 'Acto uno',
      title: 'Una máquina, desmontada',
      lede: 'Los siguientes ocho capítulos son un único producto: una sonda de suelo que diseñé, construí y clavé en la tierra entre 2016 y 2019. Está aquí porque es lo único que tengo de punta a punta — la placa, la carcasa, el protocolo, la base de datos, el clúster y la app son todos míos — así que se puede subir la pila entera, de un pin a una pantalla, sin cambiar nunca de tema.',
    },
    {
      before: 'mind',
      label: 'Acto dos',
      title: 'Y en qué acabó',
      lede: 'De 2019 en adelante. La Apple Developer Academy movió mi centro de gravedad de las placas a los productos, y la ingeniería de debajo siguió siendo exactamente la misma. Estos tres capítulos son el trabajo desde entonces — incluidas las dos cosas que estoy haciendo ahora mismo.',
    },
  ],
  chapters: [

    {
      id: '01', codename: 'SILICIO', slug: 'silicon',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Todo empieza en un solo pin',
      lede: 'Mucho antes de que exista una app, hay un microcontrolador decidiendo —millones de veces por segundo— si un cable está en alto o en bajo. Catorce firmwares me enseñaron que todo lo de arriba depende de acertar aquí.',
      panel: 'pwm_playground.c',
      takeaway: 'Acabas de atenuar un LED sin cambiar nunca su tensión. Eso es <b>PWM</b>: el pin solo está completamente encendido o completamente apagado — simplemente conmuta más rápido de lo que tu ojo puede seguir.',
      stack: ['C/C++', 'ESP32', 'PIC18F4550', 'ATmega', 'Timers y PWM'],
    },
    {
      id: '02', codename: 'COBRE', slug: 'copper',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Luego necesita una placa',
      lede: 'Un esquemático es una promesa. La PCB es donde se cumple. Cada placa que he fabricado empezó exactamente con este rompecabezas: llevar cada señal a su sitio, en una superficie donde nada puede cruzarse.',
      panel: 'router.pcb',
      takeaway: 'Dos pistas no pueden cruzarse en la misma capa. Esa única restricción es la razón por la que las placas reales tienen 2, 4, a veces 12 capas apiladas.',
      stack: ['Altium', 'EAGLE', 'SMD y THT', 'Gerber', 'Diseño para manufactura'],
    },
    {
      id: '03', codename: 'ACERO', slug: 'steel',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Y un cuerpo que sobreviva al campo',
      lede: 'Un sensor enterrado en tierra empapada durante dos años no se preocupa por lo elegante que sea tu firmware. Se preocupa por la carcasa. Por eso la modelo yo mismo: cada pieza, cada tolerancia, cada sello.',
      panel: 'soil_probe.sldasm',
      takeaway: 'El hardware es la única capa que no puedes parchear en remoto. Por eso el diseño mecánico ocurre <b>antes</b> de la primera línea de firmware, no después.',
      stack: ['SolidWorks', 'Modelado 3D', 'Tolerancias', 'Sellado IP', 'Impresión 3D'],
    },
    {
      id: '04', codename: 'SEÑAL', slug: 'signal',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Ahora haz que mil de ellos hablen',
      lede: 'Un dispositivo es un proyecto. Mil dispositivos son una arquitectura. MQTT es cómo se hablan sin conocerse nunca — y los comodines de tópico son todo el truco.',
      panel: 'broker · mqtt://meneghel.me:8883',
      takeaway: '<b>+</b> coincide con exactamente un nivel. <b>#</b> coincide con todo lo que hay debajo. Esa única regla es cómo un solo broker reparte a miles de dispositivos sin que ninguno guarde la lista de los demás.',
      stack: ['MQTT', 'Mosquitto', 'AWS IoT Core', 'QoS 0/1/2', 'Pub/Sub'],
    },
    {
      id: '05', codename: 'SERVICIO', slug: 'service',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Alguien tiene que recordarlo todo',
      lede: 'Los mensajes son efímeros; el negocio no. Detrás de cada dispositivo hay una API y una base de datos, y la diferencia entre un producto rápido y uno lento suele ser una decisión tomada aquí.',
      panel: 'psql · meneghel_db',
      takeaway: 'Sin índice, la base lee <b>todas las filas</b> para responderte. Con uno, salta directo al punto. Misma consulta, mismos datos, mismo servidor — mil veces más rápido.',
      stack: ['Node.js', 'Express', 'Restify', 'MongoDB', 'PostgreSQL', 'REST'],
    },
    {
      id: '06', codename: 'ENJAMBRE', slug: 'swarm',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Una sola máquina nunca alcanza',
      lede: 'El tráfico no llega con educación. Llega de golpe, a las 3 de la mañana, el día del lanzamiento. Los contenedores y Kubernetes son cómo respondes a eso sin despertarte.',
      panel: 'kubectl · production',
      takeaway: 'No hiciste el código más rápido — hiciste <b>más copias de él</b>. El escalado horizontal cambia dinero por latencia, y un autoscaler hace ese cambio por ti, solo.',
      stack: ['Docker', 'Kubernetes', 'HPA', 'Balanceo de carga', 'CI/CD'],
    },
    {
      id: '07', codename: 'CRISTAL', slug: 'glass',
      era: 'Swift y Flutter · 2019 → hoy',
      title: 'Por fin, algo que puedes tocar',
      lede: 'Doce apps iOS nativas, una destacada por Apple. El usuario nunca ve el broker, el clúster ni el modelo — ve una pantalla. Así que la pantalla tiene que valer todo eso.',
      panel: 'ContentView.swift / main.dart',
      takeaway: 'Misma pantalla, misma API, dos ecosistemas. Saber los dos no va de elegir un ganador — va de poder <b>elegir</b> cuando el producto lo exija.',
      stack: ['Swift', 'SwiftUI', 'Flutter', 'Dart', 'Kotlin', 'App Store'],
    },
    {
      id: '08', codename: 'SISTEMA', slug: 'system',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Ahora míralo todo funcionando a la vez',
      lede: 'Siete capítulos, un paquete. Dale a play y sigue una sola lectura de suelo, desde el sensor enterrado hasta el gráfico en la mano de alguien.',
      panel: 'trace · extremo a extremo',
      takeaway: 'Esta es la respuesta real a "¿a qué te dedicas?". No a una capa — a <b>las costuras entre ellas</b>, que es donde los productos se ganan o se pierden de verdad.',
      stack: ['Diseño de sistemas', 'Observabilidad', 'Sistemas distribuidos'],
    },
    {
      id: '09', codename: 'MENTE', slug: 'mind',
      era: 'StockGAN · 2021',
      title: 'Enseña a la máquina a adivinar qué viene después',
      lede: 'En 2021 construí desde cero una red generativa adversaria para series temporales — el trabajo en el que mi posgrado en IA y mi máster en Bioingeniería dejan de ser líneas en un diploma — dos redes, una intentando inventar la siguiente lectura y otra intentando pillarla mintiendo. La entrené con datos financieros. Aquí corre sobre la sonda de suelo de los capítulos de arriba, sin cambiar nada, porque una serie temporal no sabe qué mide.',
      panel: 'gan_model.py — train_step()',
      takeaway: 'Dos modelos, una función de pérdida y una perilla entre ellos. Exígele al pronosticador que quede cerca y responde con el promedio de todo, que es seguro e inútil. Exígele que sea creíble y responde con algo que se mueve como el sensor y no sabe nada. <b>Cada modelo que entrego es ese intercambio hecho a propósito</b>, escrito y medido.',
      stack: ['TensorFlow / Keras', 'GANs', 'LSTM', 'Series temporales', 'Selección de features con PCA y XGBoost'],
    },
    {
      id: '10', codename: 'FLUJO', slug: 'flow',
      era: 'Tradx · 2022 → hoy',
      title: 'Y entonces construí la herramienta',
      lede: 'Un pronóstico tiene que vivir en algún sitio. El mío vive en Tradx — la empresa que cofundé en 2022 y dirijo como COO, una mesa donde una estrategia es un grafo que cableas, no un código que escribes.',
      panel: 'tradx · grafo de estrategia',
      takeaway: 'Un backtest es una <b>hipótesis</b>, no un resultado. Cualquiera ajusta una curva hasta que queda bonita con los datos que ya tiene; todo el oficio está en saber cuánto vale ese número con los datos que no tiene.',
      stack: ['Node.js', 'NestJS', 'Flutter', 'MongoDB', 'Redis + BullMQ', 'Motor de backtest', 'Paper trading'],
    },
    {
      id: '11', codename: 'LIBRO', slug: 'ledger',
      era: 'Tradx · 2022 → hoy',
      title: 'Una orden no es una operación',
      lede: 'El capítulo anterior produjo una señal. Este es lo que le pasa. Una estrategia emite órdenes; un motor decide cuáles se convierten en operaciones, y la distancia entre esos dos números es donde una mesa de trading se construye o se pierde.',
      panel: 'tradx · motor de ejecución',
      takeaway: 'El motor rechazó treinta y ocho órdenes y reportó un problema de fondos. No lo tenía. <b>Vender contra una posición larga libera poder de compra</b> — un motor que revisa la orden en vez de la exposición resultante bloqueará justo las operaciones que reducen riesgo y lo llamará prudencia.',
      stack: ['NestJS', 'Ciclo de vida de la orden', 'Netting de posición', 'Idempotencia', 'Redis + BullMQ', 'Paper trading'],
    },
    {
      id: '12', codename: 'CAMPO', slug: 'field',
      era: 'Gaussian splatting · hoy',
      title: 'Y ahora el objeto está hecho de luz',
      lede: 'En esto paso los días ahora: Gaussian Splatting. Una escena deja de ser una superficie que alguien modeló y pasa a ser una nube de gaussianas orientadas, ajustadas por descenso de gradiente hasta que sus renders coinciden con las fotografías. Las reconstrucciones de verdad empiezan con una cámara recorriendo una sala. La demo de abajo a propósito no lo hace — usa una pieza que ya conociste en el capítulo 03, porque la única forma de ver qué cambia el método es ver el mismo objeto construido de las dos formas.',
      panel: 'gaussian splatting · viewer',
      takeaway: 'Una malla dice dónde están las <b>superficies</b>, y un ingeniero dibujó cada una. Un campo de splats dice dónde está la <b>luz</b>, y nadie dibujó nada — se ajustó hasta que el render dejó de contradecir a la fotografía.',
      stack: ['Gaussian Splatting', '3DGS', 'PyTorch', 'CUDA', 'Fotogrametría', 'Campos de radiancia'],
    },
  ],
  record: {
    eyebrow: '13 · TRAYECTORIA',
    title: 'Las pruebas',
    lede: 'Nueve capítulos de demostración. Este es solo evidencia. Arrastra por los años y mira qué estaba corriendo a la vez — porque el titular honesto de esta línea de tiempo no es ningún empleo concreto, es lo poco que hubo uno solo.',
    lanes: {
      education: 'Formación',
      research: 'Investigación',
      industry: 'Industria',
      venture: 'Emprendimientos',
    },
    roles: {
      grad: 'Ing. de Control y Automatización',
      msc: 'Máster en Bioingeniería',
      academy: 'Posgrado de especialización, Desarrollo iOS',
      aiSpec: 'Especialización en Inteligencia Artificial Aplicada',
      pucLab: 'Becario, Laboratorio de Automatización y Sistemas',
      araucaria: 'Ingeniero de Software — investigación aplicada, IA y salud embebida',
      freelance: 'Desarrollador de Software, autónomo',
      residency: 'Trainee · Apple Residency',
      junior: 'Desarrollador Júnior · Proyecto Apple',
      techLead: 'Tech Lead · Apple Internship',
      fullstack: 'Desarrollador Full Stack · Proyecto Apple',
      senior: 'Desarrollador Sénior · Proyecto Apple',
      ghel: 'Technology Advisor · Proyecto Renault',
      holding: 'Consejero Administrativo — el holding familiar',
      tradx: 'COO y Cofundador',
    },
    scrubber: {
      simultaneous: '{n} funciones a la vez',
      one: '1 función',
      none: 'nada registrado todavía',
      today: 'hoy',
      drag: 'arrastra el año',
    },
    ventures: {
      title: 'Seis empresas',
      lede: 'Fundadas o cofundadas. Algunas crecieron, otras no — que es justamente el motivo de fundar seis.',
      founder: 'Fundador',
      coFounder: 'Cofundador',
      sectors: { fintech: 'fintech', agritech: 'agritech', smartHome: 'casa inteligente', proptech: 'proptech', edtech: 'edtech' },
    },
    publications: {
      title: 'Publicado y premiado',
      lede: 'Trabajo revisado por pares, casi todo en la costura entre ingeniería y salud.',
      read: 'leer el artículo',
      code: 'código',
      items: {
        soilInstrument: 'Instrumento para la Medición de Factores y/o Elementos Naturales del Suelo',
        fesTool: 'A Tool to Select FES Parameters for chronic SCI',
        fallDetector: 'Indoors Wi-Fi Fall Detector Buckle for the Elderly',
        inSilicoFes: 'Aplicación, in silico, de estímulos eléctricos en un modelo neuromuscular compatible con lesión medular crónica',
        balanceModel: 'Modelado matemático del sistema de mantenimiento del equilibrio mediante identificación de sistemas',
        stockGan: 'Predicción de Series Financieras con Redes Generativas Adversarias',
      },
    },
    press: {
      title: 'En la prensa',
      items: {
        hubli: 'Hubli, creado en la Apple Developer Academy, destacado por Apple',
        neonWave: 'Neon Wave, juego de iOS cubierto por MacMagazine',
      },
    },
    closing: {
      line: 'Full stack sénior, desde el punto de soldadura hasta el modelo en producción — en el agro y en los mercados financieros.',
      note: 'La placa, el firmware, el broker, la base de datos, el clúster, el modelo y la pantalla del móvil. Todavía no he conocido a la otra persona que hace los dos extremos de los dos.',
    },
    contact: {
      title: 'Hablemos',
      lede: 'Si algo de esto tiene la forma de un problema que tienes, quiero saberlo. Correo o LinkedIn, lo que prefieras — el CV es un PDF de dos páginas y el código está en GitHub.',
      linkedin: 'Escríbeme por LinkedIn',
      github: 'Ver mi código',
      email: 'Escríbeme un correo',
      cv: 'Descargar mi CV',
    },
    skills: {
      title: 'Con qué trabajo',
      lede: 'Todo lo de abajo está acreditado por algún capítulo de esta página o está en un repositorio público. Nada aquí es aspiracional.',
      groups: {
        languages: 'Lenguajes',
        backend: 'Backend y APIs',
        data: 'Datos',
        cloud: 'Cloud y DevOps',
        frontend: 'Móvil y front-end',
        ai: 'IA y 3D',
        embedded: 'Embebidos y hardware',
        ways: 'Forma de trabajar',
      },
    },
  },
  signal: {
    levels: ['sitio', 'área', 'dispositivo', 'medida'],
    anatomyLede: 'Un tópico es una ruta. Cada dispositivo de esta granja publica en una ruta formada por los mismos cuatro niveles — así que una suscripción es, en el fondo, una pregunta sobre qué niveles te importan.',
    legendPlus: 'coincide con exactamente un nivel, sea cual sea su contenido',
    legendHash: 'coincide con todo lo que venga debajo, y tiene que ser el último nivel',
    yourToken: 'escribiste',
    noToken: '—',
    subLabel: 'Tu suscripción',
    placeholder: 'farm/greenhouse/#',
    broker: 'Broker — todo lo que se está publicando',
    inbox: 'Tu bandeja — lo que te llegó',
    delivered: 'entregados',
    dropped: 'no entregados',
    missionsTitle: 'Tres suscripciones que acertar',
    missionsLede: 'Vale cualquier filtro que seleccione exactamente los tópicos correctos. Cada misión tiene más de una respuesta válida.',
    missions: [
      { id: 'greenhouse', goal: 'Todo lo que publica el invernadero — y nada más.' },
      { id: 'temps',      goal: 'Cada lectura de temperatura, venga de donde venga.' },
      { id: 'moisture',   goal: 'Cada lectura de humedad de la granja, pero no la de casa.' },
    ],
    solved: 'resuelta',
    invalidHash: 'el # tiene que ser el último nivel, solo',
    invalidPlus: 'el + tiene que ocupar un nivel entero, solo',
    invalidEmpty: 'un nivel del tópico no puede quedar vacío',
    emptyInbox: 'nada ha coincidido todavía',
    allSolved: 'Las tres. Ya entiendes los filtros de tópico MQTT mejor que mucha gente que los usa a diario.',
  },
  swarm: {
    lede: 'El tráfico de este servicio se dispara cada pocos segundos, como en un día de lanzamiento. Añade réplicas y la latencia baja; añade demasiadas y pagas por máquinas ociosas. Después déjaselo al autoscaler y mira dónde sigue perdiendo.',
    traffic: 'Entrada',
    replicas: 'Réplicas',
    latency: 'Latencia p99',
    dropped: 'Peticiones perdidas',
    cost: 'Coste',
    saturation: 'Saturación',
    auto: 'Autoscaler',
    autoHint: 'Apuntando al 60% de saturación. Un pod nuevo tarda unos 4s en estar listo — por eso siguen cayendo peticiones en la subida.',
    manualHint: 'Estás escalando a mano. El pico llega estés listo o no.',
    ready: 'listos',
    starting: 'arrancando',
    reset: 'Poner a cero',
    spike: 'pico',
    healthy: 'saludable',
    strained: 'bajo presión',
    failing: 'perdiendo tráfico',
    wasteful: 'sobredimensionado',
  },
  mind: {
    lede: 'En 2021 escribí una GAN que pronostica el siguiente valor de una serie temporal — generador, discriminador y bucle de entrenamiento desde cero. La entrené con treinta años de barras diarias, porque ahí era donde había histórico limpio y gratis, pero la red lee log-retornos y no tiene ni idea de qué miden los números. Así que aquí está corriendo sobre la sonda de suelo de los capítulos de arriba. Lo que vale la pena mostrar es esto: el discriminador nunca juzga una lectura prevista por sí sola. La lectura se pega a las nueve reales que vinieron antes, y la red tiene que decir si la ventana entera salió del sensor. Ese es el juego. Tú eres el discriminador.',
    paper: 'StockGAN · LSTM(128) · ventana de 10 · entrenada con 30 años de barras diarias, corriendo aquí sobre soil-1',
    reading: 'soil-1 · invernadero · % de humedad',
    question: 'Una de estas dos ventanas termina con una lectura que la sonda tomó de verdad. La otra termina con una que inventó el generador. ¿Cuál es cuál?',
    slotA: 'Ventana A',
    slotB: 'Ventana B',
    pick: 'Elegir',
    real: 'REAL',
    generated: 'GENERADA',
    criticSays: 'el discriminador le dio',
    next: 'Siguiente ventana',
    reset: 'Empezar de nuevo',
    rounds: 'Rondas',
    you: 'Tú',
    network: 'El discriminador',
    fooled: 'Engañó al crítico',
    lambdaLabel: 'λ — cuánto de la nota del generador viene de engañar al crítico en vez de acertar el número',
    lambdaHis: 'lo que publiqué',
    meterTruth: 'Cerca de la verdad',
    meterReal: 'Se mueve como el sensor',
    arch: 'Lo que hay de verdad en el archivo',
    archGen: 'generador      LSTM(128, stateful) → Dropout(0.3) → Dense(n_features)',
    archDisc: 'discriminador  LSTM(128, stateful) → Dropout(0.1) → Dense(1, sigmoid)',
    archNote: 'RMSprop con decaimiento polinómico de 2.5e-4 a 1e-4 a lo largo de mil pasos. Entropía cruzada con label smoothing en 0.2, para que al discriminador nunca se le permita estar completamente seguro de nada. Objetivo real y objetivo generado multiplicados por ruido con σ = 0.25 durante el entrenamiento, para que no gane notando qué números están demasiado limpios. Doce indicadores — MACD, EMA, RSI, Bollinger, ROC, volatilidad — reducidos por PCA y XGBoost antes de que la red viera nada; en una sonda de suelo esos mismos doce se convierten en medias móviles y tasa de variación de la humedad, y ese es justamente el punto: la arquitectura cambió de dominio y el pipeline de features apenas parpadeó. Las funciones de pérdida de esta página son portes de las reales, constantes incluidas; el generador de aquí es un sustituto que reproduce el dilema sin meter 128 unidades LSTM en tu navegador.',
    hintStart: 'Elige una. Nueve lecturas reales, y una décima que es la sonda o mi generador.',
    hintRight: 'Correcto.',
    hintWrong: 'Incorrecto — y mira las dos notas de abajo. Es el mismo juicio que hace la red, sobre la misma ventana.',
    hintLow: 'Aquí abajo el generador se califica casi solo por error cuadrático, así que responde con la media condicional: la apuesta más segura posible. Es lo más preciso que puede decir y es obviamente falso — el paso es un tercio del tamaño de uno real. Todo pronosticador entrenado solo con MSE tiene este problema, y la mayoría nunca se entera.',
    hintHigh: 'Aquí arriba se califica solo por engañar al crítico. Las lecturas por fin se mueven como se mueve el sensor, y los números están más lejos de la próxima hora que nunca. Parece correcto. No lo es.',
    hintHis: '0.6 es lo que publiqué: inclinándose hacia el crítico, y pagando unas dos décimas de punto de error por ello. Ningún ajuste gana en los dos medidores — que es exactamente por qué ese número es una decisión y no un valor por defecto.',
    verdict: 'Estás en {you} en estas rondas. La red está en {net} sobre las mismas ventanas.',
  },
  ledger: {
    lede: 'Una cuenta, un instrumento, veinte lotes por clic. Compra y vende a mano y mira qué le hace cada orden a los fondos disponibles — luego cambia la comprobación de fondos y hazlo otra vez.',
    modeLabel: 'Comprobación de fondos',
    modeGross: 'Nocional de la orden',
    modeNet: 'Exposición neta',
    price: 'Precio',
    position: 'Posición',
    equityLabel: 'Patrimonio',
    lockedLabel: 'Bloqueado',
    availableLabel: 'Disponible',
    flat: 'plana',
    buy: 'Comprar 20',
    sell: 'Vender 20',
    reset: 'Reiniciar',
    replay: 'Repetir la sesión',
    replayTitle: 'Las mismas cuarenta órdenes, de las dos formas',
    grossLabel: 'Comprobado contra la orden',
    netLabel: 'Comprobado contra la exposición',
    hintStart: 'Empieza con dos compras y luego intenta vender para salir. Mira qué le hace la venta a los fondos disponibles en cada comprobación.',
    hintAccepted: 'Ejecutada — {side} {qty} a {price}.',
    hintFunds: 'Rechazada. El motor quiere {need} bloqueados y la cuenta vale {have} — incluso cuando la orden dejaría la posición más pequeña.',
    hintReplay: '{filled} de {orders} órdenes ejecutadas\n{trips} idas y vueltas\n{pnl} realizado',
  },
  service: {
    lede: 'Una tabla de lecturas de sensor, 240.000 filas. Elige una consulta, decide qué columnas llevan índice, y ejecútala. La franja de abajo es la tabla; fíjate en cuánta tiene que tocar la base de datos.',
    table: 'readings · 240.000 filas',
    indexes: 'CREATE INDEX ON',
    query: 'Consulta',
    run: 'Ejecutar',
    running: 'Ejecutando…',
    rows: 'Filas leídas',
    time: 'Tiempo de consulta',
    speedup: 'vs recorrido completo',
    writes: 'Coste de escritura',
    queryLabels: {
      point: 'una fila por id',
      selective: 'un sensor · 5%',
      broad: 'casi toda la tabla · 60%',
    },
    hints: {
      'no-index': 'No hay índice en esa columna, así que la base no tiene opción. Abre la tabla por la primera fila y lee las 240.000 para asegurarse de no dejarse ninguna.',
      'index-used': 'El índice fue directo — dieciocho pasos árbol abajo, y luego las filas. Misma consulta, mismos datos, misma máquina.',
      'not-selective': 'El índice existe, y el planificador se negó a usarlo. Esta consulta quiere el 60% de la tabla, y andar saltando por un índice para eso cuesta más que leerlo todo en orden. Crearlo no te dio nada aquí — y aun así ralentiza cada escritura.',
    },
    treeLabel: 'índice · árbol B',
    heapLabel: 'tabla',
  },
  copper: {
    lede: 'Esto no es una ilustración. Es AGROM.brd, la placa que enruté en 2017 para la sonda de suelo — 70 mm de diámetro, dos capas de cobre, 54 componentes — leída directamente del archivo de EAGLE y dibujada aquí. Elige una net y síguela.',
    viewLabel: 'Vista',
    layersLabel: 'Capas',
    view2d: 'Plana',
    view3d: 'Apilada',
    viewSolid: 'Montada',
    flip: 'Dar la vuelta',
    componentsWord: 'componentes',
    underneathWord: 'debajo',
    hintSolid: 'La misma placa con sus componentes, construida a partir del archivo IDF que EAGLE exportó al CAD mecánico en 2017 — cada footprint, posición, rotación y cara sale de ahí. Diecinueve de las 59 piezas van montadas debajo. Dale la vuelta y las encuentras.',
    explode: 'Separación',
    spin: 'arrastra para girar',
    hintStack: 'Es la misma placa, vista de canto. Dos láminas de cobre con 1,6 mm de fibra de vidrio entre ellas, y 34 postes metalizados cosiéndolas. Cada poste amarillo es una vía — la única forma de que una señal pase de una cara a la otra.',
    both: 'Ambas',
    topOnly: 'Solo la de arriba',
    bottomOnly: 'Solo la de abajo',
    netsLabel: 'Nets',
    allNets: 'Todas',
    segments: 'Segmentos',
    crossings: 'Cambios de capa',
    length: 'Longitud de cobre',
    legendTop: 'cobre superior',
    legendBottom: 'cobre inferior',
    legendVia: 'vía',
    hintIdle: 'El rojo corre por la cara superior, el azul por la inferior. Cada anillo amarillo es una vía: un agujero metalizado por donde la pista baja al otro lado.',
    hintCrossings: 'La net {net} cambia de capa {n} veces. Cambia a una sola capa y mírala partirse en trozos — esos huecos son donde va por la cara que acabas de ocultar.',
    hintFlat: 'La net {net} nunca sale de su capa. Nada se le puso delante, así que nunca tuvo que bajar.',
    hintOneLayer: 'Media placa ha desaparecido. Todo lo que falta va por la otra cara — y lo único que lo hace posible es que ambas caras están cosidas por vías.',
  },
  steel: {
    lede: 'Los ensamblajes en que está organizado el proyecto mecánico, una carpeta cada uno, reconstruidos a partir de los planos con los que se mecanizaron. Elige uno, desármalo y lee de qué está hecho.',
    productLabel: 'Producto',
    explode: 'Vista explosionada',
    zoom: 'Zoom',
    reset: 'Restablecer vista',
    loading: 'cargando las piezas impresas…',
    spin: 'arrastra para girar',
    autoSpin: 'Girar',
    pieces: 'Piezas',
    span: 'Dimensión mayor',
    provenance: 'Las piezas torneadas y cortadas se construyen desde sus planos acotados. Las impresas son sus STL reales. La disposición se ajustó a los renders de 2017, porque los ensamblajes de SolidWorks no se pueden leer.',
    processTitle: 'La prueba está en la estructura de carpetas',
    processLede: 'El proyecto mecánico no está archivado por pieza. Está archivado por cómo se fabrica cada una — que es la diferencia entre modelar algo y especificarlo.',
    processes: [
      { label: 'Torno y mecanizado', count: 11, note: 'cada una con plano acotado' },
      { label: 'Corte láser', count: 5, note: 'acrílico plano, dibujado y tolerado' },
      { label: 'Impresión 3D', count: 7, note: 'las piezas cargadas aquí como STL' },
      { label: 'Compra', count: 14, note: 'sensores, celdas, conectores' },
      { label: 'Montaje de cables', count: 1, note: 'un mazo de cuatro vías' },
    ],
    drawings: '16 planos acotados · 82 líneas en 7 listas de materiales',
    products: {
      'station': { name: 'Estación meteorológica completa', kind: 'la estación completa', blurb: 'Todos los ensamblajes de abajo, donde el render de 2017 los coloca.' },
      'cabeca-os': { name: 'Cabeza 1 · Solo suelo', kind: 'cabezal solo-suelo', blurb: 'El collar mecanizado, la columna y la tapa impresas, acrílico cortado por láser, y dos celdas fotovoltaicas.' },
      'cabeca-ws': { name: 'Cabeza 2 · Estación meteorológica', kind: 'cabezal de estación', blurb: 'El mismo cabezal, con un sensor UV y un TIL-78 donde iban las celdas.' },
      'corpo': { name: 'Mástil', kind: 'el mástil', blurb: 'Un cono, cuatro acoples, seis separadores y el tubo de un metro. Los separadores fijan las profundidades de los sensores enterrados.' },
      'painel': { name: 'Panel solar', kind: 'conjunto solar', blurb: 'Dos paneles en dos soportes mecanizados.' },
      'pcb': { name: 'PCB', kind: 'la placa, en el modelo mecánico', blurb: 'El laminado y las dos caras pobladas — la misma exportación IDF con la que el capítulo 02 monta su placa.' },
      'air': { name: 'Sensor 0 · AIR', kind: 'unidad de superficie', blurb: 'La varilla, su asiento mecanizado, y la cuna de batería impresa con su tapa.' },
      'thd': { name: 'Sensor 1 · THD', kind: 'sensor de suelo enterrado', blurb: 'Cuerpo mecanizado estriado bajo tapa de acrílico cortada por láser, encapsulado en epoxi, con latiguillo M12.' },
      'gas': { name: 'Sensor 5 · GAS STATION', kind: 'banco de sensores de gas', blurb: 'MQ-2, MQ-7 y MQ-8 con un barómetro, en un soporte impreso bajo tapa ventilada.' },
    },
  },
  system: {
    lede: 'Una lectura de humedad, desde el pin enterrado hasta el número en la mano de alguien. Dale a play. Después rompe algo — haz clic en una etapa — y vuelve a lanzarla, porque lo interesante no es cuando funciona.',
    play: 'Enviar una lectura',
    running: 'en tránsito…',
    again: 'Enviar otra',
    repair: 'Reparar todo',
    total: 'Extremo a extremo',
    verdictArrived: 'Llegó. Ocho capas, un número, y nadie tuvo que pensar en ninguna.',
    verdictFailed: 'Se detuvo en {stage}.',
    breakHint: 'Haz clic en una etapa para romperla.',
    silentBadge: 'sigue devolviendo un número',
    goto: 'capítulo',
    stages: {
      silicon: { name: 'Silicio', does: 'El ADC muestrea la sonda', payload: 'ADC 2871 / 4095', broken: 'El pin no lee nada. Todo número por encima de esto es ya una conjetura sobre un cable.' },
      copper:  { name: 'Cobre',   does: 'Cruza la placa hasta la radio', payload: '1,63 V', broken: 'Una grieta capilar en una pista. Intermitente — la peor clase, porque pasa en el banco.' },
      steel:   { name: 'Acero',   does: 'Sale por el cabezal sellado', payload: 'M12 · IP67', broken: 'Agua más allá del sello. La lectura sigue llegando, puntual, y está mal. Nada avisa.' },
      signal:  { name: 'Señal',   does: 'Publicada en el broker', payload: 'farm/greenhouse/soil-1/moisture', broken: 'El broker es inalcanzable. El dispositivo sigue midiendo perfectamente y nadie escucha.' },
      service: { name: 'Servicio', does: 'Escrita en la base de datos', payload: 'INSERT → reading_id 128374', broken: 'La API responde y la escritura falla. El panel muestra ayer, con total confianza.' },
      swarm:   { name: 'Enjambre', does: 'Atendida por una réplica', payload: 'pod 7/12', broken: 'Ninguna réplica libre. 503 — y los reintentos dejan la cola peor que la caída.' },
      model:   { name: 'Modelo',  does: 'Clasificada por el modelo', payload: 'sano · 0,94', broken: 'El modelo responde, con confianza, sobre un suelo que nunca ha visto. Un número, y ninguna forma de saber que está mal.' },
      glass:   { name: 'Cristal', does: 'Renderizada en el móvil', payload: '43 % de humedad', broken: 'Todo lo anterior funcionó. La pantalla no muestra nada, porque nadie hizo el estado vacío.' },
    },
  },
  glass: {
    lede: 'Una tarjeta, escrita dos veces y mostrada en los dos móviles. Cambia lo que quieras abajo y mira a los dos dialectos decir lo mismo — porque son dos formas de enunciar una pantalla, no dos pantallas distintas.',
    accent: 'Acento',
    layout: 'Disposición',
    radius: 'Radio de esquina',
    stacked: 'Apilada',
    inline: 'En línea',
    device: 'Dispositivo',
    iphone: 'iPhone',
    android: 'Android',
    card: {
      sensor: 'soil-1 · invernadero', status: 'sano', age: '2 s',
      delta: '2,4', depth: '40 cm', depthLabel: 'profundidad', soil: '22,4 °C', soilLabel: 'suelo',
    },
    noteTitle: 'Fíjate en lo que cambia cada uno',
    note: 'SwiftUI cambia VStack por HStack y mantiene el mismo parámetro spacing:. Flutter cambia Column por Row — cada SizedBox tiene que cambiar de eje con él, height pasando a width, {n} aquí, y el valor además hay que envolverlo en Expanded para compartir la fila. Ninguno está mal; uno son más sitios donde equivocarse.',
    swiftOnAndroid: 'SwiftUI no corre aquí. Flutter sí — que es justamente el motivo de saber los dos.',
  },
  flow: {
    lede: 'Esto es lo que hace Tradx, en miniatura. No escribes el bucle — cableas la lógica, y el motor la ejecuta sobre las velas. Mueve los parámetros y mira cómo cambian a la vez el grafo y las operaciones.',
    period: 'Periodo del RSI',
    buyLevel: 'Entrar por encima de',
    sellLevel: 'Salir por debajo de',
    run: 'Ejecutar',
    inSample: 'Ajusta en esta mitad',
    outSample: 'La mitad que nunca viste',
    trades: 'Operaciones',
    returnPct: 'Rentabilidad',
    winRate: 'Aciertos',
    nodes: {
      source: 'Datos de mercado', rsi: 'Indicador RSI', crossUp: 'Cruce al alza',
      crossDown: 'Cruce a la baja', entry: 'Entrada', exit: 'Salida',
    },
    hintIn: 'Ajústalo hasta que el número sea bonito. Esa es la parte fácil, y es lo que te enseña cualquier captura de backtest de internet.',
    hintOut: 'Mismo grafo, mismos parámetros, un tramo de mercado al que nunca se ajustó.',
    reveal: 'Entre las 75.429 combinaciones de parámetros, el conjunto que más rindió en la mitad donde ajustaste quedó en el puesto 22.949 en la mitad que no viste. Del primer puesto al vigésimo segundo milésimo. Por eso un backtest es una hipótesis y no un resultado, y por eso el número bonito es la parte fácil.',
  },
  field: {
    lede: 'Un objeto, construido dos veces. A un lado del interruptor es la malla del capítulo 03, con la que se imprimió la pieza. Al otro es un campo de gaussianas sobre esa misma malla — repartidas aquí en vez de ajustadas, para que los dos queden lado a lado y la diferencia sea el método y nada más.',
    mesh: 'Malla', splats: 'Gaussianas',
    count: 'Gaussianas', size: 'Dispersión', spin: 'arrastra para girar',
    primitives: 'Primitivas', authored: 'Hechas a mano',
    authoredMesh: 'cada triángulo', authoredSplat: 'ninguna',
    hintMesh: '997 triángulos, cada uno colocado por alguien en SolidWorks en 2017.',
    hintSplats: 'Nadie colocó estas. En una reconstrucción real empiezan como ruido y son movidas, estiradas y recoloreadas por descenso de gradiente hasta que el render deja de contradecir a las fotografías — por eso la cuenta llega a cientos de miles sin que a nadie le importe.',
    loading: 'cargando la malla…',
  },
  ui: {
    duty: 'Ciclo de trabajo',
    brightness: 'Brillo percibido',
    frequency: 'Frecuencia',
    play: 'Ejecutar',
    pause: 'Pausar',
    reset: 'Reiniciar',
    subscribe: 'Suscribir',
    publish: 'Publicar',
    matched: 'entregado',
    dropped: 'no entregado',
    replicas: 'Réplicas',
    traffic: 'Tráfico entrante',
    latency: 'Latencia p99',
    dropped_req: 'Peticiones perdidas',
    cost: 'Coste',
    train: 'Entrenar',
    epoch: 'Época',
    accuracy: 'Precisión',
    wip: 'Interactividad en construcción',
    wipNote: 'El layout es el definitivo; este panel se está cableando.',
    learned: 'Lo que acabas de aprender',
  },
};
