import type { Content } from './types';

export const es: Content = {
  meta: {
    title: 'Maykon Meneghel — el currículum jugable',
    description:
      'Ingeniero móvil sénior. Plataformas Apple nativas — iOS, macOS y visionOS — en Swift y SwiftUI, multiplataforma en Flutter en dos tiendas, y las APIs en Node y Kubernetes detrás, explicados con mini-juegos que puedes jugar en la propia página.',
  },
  nav: { chapters: 'Capítulos', family: 'La familia', contact: 'Contacto', resume: 'Currículum' },
  hero: {
    kicker: 'Ingeniero Móvil Sénior · iOS, macOS y visionOS nativos · Flutter y las APIs detrás',
    name: 'Maykon Meneghel',
    headline: 'Entrego la app Apple nativa y la API con la que habla.',
    sub: 'La mayoría de los CV te cuentan lo que alguien sabe hacer. Este te deja probarlo. Debajo de todo esto hay una sola cosa: una lectura. Construí el instrumento que produce una — firmware, placa, carcasa, enterrado en un campo — y pasé los siete años siguientes en todo lo que le ocurre a un número después. Cada capítulo de abajo es un mini-juego que funciona.',
    proof: [
      'Tradx · producto propio en Flutter, ~15 mil descargas sumando Mac App Store y Microsoft Store',
      'De trainee a sénior en cuatro años en un proyecto Apple en producción',
      'Clean Architecture para SwiftUI · 30★ en GitHub',
      'Apple Developer Academy · posgrado en desarrollo iOS',
    ],
    links: [
      { label: 'LinkedIn', href: 'https://www.linkedin.com/in/maykonmeneghel/' },
      { label: 'GitHub', href: 'https://github.com/maykonmeneghel' },
      { label: 'Tradx en la App Store', href: 'https://apps.apple.com/us/app/tradx/id6743033919' },
    ],
    cv: 'Descargar CV (PDF)',
    cta: 'Empezar el recorrido',
    scrollHint: 'desliza',
    boot: [
      'meneghel.me boot v2.0',
      'cargando plataformas ... ios · macos · visionos · windows',
      'montando frameworks .... swiftui · uikit · swift 6 · flutter · dart 3',
      'iniciando servicios .... node · nestjs · java · docker · kubernetes',
      'cargando inteligencia .. pytorch · gan · gaussian splatting',
      'listo.',
    ],
  },
  acts: [
    {
      before: 'glass',
      label: 'Acto uno',
      title: 'La pantalla',
      lede: 'Una lectura no vale nada hasta que alguien la ve, y un teléfono da 16,7 milisegundos para mostrarla. Siete años entregando apps, nativas y multiplataforma — y antes de ellas tres años un nivel más abajo, en firmware, placas y piezas mecanizadas, que la Apple Developer Academy convirtió en esto: la misma ingeniería, movida hacia arriba en la pila. Este acto son los últimos centímetros de ese trayecto — llegar a tiempo, seguir legible en condiciones que nadie diseñó, y alcanzar solo a la persona correcta.',
    },
    {
      before: 'pulse',
      label: 'Acto dos',
      title: 'Con qué habla la app',
      lede: 'Vuelve hacia atrás desde la pantalla y encuentras el trayecto que hizo el número para llegar. Tiene que llegar mientras todavía es verdad, ser encontrado entre cientos de miles de hermanos, aguantar que todos pregunten a la vez, y por fin merecer una decisión. Cuatro capítulos — y en el último, las cuatro decisiones son mías.',
    },
    {
      before: 'mind',
      label: 'Acto tres',
      title: 'Y los modelos por debajo',
      lede: 'Todo hasta aquí mueve una lectura que ya existe. Este inventa la siguiente — y es donde las dos mitades de este sitio resultan ser una sola. Entrené el modelo con datos de mercado; corre aquí sobre una sonda de suelo que enterré años antes, sin cambiar una línea, porque una serie temporal no sabe qué mide.',
    },
    {
      before: 'field',
      label: 'Acto cuatro',
      title: 'Y entonces salió de la pantalla',
      lede: 'Y ahora la medida es el objeto. En Eldorado, en macOS y visionOS, una cosa tridimensional deja de ser algo que un ingeniero dibujó y pasa a ser algo que una cámara midió — el mismo movimiento que hice en 2019, repetido, ahora sobre el mundo.',
    },
  ],
  hardwarePage: {
    title: 'Maykon Meneghel — los años de hardware',
    description: 'Antes de las apps: una sonda de suelo diseñada, ruteada, mecanizada y clavada en la tierra. Firmware, PCB, CAD y MQTT, todo jugable.',
    back: 'Volver al portafolio',
    kicker: 'El plus',
    heading: 'Antes de las apps, hice la cosa que manda el dato',
    lede: 'Esta es la mitad de la trayectoria que vino primero, y el origen de todo lo que la otra página mueve. Empecé un nivel más abajo — firmware, placas, piezas mecanizadas, y una sonda de suelo diseñada, ruteada, mecanizada y enterrada durante dos años — y la Apple Developer Academy es donde giró: la misma ingeniería, movida hacia arriba en la pila. Estos cuatro capítulos siguen aquí porque saber cuánto cuesta una lectura antes de llegar a tu app cambia cómo construyes la app, y porque las doscientas cuarenta mil filas del capítulo de base de datos salieron de algo como esto.',
    outro: 'Ahí empezó. En lo que se convirtió está en la otra página.',
    backCta: 'Ver lo que construyo hoy',
  },
  chapters: [
    {
      track: 'mobile', codename: 'THREAD', slug: 'thread',
      era: 'iOS y Flutter · 2019 → hoy',
      title: 'El frame dura dieciséis milisegundos',
      lede: 'Toda discusión de concurrencia en un equipo móvil es, en el fondo, sobre un solo número. Una pantalla debe un frame cada 16,7 ms, y todo — async/await, actors, isolates, cancelación — trata de lo que puedes hacer dentro de él. Abajo está la misma lista cargada de tres formas, con el gráfico de frames que te mostraría un profiler.',
      panel: 'instruments · frame timing',
      takeaway: 'El botón del medio es el capítulo entero. <b>await suspende una función, no la mueve</b> — la continuación se reanuda en el main actor y el trabajo caro sigue cayendo dentro de un frame. Código asíncrono que nunca sale del hilo principal es el bug de rendimiento más común en móvil, y es invisible hasta que alguien lo perfila.',
      stack: ['Swift Concurrency', 'async/await', 'actors', '@MainActor', 'Combine', 'Isolates', 'compute()', 'Instruments', 'Cancelación de Task', '60 fps'],
    },
    {
      track: 'mobile', codename: 'CRISTAL', slug: 'glass',
      era: 'Swift y Flutter · 2019 → hoy',
      title: 'La tarjeta que sobrevive al mundo real',
      lede: 'Cualquiera construye la tarjeta del diseño. El trabajo es construir la que sigue siendo legible cuando la persona que sostiene el móvil puso el texto en el mayor tamaño de accesibilidad, está en vista dividida, en un idioma cuyas palabras son más largas, leyendo de derecha a izquierda, en una conexión que nunca entregó la imagen. El diseñador te da un estado. Tú entregas seis.',
      panel: 'PositionRow.swift / position_row.dart',
      takeaway: 'El layout dibujado al comp sobrevive a una de las siete condiciones de abajo — justo aquella para la que fue dibujado. <b>La diferencia no es gusto, es qué pregunta hace el layout</b>: no "¿la letra es grande?" sino "¿esto cabe?". Haz la segunda pregunta y una traducción más larga deja de ser un reporte de bug.',
      stack: ['SwiftUI', 'UIKit', 'Flutter', 'Dynamic Type', 'VoiceOver', 'Localización', 'RTL', 'Layout adaptativo', 'Accesibilidad', 'Design systems'],
    },
    {
      track: 'mobile', codename: 'PUERTA', slug: 'gate',
      era: 'Tradx · 2022 → hoy',
      title: 'El login es por donde entran a una app',
      lede: 'Todo lo demás en una app móvil falla de forma visible. Esto falla en silencio: el login funciona, la persona entra, y el flujo estuvo abierto todo el tiempo. Rehice esta parte en Tradx después de leer nuestra propia implementación con atención — son las cincuenta líneas que preguntaría en cualquier entrevista sénior.',
      panel: 'oauth · manejo del redirect',
      takeaway: 'Cambiar el token por un código de un solo uso es la primera corrección que todos intentan, y por sí sola <b>abre dos agujeros para cerrar uno</b>. Un código necesita PKCE para que solo la app que inició el flujo pueda gastarlo, y un solo uso para que no se gaste dos veces. Media migración de seguridad es peor que ninguna, porque parece terminada.',
      stack: ['OAuth 2.0', 'PKCE', 'Universal Links', 'ASWebAuthenticationSession', 'Keychain', 'App Links', 'Deep linking', 'Modelado de amenazas'],
    },
    {
      track: 'platform', codename: 'PULSO', slug: 'pulse',
      era: 'Tradx · 2022 → hoy',
      title: 'El cliente no debería tener que preguntar',
      lede: 'Casi todo lo que una app muestra es la respuesta a una pregunta que hizo. Un precio en vivo no: cuando llega la respuesta la pregunta ya cambió, y volver a preguntar gasta una petición entera para oír, casi siempre, que no pasó nada. Este capítulo es la diferencia entre un endpoint que responde y un canal que te avisa.',
      panel: 'tradx · feed de precios',
      takeaway: 'Preguntar una vez por segundo costó <b>ocho veces más bytes</b> que mantener un socket abierto, y aun así se perdió un cuarto de los ticks. Frecuencia no es actualidad: la única forma de dejar de llegar tarde es dejar de preguntar.',
      stack: ['Node.js', 'NestJS', 'WebSockets', 'APIs REST', 'Arquitectura orientada a eventos', 'Diseño de API'],
    },
    {
      track: 'platform', codename: 'SERVICIO', slug: 'service',
      era: 'Backend · 2018 → hoy',
      title: 'Alguien tiene que recordarlo todo',
      lede: 'Una lectura que nadie guardó es una lectura que no ocurrió. Detrás de cada dispositivo y de cada cliente hay una API y una base de datos, y la diferencia entre un producto rápido y uno lento suele ser una sola decisión tomada aquí. La tabla de abajo tiene doscientas cuarenta mil lecturas de sensor — del tipo que la sonda de la otra página pasó dos años produciendo.',
      panel: 'psql · meneghel_db',
      takeaway: 'Sin índice, la base lee <b>todas las filas</b> para responderte. Con uno, salta directo al punto. Misma consulta, mismos datos, mismo servidor — mil veces más rápido.',
      stack: ['Node.js', 'Express', 'Restify', 'MongoDB', 'PostgreSQL', 'REST'],
    },
    {
      track: 'platform', codename: 'ENJAMBRE', slug: 'swarm',
      era: 'Backend · 2018 → hoy',
      title: 'Una sola máquina nunca alcanza',
      lede: 'Un lector es una consulta; diez mil a la vez es una arquitectura. El tráfico no llega con educación — llega de golpe, a las 3 de la mañana, el día del lanzamiento. Los contenedores y Kubernetes son cómo respondes a eso sin despertarte.',
      panel: 'kubectl · production',
      takeaway: 'No hiciste el código más rápido — hiciste <b>más copias de él</b>. El escalado horizontal cambia dinero por latencia, y un autoscaler hace ese cambio por ti, solo.',
      stack: ['Docker', 'Kubernetes', 'HPA', 'Balanceo de carga', 'CI/CD'],
    },
    {
      track: 'platform', codename: 'FLUJO', slug: 'flow',
      era: 'Tradx · 2022 → hoy',
      title: 'Y entonces construí la herramienta',
      lede: 'Tradx es mi sandbox — el lugar donde tomo todas las decisiones y convivo con todas ellas. Un cliente de trading de escritorio escrito en Flutter, donde una estrategia es un grafo que conectas en vez de código que escribes, publicado en la Mac App Store y en la Microsoft Store, con unas quince mil descargas entre las dos. Lo construimos dos: Luiz Veloso y yo, por pull request, con revisiones que ninguno se salta.',
      panel: 'tradx · grafo de estrategia',
      takeaway: 'Un backtest es una <b>hipótesis</b>, no un resultado. Cualquiera ajusta una curva hasta que queda bonita con los datos que ya tiene; todo el oficio está en saber cuánto vale ese número con los datos que no tiene.',
      stack: ['Node.js', 'NestJS', 'Flutter', 'MongoDB', 'Redis + BullMQ', 'Motor de backtest', 'Paper trading'],
    },
    {
      track: 'ai', codename: 'MENTE', slug: 'mind',
      era: 'StockGAN · 2021',
      title: 'Enseña a la máquina a adivinar qué viene después',
      lede: 'En 2021 construí desde cero una red generativa adversaria para series temporales — el trabajo en el que mi posgrado en IA y mi máster en Bioingeniería dejan de ser líneas en un diploma — dos redes, una intentando inventar la siguiente lectura y otra intentando pillarla mintiendo. La entrené con datos financieros. Aquí corre sobre una sonda de suelo que diseñé y enterré años antes, sin cambiar nada, porque una serie temporal no sabe qué mide.',
      panel: 'gan_model.py — train_step()',
      takeaway: 'Dos modelos, una función de pérdida y una perilla entre ellos. Exígele al pronosticador que quede cerca y responde con el promedio de todo, que es seguro e inútil. Exígele que sea creíble y responde con algo que se mueve como el sensor y no sabe nada. <b>Cada modelo que entrego es ese intercambio hecho a propósito</b>, escrito y medido.',
      stack: ['TensorFlow / Keras', 'GANs', 'LSTM', 'Series temporales', 'Selección de features con PCA y XGBoost'],
    },
    {
      track: 'spatial', codename: 'CAMPO', slug: 'field',
      era: 'Eldorado · 2022 → hoy',
      title: 'Y ahora el objeto está hecho de luz',
      lede: 'El capítulo anterior inventó el siguiente número de una serie. Este deja de tratar el mundo como algo que alguien dibuja. Una escena deja de ser una superficie que alguien modeló y pasa a ser una nube de gaussianas orientadas, ajustadas por descenso de gradiente hasta que sus renders coinciden con las fotografías — lo que significa que nadie la dibuja, y no queda malla alguna que convertir. Las reconstrucciones reales empiezan con una cámara recorriendo una sala. La demo de abajo deliberadamente no: usa una pieza que yo mismo diseñé e imprimí, porque la única manera de ver qué cambia el método es mirar el mismo objeto construido de las dos formas.',
      panel: 'gaussian splatting · visor',
      takeaway: 'Una malla dice dónde están las <b>superficies</b>, y un ingeniero dibujó cada una. Un campo de splats dice dónde está la <b>luz</b>, y nadie dibujó nada de eso — se ajustó hasta que el render dejó de contradecir a la fotografía.',
      stack: ['Gaussian Splatting', '3DGS', 'visionOS', 'macOS', 'PyTorch', 'CUDA', 'Fotogrametría', 'Campos de radiancia'],
    },


    {
      track: 'hardware', codename: 'SILICIO', slug: 'silicon',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Todo empieza en un solo pin',
      lede: 'Mucho antes de que exista una app, hay un microcontrolador decidiendo —millones de veces por segundo— si un cable está en alto o en bajo. Catorce firmwares me enseñaron que todo lo de arriba depende de acertar aquí.',
      panel: 'pwm_playground.c',
      takeaway: 'Acabas de atenuar un LED sin cambiar nunca su tensión. Eso es <b>PWM</b>: el pin solo está completamente encendido o completamente apagado — simplemente conmuta más rápido de lo que tu ojo puede seguir.',
      stack: ['C/C++', 'ESP32', 'PIC18F4550', 'ATmega', 'Timers y PWM'],
    },
    {
      track: 'hardware', codename: 'COBRE', slug: 'copper',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Luego necesita una placa',
      lede: 'Un esquemático es una promesa. La PCB es donde se cumple. Cada placa que he fabricado empezó exactamente con este rompecabezas: llevar cada señal a su sitio, en una superficie donde nada puede cruzarse.',
      panel: 'router.pcb',
      takeaway: 'Dos pistas no pueden cruzarse en la misma capa. Esa única restricción es la razón por la que las placas reales tienen 2, 4, a veces 12 capas apiladas.',
      stack: ['Altium', 'EAGLE', 'SMD y THT', 'Gerber', 'Diseño para manufactura'],
    },
    {
      track: 'hardware', codename: 'ACERO', slug: 'steel',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Y un cuerpo que sobreviva al campo',
      lede: 'Un sensor enterrado en tierra empapada durante dos años no se preocupa por lo elegante que sea tu firmware. Se preocupa por la carcasa. Por eso la modelo yo mismo: cada pieza, cada tolerancia, cada sello.',
      panel: 'soil_probe.sldasm',
      takeaway: 'El hardware es la única capa que no puedes parchear en remoto. Por eso el diseño mecánico ocurre <b>antes</b> de la primera línea de firmware, no después.',
      stack: ['SolidWorks', 'Modelado 3D', 'Tolerancias', 'Sellado IP', 'Impresión 3D'],
    },
    {
      track: 'hardware', codename: 'SEÑAL', slug: 'signal',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Ahora haz que mil de ellos hablen',
      lede: 'Un dispositivo es un proyecto. Mil dispositivos son una arquitectura. MQTT es cómo se hablan sin conocerse nunca — y los comodines de tópico son todo el truco.',
      panel: 'broker · mqtt://meneghel.me:8883',
      takeaway: '<b>+</b> coincide con exactamente un nivel. <b>#</b> coincide con todo lo que hay debajo. Esa única regla es cómo un solo broker reparte a miles de dispositivos sin que ninguno guarde la lista de los demás.',
      stack: ['MQTT', 'Mosquitto', 'AWS IoT Core', 'QoS 0/1/2', 'Pub/Sub'],
    },
  ],
  record: {
    eyebrow: '12 · TRAYECTORIA',
    title: 'Las pruebas',
    lede: 'Nueve capítulos de demostración. Este es solo evidencia. Arrastra por los años y mira qué estaba corriendo a la vez — porque el titular honesto de esta línea de tiempo no es ningún empleo concreto, es lo poco que hubo uno solo.',
    climbTitle: 'De trainee a sénior en cuatro años',
    climbBody: 'Entré en el proyecto Apple en 2022 como trainee y sigo en el mismo producto, hoy como sénior. Nadie asciende por calendario: cada escalón vino de coger algo que nadie quería — el proceso de release, la suite inestable, la pantalla que todos reescribieron dos veces — y convertirlo en un problema fácil para los demás. Arrastra el año y mira la franja de industria: las cuatro barras seguidas son el mismo producto y el mismo equipo, vistos desde cuatro niveles de responsabilidad distintos.',
    lanes: {
      education: 'Formación',
      research: 'Investigación',
      industry: 'Industria',
      venture: 'Emprendimientos',
    },
    roles: {
      grad: 'Ing. de Control y Automatización',
      msc: 'Máster en Bioingeniería',
      academy: 'Posgrado de especialización, Desarrollo iOS',
      aiSpec: 'Especialización en Inteligencia Artificial Aplicada',
      pucLab: 'Becario, Laboratorio de Automatización y Sistemas',
      araucaria: 'Ingeniero de Software — investigación aplicada, IA y salud embebida',
      freelance: 'Desarrollador de Software, autónomo',
      residency: 'Trainee · Apple Residency',
      junior: 'Desarrollador Júnior · Proyecto Apple',
      techLead: 'Tech Lead · Apple Internship',
      fullstack: 'Desarrollador Full Stack · Proyecto Apple',
      senior: 'Desarrollador Sénior · Proyecto Apple',
      ghel: 'Technology Advisor · Proyecto Renault',
      holding: 'Consejero Administrativo — el holding familiar',
      tradx: 'COO y Cofundador',
    },
    scrubber: {
      simultaneous: '{n} funciones a la vez',
      one: '1 función',
      none: 'nada registrado todavía',
      today: 'hoy',
      drag: 'arrastra el año',
    },
    ventures: {
      title: 'Seis empresas',
      lede: 'Fundadas o cofundadas. Algunas crecieron, otras no — que es justamente el motivo de fundar seis.',
      founder: 'Fundador',
      coFounder: 'Cofundador',
      sectors: { fintech: 'fintech', agritech: 'agritech', smartHome: 'casa inteligente', proptech: 'proptech', edtech: 'edtech' },
    },
    publications: {
      title: 'Publicado y premiado',
      lede: 'Seis trabajos académicos, tres de ellos con revisión por pares, y ninguno sobre móvil — y ese es justamente el punto. Ahí aprendí a equivocarme en público: a describir un método con precisión suficiente para que otro lo ataque, aceptar la revisión y cambiar la afirmación. Ese hábito vale más en un code review que cualquiera de los resultados.',
      read: 'leer el artículo',
      code: 'código',
      items: {
        soilInstrument: 'Instrumento para la Medición de Factores y/o Elementos Naturales del Suelo',
        fesTool: 'A Tool to Select FES Parameters for chronic SCI',
        fallDetector: 'Indoors Wi-Fi Fall Detector Buckle for the Elderly',
        inSilicoFes: 'Aplicación, in silico, de estímulos eléctricos en un modelo neuromuscular compatible con lesión medular crónica',
        balanceModel: 'Modelado matemático del sistema de mantenimiento del equilibrio mediante identificación de sistemas',
        stockGan: 'Predicción de Series Financieras con Redes Generativas Adversarias',
      },
    },
    press: {
      title: 'En la prensa',
      read: 'leer el artículo',
      items: {
        hubli: 'Hubli, creado en la Apple Developer Academy — Apple me nombra entre sus cinco creadores',
        neonWave: 'Neon Wave, juego de iOS cubierto por MacMagazine',
      },
    },
    closing: {
      line: 'Construyo la app, y construyo aquello con lo que habla.',
      note: 'La pantalla, el estado en ella, la API que la llena, la base de datos debajo, y el modelo que lo lee. La mayoría domina una de esas. Yo he entregado todas, y sigo sabiendo cuál es la parte difícil.',
    },
    contact: {
      title: 'Hablemos',
      lede: 'Si algo de esto tiene la forma de un problema que tienes, quiero saberlo. Correo o LinkedIn, lo que prefieras — el CV es un PDF de dos páginas y el código está en GitHub.',
      linkedin: 'Escríbeme por LinkedIn',
      github: 'Ver mi código',
      email: 'Escríbeme un correo',
      cv: 'Descargar mi CV',
    },
    skills: {
      title: 'Con qué trabajo',
      lede: 'Todo lo de abajo está acreditado por algún capítulo de esta página o está en un repositorio público. Nada aquí es aspiracional.',
      groups: {
        ios: 'iOS · Swift',
        cross: 'Multiplataforma',
        release: 'Publicación y release',
        languages: 'Lenguajes',
        backend: 'Backend y APIs',
        data: 'Datos',
        cloud: 'Cloud y DevOps',
        frontend: 'Web',
        ai: 'IA y 3D',
        embedded: 'Embebidos y hardware',
        ways: 'Forma de trabajar',
      },
    },
  },
  signal: {
    levels: ['sitio', 'área', 'dispositivo', 'medida'],
    anatomyLede: 'Un tópico es una ruta. Cada dispositivo de esta granja publica en una ruta formada por los mismos cuatro niveles — así que una suscripción es, en el fondo, una pregunta sobre qué niveles te importan.',
    legendPlus: 'coincide con exactamente un nivel, sea cual sea su contenido',
    legendHash: 'coincide con todo lo que venga debajo, y tiene que ser el último nivel',
    yourToken: 'escribiste',
    noToken: '—',
    subLabel: 'Tu suscripción',
    placeholder: 'farm/greenhouse/#',
    broker: 'Broker — todo lo que se está publicando',
    inbox: 'Tu bandeja — lo que te llegó',
    delivered: 'entregados',
    dropped: 'no entregados',
    missionsTitle: 'Tres suscripciones que acertar',
    missionsLede: 'Vale cualquier filtro que seleccione exactamente los tópicos correctos. Cada misión tiene más de una respuesta válida.',
    missions: [
      { id: 'greenhouse', goal: 'Todo lo que publica el invernadero — y nada más.' },
      { id: 'temps',      goal: 'Cada lectura de temperatura, venga de donde venga.' },
      { id: 'moisture',   goal: 'Cada lectura de humedad de la granja, pero no la de casa.' },
    ],
    solved: 'resuelta',
    invalidHash: 'el # tiene que ser el último nivel, solo',
    invalidPlus: 'el + tiene que ocupar un nivel entero, solo',
    invalidEmpty: 'un nivel del tópico no puede quedar vacío',
    emptyInbox: 'nada ha coincidido todavía',
    allSolved: 'Las tres. Ya entiendes los filtros de tópico MQTT mejor que mucha gente que los usa a diario.',
  },
  swarm: {
    lede: 'El tráfico de este servicio se dispara cada pocos segundos, como en un día de lanzamiento. Añade réplicas y la latencia baja; añade demasiadas y pagas por máquinas ociosas. Después déjaselo al autoscaler y mira dónde sigue perdiendo.',
    traffic: 'Entrada',
    replicas: 'Réplicas',
    latency: 'Latencia p99',
    dropped: 'Peticiones perdidas',
    cost: 'Coste',
    saturation: 'Saturación',
    auto: 'Autoscaler',
    autoHint: 'Apuntando al 60% de saturación. Un pod nuevo tarda unos 4s en estar listo — por eso siguen cayendo peticiones en la subida.',
    manualHint: 'Estás escalando a mano. El pico llega estés listo o no.',
    ready: 'listos',
    starting: 'arrancando',
    reset: 'Poner a cero',
    spike: 'pico',
    healthy: 'saludable',
    strained: 'bajo presión',
    failing: 'perdiendo tráfico',
    wasteful: 'sobredimensionado',
  },
  mind: {
    lede: 'En 2021 escribí una GAN que pronostica el siguiente valor de una serie temporal — generador, discriminador y bucle de entrenamiento desde cero. La entrené con treinta años de barras diarias, porque ahí era donde había histórico limpio y gratis, pero la red lee log-retornos y no tiene ni idea de qué miden los números. Así que aquí está corriendo sobre una sonda de suelo que construí años antes de todo esto. Lo que vale la pena mostrar es esto: el discriminador nunca juzga una lectura prevista por sí sola. La lectura se pega a las nueve reales que vinieron antes, y la red tiene que decir si la ventana entera salió del sensor. Ese es el juego. Tú eres el discriminador.',
    paper: 'StockGAN · LSTM(128) · ventana de 10 · entrenada con 30 años de barras diarias, corriendo aquí sobre soil-1',
    reading: 'soil-1 · invernadero · % de humedad',
    question: 'Una de estas dos ventanas termina con una lectura que la sonda tomó de verdad. La otra termina con una que inventó el generador. ¿Cuál es cuál?',
    slotA: 'Ventana A',
    slotB: 'Ventana B',
    pick: 'Elegir',
    real: 'REAL',
    generated: 'GENERADA',
    criticSays: 'el discriminador le dio',
    next: 'Siguiente ventana',
    reset: 'Empezar de nuevo',
    rounds: 'Rondas',
    you: 'Tú',
    network: 'El discriminador',
    fooled: 'Engañó al crítico',
    lambdaLabel: 'λ — cuánto de la nota del generador viene de engañar al crítico en vez de acertar el número',
    lambdaHis: 'lo que publiqué',
    meterTruth: 'Cerca de la verdad',
    meterReal: 'Se mueve como el sensor',
    arch: 'Lo que hay de verdad en el archivo',
    archGen: 'generador      LSTM(128, stateful) → Dropout(0.3) → Dense(n_features)',
    archDisc: 'discriminador  LSTM(128, stateful) → Dropout(0.1) → Dense(1, sigmoid)',
    archNote: 'RMSprop con decaimiento polinómico de 2.5e-4 a 1e-4 a lo largo de mil pasos. Entropía cruzada con label smoothing en 0.2, para que al discriminador nunca se le permita estar completamente seguro de nada. Objetivo real y objetivo generado multiplicados por ruido con σ = 0.25 durante el entrenamiento, para que no gane notando qué números están demasiado limpios. Doce indicadores — MACD, EMA, RSI, Bollinger, ROC, volatilidad — reducidos por PCA y XGBoost antes de que la red viera nada; en una sonda de suelo esos mismos doce se convierten en medias móviles y tasa de variación de la humedad, y ese es justamente el punto: la arquitectura cambió de dominio y el pipeline de features apenas parpadeó. Las funciones de pérdida de esta página son portes de las reales, constantes incluidas; el generador de aquí es un sustituto que reproduce el dilema sin meter 128 unidades LSTM en tu navegador.',
    hintStart: 'Elige una. Nueve lecturas reales, y una décima que es la sonda o mi generador.',
    hintRight: 'Correcto.',
    hintWrong: 'Incorrecto — y mira las dos notas de abajo. Es el mismo juicio que hace la red, sobre la misma ventana.',
    hintLow: 'Aquí abajo el generador se califica casi solo por error cuadrático, así que responde con la media condicional: la apuesta más segura posible. Es lo más preciso que puede decir y es obviamente falso — el paso es un tercio del tamaño de uno real. Todo pronosticador entrenado solo con MSE tiene este problema, y la mayoría nunca se entera.',
    hintHigh: 'Aquí arriba se califica solo por engañar al crítico. Las lecturas por fin se mueven como se mueve el sensor, y los números están más lejos de la próxima hora que nunca. Parece correcto. No lo es.',
    hintHis: '0.6 es lo que publiqué: inclinándose hacia el crítico, y pagando unas dos décimas de punto de error por ello. Ningún ajuste gana en los dos medidores — que es exactamente por qué ese número es una decisión y no un valor por defecto.',
    verdict: 'Estás en {you} en estas rondas. La red está en {net} sobre las mismas ventanas.',
  },
  thread: {
    lede: 'Una pantalla debe un frame cada 16,7 ms. Esta está cargando veinticuatro filas, y lo único que cambia entre los tres botones es dónde ocurre el decode. Mira el gráfico de frames, no la lista.',
    pickLabel: 'Dónde corre el trabajo',
    device: 'iPhone · 60 Hz',
    frozen: 'no responde',
    frameTimes: 'Tiempos de frame',
    budget: 'presupuesto de 16,7 ms',
    onBudget: 'dentro',
    dropped: 'perdido',
    worst: 'Peor frame',
    droppedFrames: 'Frames perdidos',
    jank: 'Jank',
    wasted: 'Desperdiciado al salir',
    leave: 'Salir de la pantalla en el frame 6',
    cancelOn: 'cancelar el trabajo',
    cancelOff: 'dejarlo terminar',
    strategies: {
      sync: {
        name: 'En el hilo principal',
        hint: 'Un frame que dura casi trescientos milisegundos. La lista no tartamudea — se detiene, y el sistema operativo empieza a plantearse si tu app sigue viva. Todo ingeniero móvil ha publicado esto una vez.',
        swift: '// Everything, right now, on the main actor.\n@MainActor\nfunc load(_ rows: [Row]) {\n  for row in rows {\n    let image = decode(row.data)   // blocks the frame\n    cache[row.id] = image\n  }\n}',
        dart: '// Everything, right now, on the UI isolate.\nvoid load(List<Row> rows) {\n  for (final row in rows) {\n    final image = decode(row.data);  // blocks the frame\n    cache[row.id] = image;\n  }\n}',
      },
      await: {
        name: 'await, aún en main',
        hint: 'Esta es la que pilla a la gente. El congelamiento desapareció y el jank no: await suspende la función, no la mueve. La continuación se reanuda en el main actor y el decode ocurre ahí, así que cada fila sigue pasándose del presupuesto. Parece arreglado y no lo está.',
        swift: '// Awaited — and still on the main actor.\n@MainActor\nfunc load(_ rows: [Row]) async {\n  for row in rows {\n    let image = await decode(row.data)\n    cache[row.id] = image          // resumes here, on main\n  }\n}',
        dart: '// Awaited — and still on the UI isolate.\nFuture<void> load(List<Row> rows) async {\n  for (final row in rows) {\n    final image = await decode(row.data);\n    cache[row.id] = image;           // resumes here, on the UI isolate\n  }\n}',
      },
      offMain: {
        name: 'Fuera del main actor',
        hint: 'Ahora el decode pertenece a un actor — o a un isolate — y el frame solo paga por recibir la fila terminada. No se pierde nada, el peor frame cabe en el presupuesto, y la lista se desplaza como debió hacerlo desde el principio.',
        swift: '// The decode belongs to something that is not the UI.\nactor Decoder {\n  func decode(_ data: Data) -> UIImage { ... }\n}\n\nfunc load(_ rows: [Row]) async {\n  await withTaskGroup(of: (Row.ID, UIImage).self) { group in\n    for row in rows {\n      group.addTask { (row.id, await decoder.decode(row.data)) }\n    }\n    for await (id, image) in group {\n      await MainActor.run { cache[id] = image }\n    }\n  }\n}',
        dart: '// compute() moves the work to another isolate.\nFuture<void> load(List<Row> rows) async {\n  await Future.wait(rows.map((row) async {\n    final image = await compute(decodeBytes, row.data);\n    cache[row.id] = image;\n  }));\n}',
      },
    },
  },
  link: {
    lede: 'Autenticar a alguien por el navegador y devolver el resultado a la app son las cincuenta líneas más sensibles de un código móvil. Empieza por la versión que muestra todo tutorial y ciérrala interruptor a interruptor. El orden importa más de lo que te gustaría.',
    hintStart: 'Empieza por la versión del tutorial y ciérrala interruptor a interruptor. Mira hasta dónde llega el redirect.',
    channel: 'El redirect',
    customScheme: 'esquema tradx://',
    universalLink: 'Universal Link',
    carries: 'Qué vuelve',
    token: 'el access token',
    code: 'un código de un solo uso',
    guards: 'Protecciones',
    singleUse: 'un solo uso',
    shipIt: 'Lo que publiqué',
    naive: 'Volver al tutorial',
    reachedLabel: 'El redirect llega a',
    openLabel: 'Ataques que pasan',
    steps: {
      open: {
        name: 'The app opens the browser',
        does: 'ASWebAuthenticationSession, not a web view — the session cookie has to be the real one',
      },
      authorise: {
        name: 'The user signs in',
        does: 'and the authorisation server redirects back',
      },
      redirect: {
        name: 'The device routes the redirect',
        does: 'to whichever app claims that address',
      },
      receive: {
        name: 'The app reads the callback',
        does: 'off the URL, which is written to logs and history',
      },
      exchange: {
        name: 'The app exchanges it',
        does: 'for a session, over TLS, from the app itself',
      },
      reuse: {
        name: 'Somebody presents it again',
        does: 'the same value, a second time',
      },
      session: {
        name: 'The session lands in the keychain',
        does: 'and the user is in',
      },
    },
    attacks: {
      'scheme-hijack': {
        name: 'Scheme hijack',
        text: 'any other app on the device can register tradx:// and receive the redirect instead',
      },
      'token-in-logs': {
        name: 'Token in the logs',
        text: 'an access token on a query string is written to system logs, browser history and the referrer',
      },
      'code-replay': {
        name: 'Code replay',
        text: 'a code that is accepted twice is an access token with extra steps',
      },
      'code-interception': {
        name: 'Code interception',
        text: 'without PKCE the exchange proves nothing about who started the flow, so whoever holds the code can spend it',
      },
      csrf: {
        name: 'Forged callback',
        text: 'without an unguessable state value the app accepts a sign-in the user never started',
      },
    },
    hints: {
      open: 'This is the version in the tutorials, and it loses on the channel before it loses on the payload: the redirect goes to whichever app claimed the scheme, and the token is in a log by the time you read it.',
      halfway: 'This is the trap. Swapping the token for a code is the fix everybody reaches for first, and on its own it makes things worse — it closes the logging hole and opens two new ones. A code needs PKCE so only the app that started the flow can spend it, and single use so it cannot be spent twice. Half the migration is worse than none of it.',
      safe: 'A Universal Link the domain vouches for, a one-time code instead of a token, PKCE so only the app that started the flow can exchange it, single use so it cannot be replayed, and a state value so a callback nobody started is refused. Five switches, and every one of them is closing a different door.',
    },
  },
  pulse: {
    lede: 'Un minuto de un feed de precios, reproducido. Elige cómo se entera el cliente — preguntar con un temporizador, o que le avisen — y luego mira los dos números: lo que hace el mercado, y lo que el lector está mirando de verdad.',
    transportLabel: 'Transporte',
    socket: 'WebSocket',
    polling: 'Polling',
    intervalLabel: 'Cada',
    intervals: { '1000': '1s', '5000': '5s', '30000': '30s' },
    truthLabel: 'El mercado',
    screenLabel: 'En pantalla',
    requestsLabel: 'Peticiones',
    bytesLabel: 'Bytes por minuto',
    seenLabel: 'Ticks vistos',
    behindLabel: 'Desactualizada',
    play: 'Reproducir el minuto',
    replay: 'Reproducir otra vez',
    hints: {
      socket: 'Una conexión, {bytes} en todo el minuto, y llegaron los {emitted} ticks. La pantalla mostró un precio ya superado el {behind} del tiempo — el vuelo en sí, y nada más.',
      fast: '{requests} peticiones y {bytes}, es decir {ratio}× lo que gastó el socket — y aun así se perdió {missed} de los {emitted} ticks. Preguntar más rápido no arregla el polling: compra un hueco menor a un precio mayor, y el hueco nunca se cierra.',
      poll: '{requests} peticiones trajeron {seen} de los {emitted} ticks. Los otros {missed} ocurrieron entre dos preguntas y nadie los vio jamás. La pantalla estuvo desactualizada el {behind} del minuto, por {stale} de media.',
      slow: 'Más barato que el socket, y con razón: {bytes} contra {socketBytes}. Preguntando menos de una vez cada {breakEven}, el polling es de verdad el transporte más barato. Este también vio {seen} de {emitted} ticks y estuvo equivocado el {behind} del tiempo — barato, y no es un precio en vivo.',
    },
  },
  service: {
    lede: 'Una tabla de lecturas de sensor, 240.000 filas. Elige una consulta, decide qué columnas llevan índice, y ejecútala. La franja de abajo es la tabla; fíjate en cuánta tiene que tocar la base de datos.',
    table: 'readings · 240.000 filas',
    indexes: 'CREATE INDEX ON',
    query: 'Consulta',
    run: 'Ejecutar',
    running: 'Ejecutando…',
    rows: 'Filas leídas',
    time: 'Tiempo de consulta',
    speedup: 'vs recorrido completo',
    writes: 'Coste de escritura',
    queryLabels: {
      point: 'una fila por id',
      selective: 'un sensor · 5%',
      broad: 'casi toda la tabla · 60%',
    },
    hints: {
      'no-index': 'No hay índice en esa columna, así que la base no tiene opción. Abre la tabla por la primera fila y lee las 240.000 para asegurarse de no dejarse ninguna.',
      'index-used': 'El índice fue directo — dieciocho pasos árbol abajo, y luego las filas. Misma consulta, mismos datos, misma máquina.',
      'not-selective': 'El índice existe, y el planificador se negó a usarlo. Esta consulta quiere el 60% de la tabla, y andar saltando por un índice para eso cuesta más que leerlo todo en orden. Crearlo no te dio nada aquí — y aun así ralentiza cada escritura.',
    },
    treeLabel: 'índice · árbol B',
    heapLabel: 'tabla',
  },
  copper: {
    lede: 'Esto no es una ilustración. Es AGROM.brd, la placa que enruté en 2017 para la sonda de suelo — 70 mm de diámetro, dos capas de cobre, 54 componentes — leída directamente del archivo de EAGLE y dibujada aquí. Elige una net y síguela.',
    viewLabel: 'Vista',
    layersLabel: 'Capas',
    view2d: 'Plana',
    view3d: 'Apilada',
    viewSolid: 'Montada',
    flip: 'Dar la vuelta',
    componentsWord: 'componentes',
    underneathWord: 'debajo',
    hintSolid: 'La misma placa con sus componentes, construida a partir del archivo IDF que EAGLE exportó al CAD mecánico en 2017 — cada footprint, posición, rotación y cara sale de ahí. Diecinueve de las 59 piezas van montadas debajo. Dale la vuelta y las encuentras.',
    explode: 'Separación',
    spin: 'arrastra para girar',
    hintStack: 'Es la misma placa, vista de canto. Dos láminas de cobre con 1,6 mm de fibra de vidrio entre ellas, y 34 postes metalizados cosiéndolas. Cada poste amarillo es una vía — la única forma de que una señal pase de una cara a la otra.',
    both: 'Ambas',
    topOnly: 'Solo la de arriba',
    bottomOnly: 'Solo la de abajo',
    netsLabel: 'Nets',
    allNets: 'Todas',
    segments: 'Segmentos',
    crossings: 'Cambios de capa',
    length: 'Longitud de cobre',
    legendTop: 'cobre superior',
    legendBottom: 'cobre inferior',
    legendVia: 'vía',
    hintIdle: 'El rojo corre por la cara superior, el azul por la inferior. Cada anillo amarillo es una vía: un agujero metalizado por donde la pista baja al otro lado.',
    hintCrossings: 'La net {net} cambia de capa {n} veces. Cambia a una sola capa y mírala partirse en trozos — esos huecos son donde va por la cara que acabas de ocultar.',
    hintFlat: 'La net {net} nunca sale de su capa. Nada se le puso delante, así que nunca tuvo que bajar.',
    hintOneLayer: 'Media placa ha desaparecido. Todo lo que falta va por la otra cara — y lo único que lo hace posible es que ambas caras están cosidas por vías.',
  },
  steel: {
    lede: 'Los ensamblajes en que está organizado el proyecto mecánico, una carpeta cada uno, reconstruidos a partir de los planos con los que se mecanizaron. Elige uno, desármalo y lee de qué está hecho.',
    productLabel: 'Producto',
    explode: 'Vista explosionada',
    zoom: 'Zoom',
    reset: 'Restablecer vista',
    loading: 'cargando las piezas impresas…',
    spin: 'arrastra para girar',
    autoSpin: 'Girar',
    pieces: 'Piezas',
    span: 'Dimensión mayor',
    provenance: 'Las piezas torneadas y cortadas se construyen desde sus planos acotados. Las impresas son sus STL reales. La disposición se ajustó a los renders de 2017, porque los ensamblajes de SolidWorks no se pueden leer.',
    processTitle: 'La prueba está en la estructura de carpetas',
    processLede: 'El proyecto mecánico no está archivado por pieza. Está archivado por cómo se fabrica cada una — que es la diferencia entre modelar algo y especificarlo.',
    processes: [
      { label: 'Torno y mecanizado', count: 11, note: 'cada una con plano acotado' },
      { label: 'Corte láser', count: 5, note: 'acrílico plano, dibujado y tolerado' },
      { label: 'Impresión 3D', count: 7, note: 'las piezas cargadas aquí como STL' },
      { label: 'Compra', count: 14, note: 'sensores, celdas, conectores' },
      { label: 'Montaje de cables', count: 1, note: 'un mazo de cuatro vías' },
    ],
    drawings: '16 planos acotados · 82 líneas en 7 listas de materiales',
    products: {
      'station': { name: 'Estación meteorológica completa', kind: 'la estación completa', blurb: 'Todos los ensamblajes de abajo, donde el render de 2017 los coloca.' },
      'cabeca-os': { name: 'Cabeza 1 · Solo suelo', kind: 'cabezal solo-suelo', blurb: 'El collar mecanizado, la columna y la tapa impresas, acrílico cortado por láser, y dos celdas fotovoltaicas.' },
      'cabeca-ws': { name: 'Cabeza 2 · Estación meteorológica', kind: 'cabezal de estación', blurb: 'El mismo cabezal, con un sensor UV y un TIL-78 donde iban las celdas.' },
      'corpo': { name: 'Mástil', kind: 'el mástil', blurb: 'Un cono, cuatro acoples, seis separadores y el tubo de un metro. Los separadores fijan las profundidades de los sensores enterrados.' },
      'painel': { name: 'Panel solar', kind: 'conjunto solar', blurb: 'Dos paneles en dos soportes mecanizados.' },
      'pcb': { name: 'PCB', kind: 'la placa, en el modelo mecánico', blurb: 'El laminado y las dos caras pobladas — la misma exportación IDF con la que el capítulo 02 monta su placa.' },
      'air': { name: 'Sensor 0 · AIR', kind: 'unidad de superficie', blurb: 'La varilla, su asiento mecanizado, y la cuna de batería impresa con su tapa.' },
      'thd': { name: 'Sensor 1 · THD', kind: 'sensor de suelo enterrado', blurb: 'Cuerpo mecanizado estriado bajo tapa de acrílico cortada por láser, encapsulado en epoxi, con latiguillo M12.' },
      'gas': { name: 'Sensor 5 · GAS STATION', kind: 'banco de sensores de gas', blurb: 'MQ-2, MQ-7 y MQ-8 con un barómetro, en un soporte impreso bajo tapa ventilada.' },
    },
  },
  glass: {
    lede: 'Una tarjeta, dos builds. A la izquierda la tarjeta tal como sale del diseño: una fila, cada texto en una línea, una altura en puntos. A la derecha la misma tarjeta construida para sobrevivir. Enciende las condiciones y mira cuál sigue siendo legible — el tamaño de letra que la persona realmente eligió, una vista dividida estrecha, una traducción más larga, un idioma de derecha a izquierda, una imagen que nunca llegó, un error sin sitio donde aparecer.',
    dynamicType: 'Dynamic Type',
    width: 'Ancho disponible',
    conditions: 'Condiciones',
    longString: 'Traducción más larga',
    rtl: 'Derecha a izquierda',
    noImage: 'La imagen no llegó',
    reset: 'Reiniciar',
    errorText: 'No pudimos contactar con el bróker. Tus posiciones están a salvo.',
    stateLabel: 'Estado de la vista',
    states: {
      loading: 'Cargando',
      empty: 'Vacío',
      error: 'Error',
      content: 'Contenido',
    },
    emptyTitle: 'Ninguna posición abierta',
    emptyBody: 'Cuando abras una aparecerá aquí, con su resultado.',
    emptyCta: 'Ver mercados',
    errorTitle: 'No se pudieron cargar tus posiciones',
    errorCta: 'Reintentar',
    variants: {
      fixed: 'Hecho al diseño',
      adaptive: 'Hecho para sobrevivir',
    },
    failures: {
      none: 'nada roto',
      'title-truncated': 'el título se corta con puntos suspensivos',
      'value-collides': 'el número se mete en el título',
      'subtitle-clipped': 'el subtítulo se corta',
      'mirrored-wrong': 'la flecha sigue apuntando al lado equivocado y el número está en el lado equivocado',
      'image-hole': 'un cuadrado vacío de cuarenta puntos donde la imagen nunca llegó',
      'error-hidden': 'el error no tiene dónde ir y se corta hasta desaparecer',
      'target-too-small': 'la fila está por debajo del mínimo de cuarenta y cuatro puntos',
      'no-skeleton': 'la misma tarjeta con los textos vacíos, que parece un bug y no una carga',
      'no-empty-state': 'una tarjeta en blanco con una flecha que no lleva a ninguna parte',
    },
    swift: '// The whole fix is three decisions.\nHStack(alignment: .firstTextBaseline, spacing: 12) {\n  if let image { Thumbnail(image) }        // no image, no box\n  VStack(alignment: .leading, spacing: 2) {\n    Text(position.symbol)\n      .font(.headline)\n      .lineLimit(nil)                      // let it wrap\n    if let error { Text(error).foregroundStyle(.red) }\n    else { Text(position.summary).font(.subheadline) }\n  }\n  Spacer(minLength: 12)\n  Text(position.pnl, format: .currency(code: code))\n    .monospacedDigit()\n}\n.padding(.horizontal, 16).padding(.vertical, 12)\n.frame(minHeight: 44)                      // grows, never clips\n.dynamicTypeSize(...DynamicTypeSize.accessibility5)\n.accessibilityElement(children: .combine)\n.accessibilityLabel(position.spokenLabel)',
    dart: '// Same three decisions, same order.\nRow(\n  crossAxisAlignment: CrossAxisAlignment.start,\n  children: [\n    if (image != null) Thumbnail(image!),\n    const SizedBox(width: 12),\n    Expanded(                              // min-width: 0, in Flutter\n      child: Column(\n        crossAxisAlignment: CrossAxisAlignment.start,\n        children: [\n          Text(p.symbol, style: t.titleMedium, softWrap: true),\n          error != null\n            ? Text(error!, style: t.bodySmall!.copyWith(color: cs.error))\n            : Text(p.summary, style: t.bodySmall),\n        ],\n      ),\n    ),\n    const SizedBox(width: 12),\n    Text(p.pnl, style: t.titleMedium),\n  ],\n)\n// Directionality mirrors the row; Semantics gives it one spoken label.',
  },
  flow: {
    shotAlt: 'El editor de estrategias de Tradx: un gráfico de velas de PETR4 sobre un grafo de nodos que conecta una media móvil y un RSI a dos entradas a mercado.',
    shotCap: 'Tradx · el editor de estrategias. Siete nodos, siete conexiones, y un backtest corriendo sobre PETR4 en el gráfico de quince minutos.',
    teamLine: 'Dos personas, pull requests, y revisiones que ninguno se salta.',
    lede: 'Esto es lo que hace Tradx, en miniatura. No escribes el bucle — cableas la lógica, y el motor la ejecuta sobre las velas. Mueve los parámetros y mira cómo cambian a la vez el grafo y las operaciones.',
    period: 'Periodo del RSI',
    buyLevel: 'Entrar por encima de',
    sellLevel: 'Salir por debajo de',
    run: 'Ejecutar',
    inSample: 'Ajusta en esta mitad',
    outSample: 'La mitad que nunca viste',
    trades: 'Operaciones',
    returnPct: 'Rentabilidad',
    winRate: 'Aciertos',
    nodes: {
      source: 'Datos de mercado', rsi: 'Indicador RSI', crossUp: 'Cruce al alza',
      crossDown: 'Cruce a la baja', entry: 'Entrada', exit: 'Salida',
    },
    hintIn: 'Ajústalo hasta que el número sea bonito. Esa es la parte fácil, y es lo que te enseña cualquier captura de backtest de internet.',
    hintOut: 'Mismo grafo, mismos parámetros, un tramo de mercado al que nunca se ajustó.',
    reveal: 'Entre las 75.429 combinaciones de parámetros, el conjunto que más rindió en la mitad donde ajustaste quedó en el puesto 22.949 en la mitad que no viste. Del primer puesto al vigésimo segundo milésimo. Por eso un backtest es una hipótesis y no un resultado, y por eso el número bonito es la parte fácil.',
  },
  field: {
    lede: 'Un objeto, construido dos veces. A un lado del interruptor es la malla con la que se imprimió la pieza. Al otro es un campo de gaussianas sobre esa misma malla — repartidas aquí en vez de ajustadas, para que los dos queden lado a lado y la diferencia sea el método y nada más.',
    mesh: 'Malla', splats: 'Gaussianas',
    count: 'Gaussianas', size: 'Dispersión', spin: 'arrastra para girar',
    primitives: 'Primitivas', authored: 'Hechas a mano',
    authoredMesh: 'cada triángulo', authoredSplat: 'ninguna',
    hintMesh: '997 triángulos, cada uno colocado por alguien en SolidWorks en 2017.',
    hintSplats: 'Nadie colocó estas. En una reconstrucción real empiezan como ruido y son movidas, estiradas y recoloreadas por descenso de gradiente hasta que el render deja de contradecir a las fotografías — por eso la cuenta llega a cientos de miles sin que a nadie le importe.',
    loading: 'cargando la malla…',
  },
  ui: {
    hardwareCta: 'Jugar los capítulos de hardware',
    duty: 'Ciclo de trabajo',
    brightness: 'Brillo percibido',
    frequency: 'Frecuencia',
    play: 'Ejecutar',
    pause: 'Pausar',
    reset: 'Reiniciar',
    subscribe: 'Suscribir',
    publish: 'Publicar',
    matched: 'entregado',
    dropped: 'no entregado',
    replicas: 'Réplicas',
    traffic: 'Tráfico entrante',
    latency: 'Latencia p99',
    dropped_req: 'Peticiones perdidas',
    cost: 'Coste',
    train: 'Entrenar',
    epoch: 'Época',
    accuracy: 'Precisión',
    wip: 'Interactividad en construcción',
    wipNote: 'El layout es el definitivo; este panel se está cableando.',
    learned: 'Lo que acabas de aprender',
  },
};
