import type { Content } from './types';

export const pt: Content = {
  meta: {
    title: 'Maykon Meneghel — o currículo jogável',
    description:
      'Engenheiro full-stack sênior com mestrado e pós em IA. Firmware, PCBs, CAD, MQTT, Kubernetes, Swift e Flutter — explicados em mini-jogos que você joga na própria página.',
  },
  nav: { chapters: 'Capítulos', family: 'A família', contact: 'Contato', resume: 'Currículo' },
  hero: {
    kicker: 'Engenheiro Mobile Sênior · iOS e Flutter · e as APIs por trás',
    name: 'Maykon Meneghel',
    headline: 'Eu entrego o app e a API com que ele conversa.',
    sub: 'A maioria dos currículos conta o que alguém sabe fazer. Este aqui deixa você experimentar. Cada capítulo é um mini-jogo que funciona: escreva a mesma tela duas vezes, em SwiftUI e em Flutter, planeje uma query, escale um serviço sob carga e veja uma ordem virar um trade — sem sair desta página.',
    proof: [
      'Tradx · publicado na Mac App Store',
      'De trainee a sênior em quatro anos num projeto Apple em produção',
      'Clean Architecture para SwiftUI · 30★ no GitHub',
      'Apple Developer Academy · pós em desenvolvimento iOS',
    ],
    links: [
      { label: 'LinkedIn', href: 'https://www.linkedin.com/in/maykonmeneghel/' },
      { label: 'GitHub', href: 'https://github.com/maykonmeneghel' },
      { label: 'Tradx na App Store', href: 'https://apps.apple.com/us/app/tradx/id6743033919' },
    ],
    cv: 'Baixar CV (PDF)',
    cta: 'Começar o tour',
    scrollHint: 'role',
    boot: [
      'meneghel.me boot v2.0',
      'carregando plataformas . ios 17 · android 14 · swift 6 · dart 3',
      'montando frameworks .... swiftui · uikit · flutter · jetpack compose',
      'subindo serviços ....... node · nestjs · java · docker · kubernetes',
      'carregando inteligência  pytorch · gan · gaussian splatting',
      'pronto.',
    ],
  },
  acts: [
    {
      before: 'glass',
      label: 'Ato um',
      title: 'A tela',
      lede: 'Sete anos entregando app, nativo e cross-platform. Dois anos na Apple Developer Academy, quatro num projeto Apple em produção que me levou de trainee a sênior, e um cliente de trading para desktop meu, publicado na Mac App Store. É esta a parte da pilha pela qual eu sou contratado.',
    },
    {
      before: 'service',
      label: 'Ato dois',
      title: 'Com o que o app conversa',
      lede: 'Um app vale o que responde a ele. Estes quatro capítulos são a outra metade do mesmo trabalho — a API, o banco que ela lê, o cluster onde ela roda, e um motor de trading onde a ordem que o app manda não é o trade que volta.',
    },
    {
      before: 'mind',
      label: 'Ato três',
      title: 'E os modelos por baixo',
      lede: 'Onde a pós em IA deixa de ser linha num diploma: uma GAN escrita do zero, e o trabalho de Gaussian Splatting que eu faço hoje.',
    },
  ],
  hardwarePage: {
    title: 'Maykon Meneghel — os anos de hardware',
    description: 'Antes dos apps: uma sonda de solo projetada, roteada, usinada e enfiada na terra. Firmware, PCB, CAD e MQTT, tudo jogável.',
    back: 'Voltar para o portfólio',
    kicker: 'O plus',
    heading: 'Antes dos apps, eu fiz a coisa que manda o dado',
    lede: 'Estes quatro capítulos abriam o site, e são o motivo de as pessoas saírem daqui me chamando de engenheiro de IoT. Continuam aqui porque uma sonda de solo projetada, roteada, usinada e enterrada não é uma coisa comum de um engenheiro mobile ter feito — e porque saber quanto custa um pacote antes de ele chegar no seu app muda o jeito de construir o app.',
    outro: 'Foi ali que começou. O que isso virou está na outra página.',
    backCta: 'Ver o que eu construo hoje',
  },
  chapters: [
    {
      track: 'mobile', codename: 'THREAD', slug: 'thread',
      era: 'iOS e Flutter · 2019 → hoje',
      title: 'O frame tem dezesseis milissegundos',
      lede: 'Toda discussão de concorrência num time mobile é, no fundo, sobre um número só. Uma tela deve um frame a cada 16,7 ms, e tudo — async/await, actors, isolates, cancelamento — é sobre o que você pode fazer dentro dele. Abaixo está a mesma lista carregada de três jeitos, com o gráfico de frames que um profiler mostraria.',
      panel: 'instruments · frame timing',
      takeaway: 'O botão do meio é o capítulo inteiro. <b>await suspende uma função, não move ela</b> — a continuação retoma no main actor e o trabalho caro ainda cai dentro de um frame. Código assíncrono que nunca sai da main thread é o bug de performance mais comum em mobile, e é invisível até alguém abrir um profiler.',
      stack: ['Swift Concurrency', 'async/await', 'actors', '@MainActor', 'Combine', 'Isolates', 'compute()', 'Instruments', 'Cancelamento de Task', '60 fps'],
    },
    {
      track: 'mobile', codename: 'VIDRO', slug: 'glass',
      era: 'Swift e Flutter · 2019 → hoje',
      title: 'O card que sobrevive ao mundo real',
      lede: 'Qualquer um constrói o card do layout. O trabalho é construir o que continua legível quando a pessoa que segura o celular colocou a fonte no maior tamanho de acessibilidade, está em tela dividida, num idioma cujas palavras são mais longas, lendo da direita para a esquerda, numa conexão que nunca entregou a imagem. O designer te entrega um estado. Você entrega seis.',
      panel: 'PositionRow.swift / position_row.dart',
      takeaway: 'O layout desenhado no comp sobrevive a uma das sete condições aqui embaixo — justamente aquela para a qual ele foi desenhado. <b>A diferença não é gosto, é qual pergunta o layout faz</b>: não "a fonte está grande?" e sim "isso cabe?". Faça a segunda pergunta e uma tradução mais longa deixa de virar um chamado de bug.',
      stack: ['SwiftUI', 'UIKit', 'Flutter', 'Dynamic Type', 'VoiceOver', 'Localização', 'RTL', 'Layout adaptativo', 'Acessibilidade', 'Design systems'],
    },
    {
      track: 'platform', codename: 'SERVIÇO', slug: 'service',
      era: 'Backend · 2018 → hoje',
      title: 'Alguém precisa lembrar de tudo isso',
      lede: 'Mensagens são efêmeras; o negócio não é. Atrás de cada dispositivo existe uma API e um banco, e a diferença entre um produto rápido e um lento costuma ser uma decisão tomada aqui.',
      panel: 'psql · meneghel_db',
      takeaway: 'Sem índice, o banco lê <b>todas as linhas</b> para te responder. Com um, ele salta direto ao ponto. Mesma query, mesmos dados, mesmo servidor — mil vezes mais rápido.',
      stack: ['Node.js', 'Express', 'Restify', 'MongoDB', 'PostgreSQL', 'REST'],
    },
    {
      track: 'platform', codename: 'ENXAME', slug: 'swarm',
      era: 'Backend · 2018 → hoje',
      title: 'Uma máquina nunca é suficiente',
      lede: 'Tráfego não chega educadamente. Ele chega todo de uma vez, às 3 da manhã, no dia do lançamento. Containers e Kubernetes são como você responde a isso sem acordar.',
      panel: 'kubectl · production',
      takeaway: 'Você não deixou o código mais rápido — você fez <b>mais cópias dele</b>. Escala horizontal troca dinheiro por latência, e um autoscaler faz essa troca por você, sozinho.',
      stack: ['Docker', 'Kubernetes', 'HPA', 'Load balancing', 'CI/CD'],
    },
    {
      track: 'platform', codename: 'FLUXO', slug: 'flow',
      era: 'Tradx · 2022 → hoje',
      title: 'E então eu construí a ferramenta',
      lede: 'Uma previsão precisa morar em algum lugar. A minha mora no Tradx — a empresa que eu cofundei em 2022 e toco como COO, uma mesa onde uma estratégia é um grafo que você liga, não um código que você escreve.',
      panel: 'tradx · grafo de estratégia',
      takeaway: 'Um backtest é uma <b>hipótese</b>, não um resultado. Qualquer um ajusta uma curva até ela ficar bonita nos dados que já tem; o ofício inteiro é saber quanto aquele número vale nos dados que ele não tem.',
      stack: ['Node.js', 'NestJS', 'Flutter', 'MongoDB', 'Redis + BullMQ', 'Motor de backtest', 'Paper trading'],
    },
    {
      track: 'platform', codename: 'LIVRO', slug: 'ledger',
      era: 'Tradx · 2022 → hoje',
      title: 'Uma ordem não é um trade',
      lede: 'O capítulo anterior produziu um sinal. Este é o que acontece com ele. Uma estratégia emite ordens; um motor decide quais delas viram trades, e a distância entre esses dois números é onde uma mesa de operações é de fato construída ou perdida.',
      panel: 'tradx · motor de execução',
      takeaway: 'O motor recusou trinta e oito ordens e relatou um problema de fundos. Ele não tinha um. <b>Vender contra uma posição comprada libera poder de compra</b> — um motor que checa a ordem em vez da exposição resultante vai bloquear justamente os trades que reduzem risco e chamar isso de prudência.',
      stack: ['NestJS', 'Ciclo de vida da ordem', 'Netting de posição', 'Idempotência', 'Redis + BullMQ', 'Paper trading'],
    },
    {
      track: 'ai', codename: 'MENTE', slug: 'mind',
      era: 'StockGAN · 2021',
      title: 'Ensine a máquina a adivinhar o que vem depois',
      lede: 'Em 2021 eu construí do zero uma rede adversária generativa para séries temporais — o trabalho em que a minha pós em IA e o mestrado em Bioengenharia deixam de ser linhas num diploma — duas redes, uma tentando inventar a próxima leitura e outra tentando pegá-la mentindo. Eu treinei em dados financeiros. Ela roda aqui na sonda de solo dos capítulos acima, sem mudar nada, porque uma série temporal não sabe o que ela mede.',
      panel: 'gan_model.py — train_step()',
      takeaway: 'Dois modelos, uma função de perda e um botão entre eles. Cobre do previsor que ele fique perto e ele responde com a média de tudo, que é segura e inútil. Cobre que ele seja crível e ele responde com algo que anda como o sensor e não sabe de nada. <b>Todo modelo que eu entrego é essa troca feita de propósito</b>, escrita e medida.',
      stack: ['TensorFlow / Keras', 'GANs', 'LSTM', 'Séries temporais', 'Seleção de features com PCA e XGBoost'],
    },
    {
      track: 'ai', codename: 'CAMPO', slug: 'field',
      era: 'Gaussian splatting · hoje',
      title: 'E agora o objeto é feito de luz',
      lede: 'É nisso que eu passo os dias agora: Gaussian Splatting. Uma cena deixa de ser uma superfície que alguém modelou e vira uma nuvem de gaussianas orientadas, ajustadas por gradiente descendente até que renders delas batam com as fotografias. Reconstruções de verdade começam com uma câmera andando pela sala. A demo aqui embaixo de propósito não faz isso — ela usa uma peça que você já conheceu no capítulo 03, porque o único jeito de ver o que o método muda é ver o mesmo objeto construído dos dois jeitos.',
      panel: 'gaussian splatting · viewer',
      takeaway: 'Uma malha diz onde estão as <b>superfícies</b>, e um engenheiro desenhou cada uma. Um campo de splats diz onde está a <b>luz</b>, e ninguém desenhou nada — ele foi ajustado até o render parar de discordar da fotografia.',
      stack: ['Gaussian Splatting', '3DGS', 'PyTorch', 'CUDA', 'Fotogrametria', 'Campos de radiância'],
    },


    {
      track: 'hardware', codename: 'SILÍCIO', slug: 'silicon',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Tudo começa em um único pino',
      lede: 'Muito antes de existir um app, existe um microcontrolador decidindo — milhões de vezes por segundo — se um fio está em nível alto ou baixo. Quatorze firmwares me ensinaram que tudo o que vem acima depende de acertar isto aqui.',
      panel: 'pwm_playground.c',
      takeaway: 'Você acabou de reduzir o brilho de um LED sem nunca mudar a tensão dele. Isso é <b>PWM</b>: o pino só fica totalmente ligado ou totalmente desligado — ele apenas chaveia mais rápido do que o seu olho consegue acompanhar.',
      stack: ['C/C++', 'ESP32', 'PIC18F4550', 'ATmega', 'Timers e PWM'],
    },
    {
      track: 'hardware', codename: 'COBRE', slug: 'copper',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Depois, ele precisa de uma placa',
      lede: 'Um esquemático é uma promessa. A PCB é onde ela é cumprida. Toda placa que fabriquei começou exatamente neste quebra-cabeça: levar cada sinal ao seu lugar, numa superfície onde nada pode se cruzar.',
      panel: 'router.pcb',
      takeaway: 'Duas trilhas não podem se cruzar na mesma camada. É essa única restrição que faz placas reais terem 2, 4, às vezes 12 camadas empilhadas.',
      stack: ['Altium', 'EAGLE', 'SMD e THT', 'Gerber', 'Design para manufatura'],
    },
    {
      track: 'hardware', codename: 'AÇO', slug: 'steel',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'E um corpo para sobreviver ao campo',
      lede: 'Um sensor enterrado em solo encharcado por dois anos não liga para a elegância do seu firmware. Ele liga para o encapsulamento. Por isso eu mesmo modelo cada peça, cada tolerância, cada vedação.',
      panel: 'soil_probe.sldasm',
      takeaway: 'Hardware é a única camada que você não corrige remotamente. É por isso que o projeto mecânico acontece <b>antes</b> da primeira linha de firmware, não depois.',
      stack: ['SolidWorks', 'Modelagem 3D', 'Tolerâncias', 'Vedação IP', 'Impressão 3D'],
    },
    {
      track: 'hardware', codename: 'SINAL', slug: 'signal',
      era: 'AGROM.IO · 2016 – 2019',
      title: 'Agora faça mil deles conversarem',
      lede: 'Um dispositivo é um projeto. Mil dispositivos é uma arquitetura. MQTT é como eles se falam sem nunca se conhecerem — e os curingas de tópico são o truque inteiro.',
      panel: 'broker · mqtt://meneghel.me:8883',
      takeaway: '<b>+</b> casa exatamente um nível. <b>#</b> casa tudo abaixo dele. Essa única regra é como um só broker distribui para milhares de dispositivos sem que nenhum deles guarde a lista dos outros.',
      stack: ['MQTT', 'Mosquitto', 'AWS IoT Core', 'QoS 0/1/2', 'Pub/Sub'],
    },
  ],
  record: {
    eyebrow: '12 · TRAJETÓRIA',
    title: 'As provas',
    lede: 'Nove capítulos de demonstração. Este aqui é só evidência. Arraste pelos anos e veja o que estava rodando ao mesmo tempo — porque a manchete honesta desta linha do tempo não é nenhum emprego específico, é o quão raramente houve só um.',
    lanes: {
      education: 'Formação',
      research: 'Pesquisa',
      industry: 'Indústria',
      venture: 'Empreendimentos',
    },
    roles: {
      grad: 'Eng. de Controle e Automação',
      msc: 'Mestrado em Bioengenharia',
      academy: 'Pós-graduação lato sensu, Desenvolvimento iOS',
      aiSpec: 'Especialização em Inteligência Artificial Aplicada',
      pucLab: 'Estagiário, Laboratório de Automação e Sistemas',
      araucaria: 'Engenheiro de Software — pesquisa aplicada, IA e saúde embarcada',
      freelance: 'Desenvolvedor de Software, autônomo',
      residency: 'Trainee · Apple Residency',
      junior: 'Desenvolvedor Júnior · Projeto Apple',
      techLead: 'Tech Lead · Apple Internship',
      fullstack: 'Desenvolvedor Full Stack · Projeto Apple',
      senior: 'Desenvolvedor Sênior · Projeto Apple',
      ghel: 'Technology Advisor · Projeto Renault',
      holding: 'Conselheiro Administrativo — a holding da família',
      tradx: 'COO e Cofundador',
    },
    scrubber: {
      simultaneous: '{n} funções ao mesmo tempo',
      one: '1 função',
      none: 'nada registrado ainda',
      today: 'hoje',
      drag: 'arraste o ano',
    },
    ventures: {
      title: 'Seis empresas',
      lede: 'Fundadas ou cofundadas. Algumas cresceram, outras não — que é exatamente o motivo de fundar seis.',
      founder: 'Fundador',
      coFounder: 'Cofundador',
      sectors: { fintech: 'fintech', agritech: 'agritech', smartHome: 'casa inteligente', proptech: 'proptech', edtech: 'edtech' },
    },
    publications: {
      title: 'Publicado e premiado',
      lede: 'Trabalho revisado por pares, quase todo na costura entre engenharia e saúde.',
      read: 'ler o artigo',
      code: 'código',
      items: {
        soilInstrument: 'Instrumento para Medição de Fatores e/ou Elementos Naturais do Solo',
        fesTool: 'A Tool to Select FES Parameters for chronic SCI',
        fallDetector: 'Indoors Wi-Fi Fall Detector Buckle for the Elderly',
        inSilicoFes: 'Aplicação, in silico, de estímulos elétricos em modelo neuromuscular compatível com lesão medular crônica',
        balanceModel: 'Modelagem matemática do sistema de manutenção do equilíbrio por técnicas de identificação de sistemas',
        stockGan: 'Previsão de Séries Financeiras com Redes Generativas Adversárias',
      },
    },
    press: {
      title: 'Na imprensa',
      items: {
        hubli: 'Hubli, criado na Apple Developer Academy, destacado pela Apple',
        neonWave: 'Neon Wave, jogo de iOS que saiu no MacMagazine',
      },
    },
    closing: {
      line: 'Full stack sênior, do ponto de solda ao modelo em produção — no agro e no mercado financeiro.',
      note: 'A placa, o firmware, o broker, o banco, o cluster, o modelo e a tela do celular. Ainda não conheci a outra pessoa que faz as duas pontas dos dois.',
    },
    contact: {
      title: 'Fale comigo',
      lede: 'Se alguma coisa aqui tem a cara de um problema que você tem, eu quero ouvir. E-mail ou LinkedIn, o que preferir — o CV é um PDF de duas páginas e o código está no GitHub.',
      linkedin: 'Falar comigo no LinkedIn',
      github: 'Ver meu código',
      email: 'Me mandar um e-mail',
      cv: 'Baixar meu CV',
    },
    skills: {
      title: 'Com o que eu trabalho',
      lede: 'Tudo aqui embaixo é creditado por algum capítulo desta página ou está num repositório público. Nada aqui é aspiracional.',
      groups: {
        ios: 'iOS · Swift',
        cross: 'Multiplataforma',
        release: 'Publicação e release',
        languages: 'Linguagens',
        backend: 'Backend e APIs',
        data: 'Dados',
        cloud: 'Cloud e DevOps',
        frontend: 'Web',
        ai: 'IA e 3D',
        embedded: 'Embarcados e hardware',
        ways: 'Jeito de trabalhar',
      },
    },
  },
  signal: {
    levels: ['local', 'área', 'dispositivo', 'medida'],
    anatomyLede: 'Um tópico é um caminho. Todo dispositivo desta fazenda publica em um caminho montado com os mesmos quatro níveis — então uma assinatura é, no fundo, uma pergunta sobre quais níveis te interessam.',
    legendPlus: 'casa exatamente um nível, seja qual for o conteúdo',
    legendHash: 'casa tudo o que vier abaixo, e precisa ser o último nível',
    yourToken: 'você escreveu',
    noToken: '—',
    subLabel: 'Sua assinatura',
    placeholder: 'farm/greenhouse/#',
    broker: 'Broker — tudo o que está sendo publicado',
    inbox: 'Sua caixa — o que chegou até você',
    delivered: 'entregues',
    dropped: 'não entregues',
    missionsTitle: 'Três assinaturas para acertar',
    missionsLede: 'Vale qualquer filtro que selecione exatamente os tópicos certos. Cada missão tem mais de uma resposta correta.',
    missions: [
      { id: 'greenhouse', goal: 'Tudo o que a estufa publica — e nada além disso.' },
      { id: 'temps',      goal: 'Toda leitura de temperatura, venha de onde vier.' },
      { id: 'moisture',   goal: 'Toda leitura de umidade da fazenda, mas não a de casa.' },
    ],
    solved: 'resolvida',
    invalidHash: 'o # precisa ser o último nível, sozinho',
    invalidPlus: 'o + precisa ocupar um nível inteiro, sozinho',
    invalidEmpty: 'um nível do tópico não pode ficar vazio',
    emptyInbox: 'nada casou ainda',
    allSolved: 'As três. Você já entende filtros de tópico MQTT melhor que boa parte de quem usa isso todo dia.',
  },
  swarm: {
    lede: 'O tráfego deste serviço dispara a cada poucos segundos, como num dia de lançamento. Adicione réplicas e a latência cai; adicione demais e você paga por máquina ociosa. Depois entregue ao autoscaler e veja onde ele ainda perde.',
    traffic: 'Entrada',
    replicas: 'Réplicas',
    latency: 'Latência p99',
    dropped: 'Requisições perdidas',
    cost: 'Custo',
    saturation: 'Saturação',
    auto: 'Autoscaler',
    autoHint: 'Mirando 60% de saturação. Um pod novo leva cerca de 4s para ficar pronto — e é por isso que ainda caem requisições na subida.',
    manualHint: 'Você está escalando na mão. O pico chega estando você pronto ou não.',
    ready: 'prontos',
    starting: 'subindo',
    reset: 'Zerar contadores',
    spike: 'pico',
    healthy: 'saudável',
    strained: 'sob pressão',
    failing: 'perdendo tráfego',
    wasteful: 'superdimensionado',
  },
  mind: {
    lede: 'Em 2021 eu escrevi uma GAN que prevê o próximo valor de uma série temporal — gerador, discriminador e loop de treino do zero. Eu treinei em trinta anos de barras diárias, porque era ali que havia histórico limpo de graça, mas a rede lê log-retornos e não faz ideia do que os números medem. Então aqui ela está rodando na sonda de solo dos capítulos acima. A parte que vale mostrar é esta: o discriminador nunca julga uma leitura prevista sozinha. A leitura é colada nas nove reais que vieram antes, e a rede precisa dizer se a janela inteira saiu do sensor. É esse o jogo. Você é o discriminador.',
    paper: 'StockGAN · LSTM(128) · janela de 10 · treinada em 30 anos de barras diárias, rodando aqui no soil-1',
    reading: 'soil-1 · estufa · % de umidade',
    question: 'Uma destas duas janelas termina com uma leitura que a sonda realmente fez. A outra termina com uma que o gerador inventou. Qual é qual?',
    slotA: 'Janela A',
    slotB: 'Janela B',
    pick: 'Escolher',
    real: 'REAL',
    generated: 'GERADA',
    criticSays: 'o discriminador deu',
    next: 'Próxima janela',
    reset: 'Recomeçar',
    rounds: 'Rodadas',
    you: 'Você',
    network: 'O discriminador',
    fooled: 'Enganou o crítico',
    lambdaLabel: 'λ — quanto da nota do gerador vem de enganar o crítico em vez de acertar o número',
    lambdaHis: 'o que eu subi',
    meterTruth: 'Perto da verdade',
    meterReal: 'Anda como o sensor',
    arch: 'O que existe de fato no arquivo',
    archGen: 'gerador        LSTM(128, stateful) → Dropout(0.3) → Dense(n_features)',
    archDisc: 'discriminador  LSTM(128, stateful) → Dropout(0.1) → Dense(1, sigmoid)',
    archNote: 'RMSprop com decaimento polinomial de 2.5e-4 até 1e-4 ao longo de mil passos. Entropia cruzada com label smoothing em 0.2, para que o discriminador nunca tenha permissão de ter certeza absoluta de nada. Alvo real e alvo gerado multiplicados por ruído com σ = 0.25 durante o treino, para que ele não vença percebendo quais números são limpos demais. Doze indicadores — MACD, EMA, RSI, Bollinger, ROC, volatilidade — reduzidos por PCA e XGBoost antes de a rede ver qualquer coisa; numa sonda de solo esses mesmos doze viram médias móveis e taxa de variação da umidade, e é justamente esse o ponto: a arquitetura mudou de domínio e o pipeline de features quase não piscou. As funções de perda desta página são portes das reais, constantes incluídas; o gerador daqui é um substituto que reproduz o dilema sem carregar 128 unidades LSTM para dentro do seu navegador.',
    hintStart: 'Escolha uma. Nove leituras reais, e uma décima que é a sonda ou o meu gerador.',
    hintRight: 'Certo.',
    hintWrong: 'Errado — e olhe as duas notas embaixo. É o mesmo julgamento que a rede faz, na mesma janela.',
    hintLow: 'Aqui embaixo o gerador é avaliado quase só por erro quadrático, então ele responde com a média condicional: o palpite mais seguro possível. É a coisa mais precisa que ele consegue dizer e é obviamente falsa — o passo tem um terço do tamanho de um real. Todo previsor treinado só em MSE tem esse problema, e a maioria nunca descobre.',
    hintHigh: 'Aqui em cima ele é avaliado só por enganar o crítico. As leituras finalmente andam como o sensor anda, e os números estão mais longe da próxima hora do que nunca. Parece certo. Não está certo.',
    hintHis: '0.6 foi o que eu subi: pendendo para o crítico, e pagando cerca de dois décimos de ponto de erro por isso. Nenhum ajuste ganha nos dois medidores — que é exatamente por que esse número é uma decisão e não um padrão.',
    verdict: 'Você está em {you} nestas rodadas. A rede está em {net} nas mesmas janelas.',
  },
  thread: {
    lede: 'Uma tela deve um frame a cada 16,7 ms. Esta está carregando vinte e quatro linhas, e a única coisa que muda entre os três botões é onde o decode acontece. Olhe o gráfico de frames, não a lista.',
    pickLabel: 'Onde o trabalho roda',
    device: 'iPhone · 60 Hz',
    frozen: 'não responde',
    frameTimes: 'Tempo dos frames',
    budget: 'orçamento de 16,7 ms',
    onBudget: 'no orçamento',
    dropped: 'perdido',
    worst: 'Pior frame',
    droppedFrames: 'Frames perdidos',
    jank: 'Travamento',
    wasted: 'Desperdiçado após sair',
    leave: 'Sair da tela no frame 6',
    cancelOn: 'cancelar o trabalho',
    cancelOff: 'deixar terminar',
    strategies: {
      sync: {
        name: 'Na main thread',
        hint: 'Um frame que dura quase trezentos milissegundos. A lista não engasga — ela para, e o sistema operacional começa a considerar se o seu app ainda está vivo. Todo engenheiro mobile já subiu isso uma vez.',
        swift: '// Everything, right now, on the main actor.\n@MainActor\nfunc load(_ rows: [Row]) {\n  for row in rows {\n    let image = decode(row.data)   // blocks the frame\n    cache[row.id] = image\n  }\n}',
        dart: '// Everything, right now, on the UI isolate.\nvoid load(List<Row> rows) {\n  for (final row in rows) {\n    final image = decode(row.data);  // blocks the frame\n    cache[row.id] = image;\n  }\n}',
      },
      await: {
        name: 'await, ainda na main',
        hint: 'Esta é a que pega as pessoas. O congelamento sumiu e o travamento não: await suspende a função, não move ela. A continuação retoma no main actor e o decode acontece ali, então cada linha continua estourando o orçamento. Parece resolvido e não está.',
        swift: '// Awaited — and still on the main actor.\n@MainActor\nfunc load(_ rows: [Row]) async {\n  for row in rows {\n    let image = await decode(row.data)\n    cache[row.id] = image          // resumes here, on main\n  }\n}',
        dart: '// Awaited — and still on the UI isolate.\nFuture<void> load(List<Row> rows) async {\n  for (final row in rows) {\n    final image = await decode(row.data);\n    cache[row.id] = image;           // resumes here, on the UI isolate\n  }\n}',
      },
      offMain: {
        name: 'Fora do main actor',
        hint: 'Agora o decode pertence a um actor — ou a um isolate — e o frame só paga para receber a linha pronta. Nada é perdido, o pior frame cabe no orçamento, e a lista rola do jeito que deveria desde o começo.',
        swift: '// The decode belongs to something that is not the UI.\nactor Decoder {\n  func decode(_ data: Data) -> UIImage { ... }\n}\n\nfunc load(_ rows: [Row]) async {\n  await withTaskGroup(of: (Row.ID, UIImage).self) { group in\n    for row in rows {\n      group.addTask { (row.id, await decoder.decode(row.data)) }\n    }\n    for await (id, image) in group {\n      await MainActor.run { cache[id] = image }\n    }\n  }\n}',
        dart: '// compute() moves the work to another isolate.\nFuture<void> load(List<Row> rows) async {\n  await Future.wait(rows.map((row) async {\n    final image = await compute(decodeBytes, row.data);\n    cache[row.id] = image;\n  }));\n}',
      },
    },
  },
  ledger: {
    lede: 'Uma conta, um instrumento, vinte lotes por clique. Compre e venda na mão e veja o que cada ordem faz com os fundos disponíveis — depois troque a checagem de fundos e faça de novo.',
    modeLabel: 'Checagem de fundos',
    modeGross: 'Nocional da ordem',
    modeNet: 'Exposição líquida',
    price: 'Preço',
    position: 'Posição',
    equityLabel: 'Patrimônio',
    lockedLabel: 'Travado',
    availableLabel: 'Disponível',
    flat: 'zerada',
    buy: 'Comprar 20',
    sell: 'Vender 20',
    reset: 'Zerar',
    replay: 'Repetir a sessão',
    replayTitle: 'As mesmas quarenta ordens, dos dois jeitos',
    grossLabel: 'Checado contra a ordem',
    netLabel: 'Checado contra a exposição',
    hintStart: 'Comece com duas compras e depois tente vender para sair delas. Veja o que a venda faz com os fundos disponíveis em cada checagem.',
    hintAccepted: 'Executada — {side} {qty} a {price}.',
    hintFunds: 'Recusada. O motor quer {need} travados e a conta vale {have} — mesmo quando a ordem deixaria a posição menor.',
    hintReplay: '{filled} de {orders} ordens executadas\n{trips} idas e voltas\n{pnl} realizado',
  },
  service: {
    lede: 'Uma tabela de leituras de sensor, 240.000 linhas. Escolha uma consulta, decida quais colunas ganham índice, e rode. A faixa abaixo é a tabela; repare em quanto dela o banco precisa tocar.',
    table: 'readings · 240.000 linhas',
    indexes: 'CREATE INDEX ON',
    query: 'Consulta',
    run: 'Rodar',
    running: 'Rodando…',
    rows: 'Linhas lidas',
    time: 'Tempo da consulta',
    speedup: 'vs varredura completa',
    writes: 'Custo de escrita',
    queryLabels: {
      point: 'uma linha por id',
      selective: 'um sensor · 5%',
      broad: 'quase toda a tabela · 60%',
    },
    hints: {
      'no-index': 'Não existe índice nessa coluna, então o banco não tem escolha. Ele abre a tabela na primeira linha e lê todas as 240.000 para ter certeza de que não deixou nenhuma passar.',
      'index-used': 'O índice foi direto ao ponto — dezoito passos árvore abaixo, e então as linhas. Mesma consulta, mesmos dados, mesma máquina.',
      'not-selective': 'O índice existe, e o planner se recusou a usá-lo. Esta consulta quer 60% da tabela, e ficar pulando por um índice para isso custa mais do que ler tudo em ordem. Criá-lo não te deu nada aqui — e mesmo assim ele deixa toda escrita mais lenta.',
    },
    treeLabel: 'índice · árvore B',
    heapLabel: 'tabela',
  },
  copper: {
    lede: 'Isto não é uma ilustração. É o AGROM.brd, a placa que eu roteei em 2017 para a sonda de solo — 70 mm de diâmetro, duas camadas de cobre, 54 componentes — lido direto do arquivo do EAGLE e desenhado aqui. Escolha uma net e siga ela.',
    viewLabel: 'Vista',
    layersLabel: 'Camadas',
    view2d: 'Plana',
    view3d: 'Empilhada',
    viewSolid: 'Montada',
    flip: 'Virar',
    componentsWord: 'componentes',
    underneathWord: 'embaixo',
    hintSolid: 'A mesma placa com os componentes em cima, construída a partir do arquivo IDF que o EAGLE exportou para o CAD mecânico em 2017 — cada footprint, posição, rotação e lado vem de lá. Dezenove das 59 peças são montadas na face de baixo. Vire a placa e você acha elas.',
    explode: 'Separação',
    spin: 'arraste para girar',
    hintStack: 'É a mesma placa, vista de lado. Duas folhas de cobre com 1,6 mm de fibra de vidro entre elas, e 34 postes metalizados costurando as duas. Cada poste amarelo é uma via — o único jeito de um sinal ir de uma face para a outra.',
    both: 'Ambas',
    topOnly: 'Só a de cima',
    bottomOnly: 'Só a de baixo',
    netsLabel: 'Nets',
    allNets: 'Todas',
    segments: 'Segmentos',
    crossings: 'Trocas de camada',
    length: 'Comprimento de cobre',
    legendTop: 'cobre superior',
    legendBottom: 'cobre inferior',
    legendVia: 'via',
    hintIdle: 'Vermelho corre na face de cima, azul na de baixo. Cada anel amarelo é uma via: um furo metalizado onde a trilha atravessa para o outro lado.',
    hintCrossings: 'A net {net} troca de camada {n} vezes. Mude para uma camada só e veja ela se partir em pedaços — os buracos são onde ela está correndo na face que você acabou de esconder.',
    hintFlat: 'A net {net} nunca sai da sua camada. Nada ficou no caminho dela, então ela nunca precisou mergulhar.',
    hintOneLayer: 'Metade da placa sumiu. Tudo o que falta está correndo na outra face — e o único motivo de isso ser possível é que as duas faces estão costuradas por vias.',
  },
  steel: {
    lede: 'As montagens em que o projeto mecânico está organizado, uma pasta para cada, reconstruídas a partir dos desenhos pelos quais foram usinadas. Escolha uma, desmonte, e leia do que ela é feita.',
    productLabel: 'Produto',
    explode: 'Vista explodida',
    zoom: 'Zoom',
    reset: 'Redefinir vista',
    loading: 'carregando as peças impressas…',
    spin: 'arraste para girar',
    autoSpin: 'Girar',
    pieces: 'Peças',
    span: 'Maior dimensão',
    provenance: 'Peças torneadas e cortadas são construídas dos seus desenhos cotados. Peças impressas são os STLs de verdade. O arranjo foi ajustado pelos renders de 2017, porque as montagens do SolidWorks não podem ser lidas.',
    processTitle: 'A prova está na estrutura de pastas',
    processLede: 'O projeto mecânico não está organizado por peça. Está organizado por como cada peça é fabricada — que é a diferença entre modelar uma coisa e especificar ela.',
    processes: [
      { label: 'Torno e usinagem', count: 11, note: 'cada uma com desenho cotado' },
      { label: 'Corte a laser', count: 5, note: 'acrílico plano, desenhado e tolerado' },
      { label: 'Impressão 3D', count: 7, note: 'as peças carregadas aqui como STL' },
      { label: 'Compra', count: 14, note: 'sensores, células, conectores' },
      { label: 'Montagem de cabos', count: 1, note: 'um chicote de quatro vias' },
    ],
    drawings: '16 desenhos cotados · 82 itens em 7 listas de material',
    products: {
      'station': { name: 'Estação Meteorológica Full', kind: 'a estação completa', blurb: 'Todas as montagens abaixo, no lugar em que o render de 2017 as coloca.' },
      'cabeca-os': { name: 'Cabeça 1 · Only Soil', kind: 'cabeça só-solo', blurb: 'O suporte usinado, a barra e a tampa impressas, acrílico cortado a laser, e duas células fotovoltaicas.' },
      'cabeca-ws': { name: 'Cabeça 2 · Weather Station', kind: 'cabeça de estação', blurb: 'A mesma cabeça, levando um sensor UV e um TIL-78 onde estavam as células.' },
      'corpo': { name: 'Corpo', kind: 'o mastro', blurb: 'Um cone, quatro conexões, seis espaçadores e o cano de um metro. São os espaçadores que definem as profundidades dos sensores enterrados.' },
      'painel': { name: 'Painel Solar', kind: 'conjunto solar', blurb: 'Dois painéis em dois suportes usinados.' },
      'pcb': { name: 'PCB', kind: 'a placa, no modelo mecânico', blurb: 'O laminado e as duas faces povoadas — o mesmo export IDF de que o capítulo 02 monta a placa dele.' },
      'air': { name: 'Sensor 0 · AIR', kind: 'unidade de superfície', blurb: 'A haste, o assento usinado dela, e o berço de bateria impresso com sua tampa.' },
      'thd': { name: 'Sensor 1 · THD', kind: 'sensor de solo enterrado', blurb: 'Corpo usinado estriado sob tampa de acrílico cortada a laser, encapsulado em epóxi, com rabicho M12.' },
      'gas': { name: 'Sensor 5 · GAS STATION', kind: 'banco de sensores de gás', blurb: 'MQ-2, MQ-7 e MQ-8 com um barômetro, num suporte impresso sob tampa ventilada.' },
    },
  },
  glass: {
    lede: 'Um card, dois builds. À esquerda o card como ele sai do layout: uma linha só, cada texto numa linha, uma altura em pontos. À direita o mesmo card construído para sobreviver. Ligue as condições e veja qual continua legível — o tamanho de fonte que a pessoa realmente escolheu, uma tela dividida estreita, uma tradução mais longa, um idioma da direita para a esquerda, uma imagem que nunca chegou, um erro sem lugar para aparecer.',
    dynamicType: 'Dynamic Type',
    width: 'Largura disponível',
    conditions: 'Condições',
    longString: 'Tradução mais longa',
    rtl: 'Direita para esquerda',
    noImage: 'Imagem não chegou',
    reset: 'Resetar',
    errorText: 'Não conseguimos falar com a corretora. Suas posições estão seguras.',
    stateLabel: 'Estado da tela',
    states: {
      loading: 'Carregando',
      empty: 'Vazio',
      error: 'Erro',
      content: 'Conteúdo',
    },
    emptyTitle: 'Nenhuma posição aberta',
    emptyBody: 'Quando você abrir uma, ela aparece aqui, com o resultado dela.',
    emptyCta: 'Ver mercados',
    errorTitle: 'Não deu para carregar suas posições',
    errorCta: 'Tentar de novo',
    variants: {
      fixed: 'Feito pelo layout',
      adaptive: 'Feito para sobreviver',
    },
    failures: {
      none: 'nada quebrado',
      'title-truncated': 'o título é cortado com reticências',
      'value-collides': 'o número atropela o título',
      'subtitle-clipped': 'o subtítulo é cortado',
      'mirrored-wrong': 'a seta continua apontando para o lado errado e o número está do lado errado',
      'image-hole': 'um quadrado vazio de quarenta pontos onde a imagem nunca chegou',
      'error-hidden': 'o erro não tem onde aparecer e é cortado até sumir',
      'target-too-small': 'a linha está abaixo do mínimo de quarenta e quatro pontos',
      'no-skeleton': 'o mesmo card com os textos vazios, que parece bug e não carregamento',
      'no-empty-state': 'um card em branco com uma seta que não leva a lugar nenhum',
    },
    swift: '// The whole fix is three decisions.\nHStack(alignment: .firstTextBaseline, spacing: 12) {\n  if let image { Thumbnail(image) }        // no image, no box\n  VStack(alignment: .leading, spacing: 2) {\n    Text(position.symbol)\n      .font(.headline)\n      .lineLimit(nil)                      // let it wrap\n    if let error { Text(error).foregroundStyle(.red) }\n    else { Text(position.summary).font(.subheadline) }\n  }\n  Spacer(minLength: 12)\n  Text(position.pnl, format: .currency(code: code))\n    .monospacedDigit()\n}\n.padding(.horizontal, 16).padding(.vertical, 12)\n.frame(minHeight: 44)                      // grows, never clips\n.dynamicTypeSize(...DynamicTypeSize.accessibility5)\n.accessibilityElement(children: .combine)\n.accessibilityLabel(position.spokenLabel)',
    dart: '// Same three decisions, same order.\nRow(\n  crossAxisAlignment: CrossAxisAlignment.start,\n  children: [\n    if (image != null) Thumbnail(image!),\n    const SizedBox(width: 12),\n    Expanded(                              // min-width: 0, in Flutter\n      child: Column(\n        crossAxisAlignment: CrossAxisAlignment.start,\n        children: [\n          Text(p.symbol, style: t.titleMedium, softWrap: true),\n          error != null\n            ? Text(error!, style: t.bodySmall!.copyWith(color: cs.error))\n            : Text(p.summary, style: t.bodySmall),\n        ],\n      ),\n    ),\n    const SizedBox(width: 12),\n    Text(p.pnl, style: t.titleMedium),\n  ],\n)\n// Directionality mirrors the row; Semantics gives it one spoken label.',
  },
  flow: {
    lede: 'É isso que o Tradx faz, em miniatura. Você não escreve o laço — você liga a lógica, e o motor roda ela sobre os candles. Mexa nos parâmetros e veja o grafo e as operações mudarem juntos.',
    period: 'Período do RSI',
    buyLevel: 'Entrar acima de',
    sellLevel: 'Sair abaixo de',
    run: 'Rodar',
    inSample: 'Ajuste nesta metade',
    outSample: 'A metade que você nunca viu',
    trades: 'Operações',
    returnPct: 'Retorno',
    winRate: 'Acerto',
    nodes: {
      source: 'Dados de mercado', rsi: 'Indicador RSI', crossUp: 'Cruzamento p/ cima',
      crossDown: 'Cruzamento p/ baixo', entry: 'Entrada', exit: 'Saída',
    },
    hintIn: 'Ajuste até o número ficar bonito. Essa é a parte fácil, e é o que todo print de backtest na internet está te mostrando.',
    hintOut: 'Mesmo grafo, mesmos parâmetros, um trecho de mercado em que ele nunca foi ajustado.',
    reveal: 'Entre as 75.429 combinações de parâmetros, o conjunto que mais rendeu na metade em que você ajustou ficou em 22.949º lugar na metade que você não viu. Do primeiro lugar para o vigésimo segundo milésimo. É por isso que um backtest é uma hipótese e não um resultado, e por isso o número bonito é a parte fácil.',
  },
  field: {
    lede: 'Um objeto, construído duas vezes. De um lado da chave é a malha do capítulo 03, aquela pela qual a peça foi impressa. Do outro é um campo de gaussianas sobre essa mesma malha — espalhadas aqui em vez de ajustadas, para os dois ficarem lado a lado e a diferença ser o método e mais nada.',
    mesh: 'Malha', splats: 'Gaussianas',
    count: 'Gaussianas', size: 'Espalhamento', spin: 'arraste para girar',
    primitives: 'Primitivas', authored: 'Feitas à mão',
    authoredMesh: 'cada triângulo', authoredSplat: 'nenhuma delas',
    hintMesh: '997 triângulos, cada um colocado por alguém no SolidWorks em 2017.',
    hintSplats: 'Ninguém colocou estas. Numa reconstrução de verdade elas começam como ruído e são movidas, esticadas e recoloridas por gradiente descendente até o render parar de discordar das fotografias — e é por isso que a contagem chega às centenas de milhares sem incomodar ninguém.',
    loading: 'carregando a malha…',
  },
  ui: {
    hardwareCta: 'Jogar os capítulos de hardware',
    duty: 'Ciclo de trabalho',
    brightness: 'Brilho percebido',
    frequency: 'Frequência',
    play: 'Rodar',
    pause: 'Pausar',
    reset: 'Reiniciar',
    subscribe: 'Assinar',
    publish: 'Publicar',
    matched: 'entregue',
    dropped: 'não entregue',
    replicas: 'Réplicas',
    traffic: 'Tráfego de entrada',
    latency: 'Latência p99',
    dropped_req: 'Requisições perdidas',
    cost: 'Custo',
    train: 'Treinar',
    epoch: 'Época',
    accuracy: 'Acurácia',
    wip: 'Interatividade em construção',
    wipNote: 'O layout é o definitivo; este painel está sendo ligado.',
    learned: 'O que você acabou de aprender',
  },
};
