import type { Content } from './types';

export const pt: Content = {
  meta: {
    title: 'Maykon Meneghel — o currículo jogável',
    description:
      'Engenheiro full-stack sênior com mestrado e pós em IA. Firmware, PCBs, CAD, MQTT, Kubernetes, Swift e Flutter — explicados em mini-jogos que você joga na própria página.',
  },
  nav: { chapters: 'Capítulos', family: 'A família', contact: 'Contato', resume: 'Currículo' },
  hero: {
    kicker: 'Engenheiro Full-Stack Sênior · Mestre em Bioengenharia · Especialista em IA',
    name: 'Maykon Meneghel',
    headline: 'Eu construo a pilha inteira — da trilha de cobre à rede neural.',
    sub: 'A maioria dos currículos conta o que alguém sabe fazer. Este aqui deixa você experimentar. Cada capítulo abaixo é um mini-jogo que funciona: você vai rotear uma PCB, assinar um tópico MQTT, escalar um cluster sob carga e treinar um modelo — sem sair desta página.',
    cta: 'Começar o tour',
    scrollHint: 'role',
    boot: [
      'meneghel.me boot v2.0',
      'detectando hardware .... ESP32 · PIC18F4550 · ATmega · ATtiny',
      'montando linguagens .... swift · dart · python · typescript · c/c++ · java',
      'subindo serviços ....... docker · kubernetes · mqtt · rest',
      'carregando inteligência  pytorch · gan · pln',
      'pronto.',
    ],
  },
  chapters: [
    {
      id: '01', codename: 'SILÍCIO', slug: 'silicon',
      title: 'Tudo começa em um único pino',
      lede: 'Muito antes de existir um app, existe um microcontrolador decidindo — milhões de vezes por segundo — se um fio está em nível alto ou baixo. Quatorze firmwares me ensinaram que tudo o que vem acima depende de acertar isto aqui.',
      panel: 'pwm_playground.c',
      takeaway: 'Você acabou de reduzir o brilho de um LED sem nunca mudar a tensão dele. Isso é <b>PWM</b>: o pino só fica totalmente ligado ou totalmente desligado — ele apenas chaveia mais rápido do que o seu olho consegue acompanhar.',
      stack: ['C/C++', 'ESP32', 'PIC18F4550', 'ATmega', 'Timers e PWM'],
    },
    {
      id: '02', codename: 'COBRE', slug: 'copper',
      title: 'Depois, ele precisa de uma placa',
      lede: 'Um esquemático é uma promessa. A PCB é onde ela é cumprida. Toda placa que fabriquei começou exatamente neste quebra-cabeça: levar cada sinal ao seu lugar, numa superfície onde nada pode se cruzar.',
      panel: 'router.pcb',
      takeaway: 'Duas trilhas não podem se cruzar na mesma camada. É essa única restrição que faz placas reais terem 2, 4, às vezes 12 camadas empilhadas.',
      stack: ['Altium', 'EAGLE', 'SMD e THT', 'Gerber', 'Design para manufatura'],
    },
    {
      id: '03', codename: 'AÇO', slug: 'steel',
      title: 'E um corpo para sobreviver ao campo',
      lede: 'Um sensor enterrado em solo encharcado por dois anos não liga para a elegância do seu firmware. Ele liga para o encapsulamento. Por isso eu mesmo modelo cada peça, cada tolerância, cada vedação.',
      panel: 'soil_probe.sldasm',
      takeaway: 'Hardware é a única camada que você não corrige remotamente. É por isso que o projeto mecânico acontece <b>antes</b> da primeira linha de firmware, não depois.',
      stack: ['SolidWorks', 'Modelagem 3D', 'Tolerâncias', 'Vedação IP', 'Impressão 3D'],
    },
    {
      id: '04', codename: 'SINAL', slug: 'signal',
      title: 'Agora faça mil deles conversarem',
      lede: 'Um dispositivo é um projeto. Mil dispositivos é uma arquitetura. MQTT é como eles se falam sem nunca se conhecerem — e os curingas de tópico são o truque inteiro.',
      panel: 'broker · mqtt://meneghel.me:8883',
      takeaway: '<b>+</b> casa exatamente um nível. <b>#</b> casa tudo abaixo dele. Essa única regra é como um só broker distribui para milhares de dispositivos sem que nenhum deles guarde a lista dos outros.',
      stack: ['MQTT', 'Mosquitto', 'AWS IoT Core', 'QoS 0/1/2', 'Pub/Sub'],
    },
    {
      id: '05', codename: 'SERVIÇO', slug: 'service',
      title: 'Alguém precisa lembrar de tudo isso',
      lede: 'Mensagens são efêmeras; o negócio não é. Atrás de cada dispositivo existe uma API e um banco, e a diferença entre um produto rápido e um lento costuma ser uma decisão tomada aqui.',
      panel: 'psql · meneghel_db',
      takeaway: 'Sem índice, o banco lê <b>todas as linhas</b> para te responder. Com um, ele salta direto ao ponto. Mesma query, mesmos dados, mesmo servidor — mil vezes mais rápido.',
      stack: ['Node.js', 'Express', 'Restify', 'MongoDB', 'PostgreSQL', 'REST'],
    },
    {
      id: '06', codename: 'ENXAME', slug: 'swarm',
      title: 'Uma máquina nunca é suficiente',
      lede: 'Tráfego não chega educadamente. Ele chega todo de uma vez, às 3 da manhã, no dia do lançamento. Containers e Kubernetes são como você responde a isso sem acordar.',
      panel: 'kubectl · production',
      takeaway: 'Você não deixou o código mais rápido — você fez <b>mais cópias dele</b>. Escala horizontal troca dinheiro por latência, e um autoscaler faz essa troca por você, sozinho.',
      stack: ['Docker', 'Kubernetes', 'HPA', 'Load balancing', 'CI/CD'],
    },
    {
      id: '07', codename: 'MENTE', slug: 'mind',
      title: 'Ensine a máquina a decidir',
      lede: 'É aqui que a minha pós em IA e o mestrado em Bioengenharia deixam de ser linhas num diploma. Um modelo não é mágica: é uma fronteira, desenhada e redesenhada até os erros pararem.',
      panel: 'perceptron.py — época 0',
      takeaway: 'O modelo nunca viu a sua regra. Ele viu apenas os seus erros, e moveu a linha um pouquinho depois de cada um. Repita isso algumas centenas de vezes e você tem o que chamam de <b>aprendizado</b>.',
      stack: ['PyTorch', 'GANs', 'PLN', 'Classificação e regressão', 'Mineração de dados'],
    },
    {
      id: '08', codename: 'VIDRO', slug: 'glass',
      title: 'Finalmente, algo em que se possa tocar',
      lede: 'Doze apps iOS nativos, um deles destacado pela Apple. O usuário nunca vê o broker, o cluster ou o modelo — ele vê uma tela. Então a tela precisa valer tudo isso.',
      panel: 'ContentView.swift / main.dart',
      takeaway: 'Mesma tela, mesma API, dois ecossistemas. Saber os dois não é sobre escolher um vencedor — é sobre poder <b>escolher</b> quando o produto exigir.',
      stack: ['Swift', 'SwiftUI', 'Flutter', 'Dart', 'Kotlin', 'App Store'],
    },
    {
      id: '09', codename: 'SISTEMA', slug: 'system',
      title: 'Agora veja tudo rodando junto',
      lede: 'Nove capítulos, um pacote. Aperte play e acompanhe uma única leitura de solo, do sensor enterrado até o gráfico na mão de alguém.',
      panel: 'trace · ponta a ponta',
      takeaway: 'Esta é a resposta de verdade para "o que você faz?". Não uma camada — <b>as costuras entre elas</b>, que é onde produtos de fato se ganham ou se perdem.',
      stack: ['Design de sistemas', 'Observabilidade', 'Sistemas distribuídos'],
    },
  ],
  record: {
    eyebrow: '10 · TRAJETÓRIA',
    title: 'As provas',
    lede: 'Nove capítulos de demonstração. Este aqui é só evidência. Arraste pelos anos e veja o que estava rodando ao mesmo tempo — porque a manchete honesta desta linha do tempo não é nenhum emprego específico, é o quão raramente houve só um.',
    lanes: {
      education: 'Formação',
      research: 'Pesquisa',
      industry: 'Indústria',
      venture: 'Empreendimentos',
    },
    roles: {
      grad: 'Eng. de Controle e Automação',
      msc: 'Mestrado em Bioengenharia',
      academy: 'Pós-graduação lato sensu, Desenvolvimento iOS',
      aiSpec: 'Especialização em Inteligência Artificial Aplicada',
      pucLab: 'Estagiário, Laboratório de Automação e Sistemas',
      araucaria: 'Engenheiro de Software — pesquisa aplicada, IA e saúde embarcada',
      freelance: 'Desenvolvedor de Software, autônomo',
      residency: 'Trainee · Apple Residency',
      junior: 'Desenvolvedor Júnior · Projeto Apple',
      techLead: 'Tech Lead · Apple Internship',
      fullstack: 'Desenvolvedor Full Stack · Projeto Apple',
      senior: 'Desenvolvedor Sênior · Projeto Apple',
      ghel: 'Technology Advisor · Projeto Renault',
      holding: 'Conselheiro Administrativo — a holding da família',
      tradx: 'COO e Cofundador',
    },
    scrubber: {
      simultaneous: '{n} funções ao mesmo tempo',
      one: '1 função',
      none: 'nada registrado ainda',
      today: 'hoje',
      drag: 'arraste o ano',
    },
    ventures: {
      title: 'Seis empresas',
      lede: 'Fundadas ou cofundadas. Algumas cresceram, outras não — que é exatamente o motivo de fundar seis.',
      founder: 'Fundador',
      coFounder: 'Cofundador',
      sectors: { fintech: 'fintech', agritech: 'agritech', smartHome: 'casa inteligente', proptech: 'proptech', edtech: 'edtech' },
    },
    publications: {
      title: 'Publicado e premiado',
      lede: 'Trabalho revisado por pares, quase todo na costura entre engenharia e saúde.',
      items: {
        soilInstrument: 'Instrumento para Medição de Fatores e/ou Elementos Naturais do Solo',
        fesTool: 'A Tool to Select FES Parameters for chronic SCI',
        fallDetector: 'Indoors Wi-Fi Fall Detector Buckle for the Elderly',
        inSilicoFes: 'Aplicação, in silico, de estímulos elétricos em modelo neuromuscular compatível com lesão medular crônica',
        balanceModel: 'Modelagem matemática do sistema de manutenção do equilíbrio por técnicas de identificação de sistemas',
        stockGan: 'Previsão de Séries Financeiras com Redes Generativas Adversárias',
      },
    },
    press: {
      title: 'Na imprensa',
      items: {
        hubli: 'Hubli, criado na Apple Developer Academy, destacado pela Apple',
        neonWave: 'Neon Wave, jogo de iOS que saiu no MacMagazine',
      },
    },
  },
  signal: {
    levels: ['local', 'área', 'dispositivo', 'medida'],
    anatomyLede: 'Um tópico é um caminho. Todo dispositivo desta fazenda publica em um caminho montado com os mesmos quatro níveis — então uma assinatura é, no fundo, uma pergunta sobre quais níveis te interessam.',
    legendPlus: 'casa exatamente um nível, seja qual for o conteúdo',
    legendHash: 'casa tudo o que vier abaixo, e precisa ser o último nível',
    yourToken: 'você escreveu',
    noToken: '—',
    subLabel: 'Sua assinatura',
    placeholder: 'farm/greenhouse/#',
    broker: 'Broker — tudo o que está sendo publicado',
    inbox: 'Sua caixa — o que chegou até você',
    delivered: 'entregues',
    dropped: 'não entregues',
    missionsTitle: 'Três assinaturas para acertar',
    missionsLede: 'Vale qualquer filtro que selecione exatamente os tópicos certos. Cada missão tem mais de uma resposta correta.',
    missions: [
      { id: 'greenhouse', goal: 'Tudo o que a estufa publica — e nada além disso.' },
      { id: 'temps',      goal: 'Toda leitura de temperatura, venha de onde vier.' },
      { id: 'moisture',   goal: 'Toda leitura de umidade da fazenda, mas não a de casa.' },
    ],
    solved: 'resolvida',
    invalidHash: 'o # precisa ser o último nível, sozinho',
    invalidPlus: 'o + precisa ocupar um nível inteiro, sozinho',
    invalidEmpty: 'um nível do tópico não pode ficar vazio',
    emptyInbox: 'nada casou ainda',
    allSolved: 'As três. Você já entende filtros de tópico MQTT melhor que boa parte de quem usa isso todo dia.',
  },
  swarm: {
    lede: 'O tráfego deste serviço dispara a cada poucos segundos, como num dia de lançamento. Adicione réplicas e a latência cai; adicione demais e você paga por máquina ociosa. Depois entregue ao autoscaler e veja onde ele ainda perde.',
    traffic: 'Entrada',
    replicas: 'Réplicas',
    latency: 'Latência p99',
    dropped: 'Requisições perdidas',
    cost: 'Custo',
    saturation: 'Saturação',
    auto: 'Autoscaler',
    autoHint: 'Mirando 60% de saturação. Um pod novo leva cerca de 4s para ficar pronto — e é por isso que ainda caem requisições na subida.',
    manualHint: 'Você está escalando na mão. O pico chega estando você pronto ou não.',
    ready: 'prontos',
    starting: 'subindo',
    reset: 'Zerar contadores',
    spike: 'pico',
    healthy: 'saudável',
    strained: 'sob pressão',
    failing: 'perdendo tráfego',
    wasteful: 'superdimensionado',
  },
  mind: {
    lede: 'Cada ponto é um motor que estava rodando a certa temperatura e certa vibração, e depois se mostrou bom ou se mostrou quebrado. Ninguém contou a regra ao modelo. Aperte treinar e veja ele procurar a linha.',
    axisX: 'temperatura →',
    axisY: 'vibração →',
    healthy: 'saudável',
    failing: 'em falha',
    adding: 'clicando adiciona',
    train: 'Treinar',
    pause: 'Pausar',
    clear: 'Limpar',
    presetSeparable: 'Separável',
    presetXor: 'XOR',
    steps: 'Correções',
    accuracy: 'Acurácia',
    wrong: 'Ainda errados',
    weights: 'Pesos',
    hintPlace: 'Clique em qualquer lugar para adicionar uma leitura. Troque a classe para colocar do outro tipo.',
    hintConverged: 'Ele parou. Não porque mandaram parar — porque não sobrou nada que ele errasse.',
    hintStuck: 'Ele nunca vai assentar. Nenhuma reta consegue separar este arranjo, e um perceptron é exatamente uma reta. Empilhar vários é como se obtém uma curva — e é essa a razão de existirem redes profundas.',
  },
  service: {
    lede: 'Uma tabela de leituras de sensor, 240.000 linhas. Escolha uma consulta, decida quais colunas ganham índice, e rode. A faixa abaixo é a tabela; repare em quanto dela o banco precisa tocar.',
    table: 'readings · 240.000 linhas',
    indexes: 'CREATE INDEX ON',
    query: 'Consulta',
    run: 'Rodar',
    running: 'Rodando…',
    rows: 'Linhas lidas',
    time: 'Tempo da consulta',
    speedup: 'vs varredura completa',
    writes: 'Custo de escrita',
    queryLabels: {
      point: 'uma linha por id',
      selective: 'um sensor · 5%',
      broad: 'quase toda a tabela · 60%',
    },
    hints: {
      'no-index': 'Não existe índice nessa coluna, então o banco não tem escolha. Ele abre a tabela na primeira linha e lê todas as 240.000 para ter certeza de que não deixou nenhuma passar.',
      'index-used': 'O índice foi direto ao ponto — dezoito passos árvore abaixo, e então as linhas. Mesma consulta, mesmos dados, mesma máquina.',
      'not-selective': 'O índice existe, e o planner se recusou a usá-lo. Esta consulta quer 60% da tabela, e ficar pulando por um índice para isso custa mais do que ler tudo em ordem. Criá-lo não te deu nada aqui — e mesmo assim ele deixa toda escrita mais lenta.',
    },
    treeLabel: 'índice · árvore B',
    heapLabel: 'tabela',
  },
  copper: {
    lede: 'Isto não é uma ilustração. É o AGROM.brd, a placa que eu roteei em 2017 para a sonda de solo — 70 mm de diâmetro, duas camadas de cobre, 54 componentes — lido direto do arquivo do EAGLE e desenhado aqui. Escolha uma net e siga ela.',
    layersLabel: 'Camadas',
    view2d: 'Plana',
    view3d: 'Empilhada',
    viewSolid: 'Montada',
    flip: 'Virar',
    componentsWord: 'componentes',
    underneathWord: 'embaixo',
    hintSolid: 'A mesma placa com os componentes em cima, construída a partir do arquivo IDF que o EAGLE exportou para o CAD mecânico em 2017 — cada footprint, posição, rotação e lado vem de lá. Dezenove das 59 peças são montadas na face de baixo. Vire a placa e você acha elas.',
    explode: 'Separação',
    spin: 'arraste para girar',
    hintStack: 'É a mesma placa, vista de lado. Duas folhas de cobre com 1,6 mm de fibra de vidro entre elas, e 34 postes metalizados costurando as duas. Cada poste amarelo é uma via — o único jeito de um sinal ir de uma face para a outra.',
    both: 'Ambas',
    topOnly: 'Só a de cima',
    bottomOnly: 'Só a de baixo',
    netsLabel: 'Nets',
    allNets: 'Todas',
    segments: 'Segmentos',
    crossings: 'Trocas de camada',
    length: 'Comprimento de cobre',
    legendTop: 'cobre superior',
    legendBottom: 'cobre inferior',
    legendVia: 'via',
    hintIdle: 'Vermelho corre na face de cima, azul na de baixo. Cada anel amarelo é uma via: um furo metalizado onde a trilha atravessa para o outro lado.',
    hintCrossings: 'A net {net} troca de camada {n} vezes. Mude para uma camada só e veja ela se partir em pedaços — os buracos são onde ela está correndo na face que você acabou de esconder.',
    hintFlat: 'A net {net} nunca sai da sua camada. Nada ficou no caminho dela, então ela nunca precisou mergulhar.',
    hintOneLayer: 'Metade da placa sumiu. Tudo o que falta está correndo na outra face — e o único motivo de isso ser possível é que as duas faces estão costuradas por vias.',
  },
  steel: {
    lede: 'Sete peças que eu modelei no SolidWorks e imprimi, carregadas aqui dos mesmos STLs que foram para a impressora. Vire uma.',
    partsLabel: 'Peça',
    loading: 'carregando malhas…',
    spin: 'arraste para girar',
    autoSpin: 'Girar',
    triangles: 'Triângulos',
    sourceTris: 'No STL',
    span: 'Maior dimensão',
    processTitle: 'A prova está na estrutura de pastas',
    processLede: 'O projeto mecânico não está organizado por peça. Está organizado por como cada peça é fabricada — que é a diferença entre modelar uma coisa e especificar ela.',
    processes: [
      { label: 'Torno e usinagem', count: 11, note: 'cada uma com desenho cotado' },
      { label: 'Corte a laser', count: 5, note: 'acrílico plano, desenhado e tolerado' },
      { label: 'Impressão 3D', count: 7, note: 'as peças que você gira aqui' },
      { label: 'Compra', count: 14, note: 'sensores, células, conectores' },
      { label: 'Montagem de cabos', count: 1, note: 'um chicote de quatro vias' },
    ],
    parts: {
      'barra-central': { kind: 'coluna central', blurb: 'A espinha em volta da qual a cabeça inteira é montada.' },
      'suporte-bateria': { kind: 'berço da bateria', blurb: 'Segura a célula de chumbo dentro do mastro.' },
      'tampa-suporte-bateria': { kind: 'tampa do berço', blurb: 'Fecha o berço contra o tempo.' },
      'suporte-gas': { kind: 'suporte dos sensores de gás', blurb: 'Carrega os sensores MQ-2, MQ-7 e MQ-8.' },
      'tampa-gas': { kind: 'tampa dos sensores de gás', blurb: 'Tampa ventilada, para os sensores ainda respirarem.' },
      'tampa-os': { kind: 'tampa da cabeça de solo', blurb: 'Tampa superior da cabeça só-solo.' },
      'tampa-ws': { kind: 'tampa da estação', blurb: 'Tampa superior da cabeça de estação meteorológica.' },
    },
    drawings: '16 desenhos cotados',
    hint: 'Estas malhas estão decimadas — cerca de mil triângulos cada, vindas de até quinze mil — porque uma página web não deve carregar arquivo de impressão. As silhuetas são as de verdade.',
  },
  ui: {
    duty: 'Ciclo de trabalho',
    brightness: 'Brilho percebido',
    frequency: 'Frequência',
    play: 'Rodar',
    pause: 'Pausar',
    reset: 'Reiniciar',
    subscribe: 'Assinar',
    publish: 'Publicar',
    matched: 'entregue',
    dropped: 'não entregue',
    replicas: 'Réplicas',
    traffic: 'Tráfego de entrada',
    latency: 'Latência p99',
    dropped_req: 'Requisições perdidas',
    cost: 'Custo',
    train: 'Treinar',
    epoch: 'Época',
    accuracy: 'Acurácia',
    wip: 'Interatividade em construção',
    wipNote: 'O layout é o definitivo; este painel está sendo ligado.',
    learned: 'O que você acabou de aprender',
  },
};
