import type { Content } from './types';

export const pt: Content = {
  meta: {
    title: 'Maykon Meneghel — o currículo jogável',
    description:
      'Engenheiro full-stack sênior com mestrado e pós em IA. Firmware, PCBs, CAD, MQTT, Kubernetes, Swift e Flutter — explicados em mini-jogos que você joga na própria página.',
  },
  nav: { chapters: 'Capítulos', family: 'A família', contact: 'Contato', resume: 'Currículo' },
  hero: {
    kicker: 'Engenheiro Full-Stack Sênior · Mestre em Tecnologias em Saúde · Especialista em IA',
    name: 'Maykon Meneghel',
    headline: 'Eu construo a pilha inteira — da trilha de cobre à rede neural.',
    sub: 'A maioria dos currículos conta o que alguém sabe fazer. Este aqui deixa você experimentar. Cada capítulo abaixo é um mini-jogo que funciona: você vai rotear uma PCB, assinar um tópico MQTT, escalar um cluster sob carga e treinar um modelo — sem sair desta página.',
    cta: 'Começar o tour',
    scrollHint: 'role',
    boot: [
      'meneghel.me boot v2.0',
      'detectando hardware .... ESP32 · PIC18F4550 · ATmega · ATtiny',
      'montando linguagens .... swift · dart · python · typescript · c/c++ · java',
      'subindo serviços ....... docker · kubernetes · mqtt · rest',
      'carregando inteligência  pytorch · gan · pln',
      'pronto.',
    ],
  },
  chapters: [
    {
      id: '01', codename: 'SILÍCIO', slug: 'silicon',
      title: 'Tudo começa em um único pino',
      lede: 'Muito antes de existir um app, existe um microcontrolador decidindo — milhões de vezes por segundo — se um fio está em nível alto ou baixo. Quatorze firmwares me ensinaram que tudo o que vem acima depende de acertar isto aqui.',
      panel: 'pwm_playground.c',
      takeaway: 'Você acabou de reduzir o brilho de um LED sem nunca mudar a tensão dele. Isso é <b>PWM</b>: o pino só fica totalmente ligado ou totalmente desligado — ele apenas chaveia mais rápido do que o seu olho consegue acompanhar.',
      stack: ['C/C++', 'ESP32', 'PIC18F4550', 'ATmega', 'Timers e PWM'],
    },
    {
      id: '02', codename: 'COBRE', slug: 'copper',
      title: 'Depois, ele precisa de uma placa',
      lede: 'Um esquemático é uma promessa. A PCB é onde ela é cumprida. Toda placa que fabriquei começou exatamente neste quebra-cabeça: levar cada sinal ao seu lugar, numa superfície onde nada pode se cruzar.',
      panel: 'router.pcb',
      takeaway: 'Duas trilhas não podem se cruzar na mesma camada. É essa única restrição que faz placas reais terem 2, 4, às vezes 12 camadas empilhadas.',
      stack: ['Altium', 'EAGLE', 'SMD e THT', 'Gerber', 'Design para manufatura'],
    },
    {
      id: '03', codename: 'AÇO', slug: 'steel',
      title: 'E um corpo para sobreviver ao campo',
      lede: 'Um sensor enterrado em solo encharcado por dois anos não liga para a elegância do seu firmware. Ele liga para o encapsulamento. Por isso eu mesmo modelo cada peça, cada tolerância, cada vedação.',
      panel: 'soil_probe.sldasm',
      takeaway: 'Hardware é a única camada que você não corrige remotamente. É por isso que o projeto mecânico acontece <b>antes</b> da primeira linha de firmware, não depois.',
      stack: ['SolidWorks', 'Modelagem 3D', 'Tolerâncias', 'Vedação IP', 'Impressão 3D'],
    },
    {
      id: '04', codename: 'SINAL', slug: 'signal',
      title: 'Agora faça mil deles conversarem',
      lede: 'Um dispositivo é um projeto. Mil dispositivos é uma arquitetura. MQTT é como eles se falam sem nunca se conhecerem — e os curingas de tópico são o truque inteiro.',
      panel: 'broker · mqtt://meneghel.me:8883',
      takeaway: '<b>+</b> casa exatamente um nível. <b>#</b> casa tudo abaixo dele. Essa única regra é como um só broker distribui para milhares de dispositivos sem que nenhum deles guarde a lista dos outros.',
      stack: ['MQTT', 'Mosquitto', 'AWS IoT Core', 'QoS 0/1/2', 'Pub/Sub'],
    },
    {
      id: '05', codename: 'SERVIÇO', slug: 'service',
      title: 'Alguém precisa lembrar de tudo isso',
      lede: 'Mensagens são efêmeras; o negócio não é. Atrás de cada dispositivo existe uma API e um banco, e a diferença entre um produto rápido e um lento costuma ser uma decisão tomada aqui.',
      panel: 'psql · meneghel_db',
      takeaway: 'Sem índice, o banco lê <b>todas as linhas</b> para te responder. Com um, ele salta direto ao ponto. Mesma query, mesmos dados, mesmo servidor — mil vezes mais rápido.',
      stack: ['Node.js', 'Express', 'Restify', 'MongoDB', 'PostgreSQL', 'REST'],
    },
    {
      id: '06', codename: 'ENXAME', slug: 'swarm',
      title: 'Uma máquina nunca é suficiente',
      lede: 'Tráfego não chega educadamente. Ele chega todo de uma vez, às 3 da manhã, no dia do lançamento. Containers e Kubernetes são como você responde a isso sem acordar.',
      panel: 'kubectl · production',
      takeaway: 'Você não deixou o código mais rápido — você fez <b>mais cópias dele</b>. Escala horizontal troca dinheiro por latência, e um autoscaler faz essa troca por você, sozinho.',
      stack: ['Docker', 'Kubernetes', 'HPA', 'Load balancing', 'CI/CD'],
    },
    {
      id: '07', codename: 'MENTE', slug: 'mind',
      title: 'Ensine a máquina a decidir',
      lede: 'É aqui que a minha pós em IA e o mestrado em Tecnologias em Saúde deixam de ser linhas num diploma. Um modelo não é mágica: é uma fronteira, desenhada e redesenhada até os erros pararem.',
      panel: 'perceptron.py — época 0',
      takeaway: 'O modelo nunca viu a sua regra. Ele viu apenas os seus erros, e moveu a linha um pouquinho depois de cada um. Repita isso algumas centenas de vezes e você tem o que chamam de <b>aprendizado</b>.',
      stack: ['PyTorch', 'GANs', 'PLN', 'Classificação e regressão', 'Mineração de dados'],
    },
    {
      id: '08', codename: 'VIDRO', slug: 'glass',
      title: 'Finalmente, algo em que se possa tocar',
      lede: 'Doze apps iOS nativos, um deles destacado pela Apple. O usuário nunca vê o broker, o cluster ou o modelo — ele vê uma tela. Então a tela precisa valer tudo isso.',
      panel: 'ContentView.swift / main.dart',
      takeaway: 'Mesma tela, mesma API, dois ecossistemas. Saber os dois não é sobre escolher um vencedor — é sobre poder <b>escolher</b> quando o produto exigir.',
      stack: ['Swift', 'SwiftUI', 'Flutter', 'Dart', 'Kotlin', 'App Store'],
    },
    {
      id: '09', codename: 'SISTEMA', slug: 'system',
      title: 'Agora veja tudo rodando junto',
      lede: 'Nove capítulos, um pacote. Aperte play e acompanhe uma única leitura de solo, do sensor enterrado até o gráfico na mão de alguém.',
      panel: 'trace · ponta a ponta',
      takeaway: 'Esta é a resposta de verdade para "o que você faz?". Não uma camada — <b>as costuras entre elas</b>, que é onde produtos de fato se ganham ou se perdem.',
      stack: ['Design de sistemas', 'Observabilidade', 'Sistemas distribuídos'],
    },
  ],
  record: {
    eyebrow: '10 · TRAJETÓRIA',
    title: 'As provas',
    lede: 'Nove capítulos de demonstração. Este aqui é só evidência. Arraste pelos anos e veja o que estava rodando ao mesmo tempo — porque a manchete honesta desta linha do tempo não é nenhum emprego específico, é o quão raramente houve só um.',
    lanes: {
      education: 'Formação',
      research: 'Pesquisa',
      industry: 'Indústria',
      venture: 'Empreendimentos',
    },
    roles: {
      grad: 'Eng. de Controle e Automação',
      msc: 'Mestrado em Bioengenharia',
      academy: 'Pós-graduação lato sensu, Desenvolvimento iOS',
      aiSpec: 'Especialização em Inteligência Artificial Aplicada',
      pucLab: 'Estagiário, Laboratório de Automação e Sistemas',
      araucaria: 'Engenheiro de Software — pesquisa aplicada, IA e saúde embarcada',
      freelance: 'Desenvolvedor de Software, autônomo',
      residency: 'Trainee · Apple Residency',
      junior: 'Desenvolvedor Júnior · Projeto Apple',
      techLead: 'Tech Lead · Apple Internship',
      fullstack: 'Desenvolvedor Full Stack · Projeto Apple',
      ghel: 'Technology Advisor',
      holding: 'Conselheiro Administrativo — a holding da família',
      tradx: 'COO e Cofundador',
    },
    scrubber: {
      simultaneous: '{n} funções ao mesmo tempo',
      one: '1 função',
      none: 'nada registrado ainda',
      today: 'hoje',
      drag: 'arraste o ano',
    },
    ventures: {
      title: 'Seis empresas',
      lede: 'Fundadas ou cofundadas. Algumas cresceram, outras não — que é exatamente o motivo de fundar seis.',
      founder: 'Fundador',
      coFounder: 'Cofundador',
      sectors: { fintech: 'fintech', agritech: 'agritech', smartHome: 'casa inteligente', proptech: 'proptech', edtech: 'edtech' },
    },
    publications: {
      title: 'Publicado e premiado',
      lede: 'Trabalho revisado por pares, quase todo na costura entre engenharia e saúde.',
      items: {
        soilInstrument: 'Instrumento para Medição de Fatores e/ou Elementos Naturais do Solo',
        fesTool: 'A Tool to Select FES Parameters for chronic SCI',
        fallDetector: 'Indoors Wi-Fi Fall Detector Buckle for the Elderly',
        inSilicoFes: 'Aplicação, in silico, de estímulos elétricos em modelo neuromuscular compatível com lesão medular crônica',
        balanceModel: 'Modelagem matemática do sistema de manutenção do equilíbrio por técnicas de identificação de sistemas',
        stockGan: 'Previsão de Séries Financeiras com Redes Generativas Adversárias',
      },
    },
    press: {
      title: 'Na imprensa',
      items: {
        hubli: 'Hubli, criado na Apple Developer Academy, destacado pela Apple',
        neonWave: 'Neon Wave, jogo de iOS que saiu no MacMagazine',
      },
    },
  },
  ui: {
    duty: 'Ciclo de trabalho',
    brightness: 'Brilho percebido',
    frequency: 'Frequência',
    play: 'Rodar',
    pause: 'Pausar',
    reset: 'Reiniciar',
    subscribe: 'Assinar',
    publish: 'Publicar',
    matched: 'entregue',
    dropped: 'não entregue',
    replicas: 'Réplicas',
    traffic: 'Tráfego de entrada',
    latency: 'Latência p99',
    dropped_req: 'Requisições perdidas',
    cost: 'Custo',
    train: 'Treinar',
    epoch: 'Época',
    accuracy: 'Acurácia',
    wip: 'Interatividade em construção',
    wipNote: 'O layout é o definitivo; este painel está sendo ligado.',
    learned: 'O que você acabou de aprender',
  },
};
