/**
 * The board JSON is generated by tools/extract-board.py from a 2017 EAGLE file
 * that lives outside this repository. These assertions are what stops a bad
 * re-extraction from silently shipping a board that is subtly wrong.
 */
import board from '../../data/agrom-board.json' with { type: 'json' };

let fail = 0;
const check = (ok: boolean, label: string, detail = '') => {
  if (!ok) { console.log(`FAIL ${label}${detail ? '\n  ' + detail : ''}`); fail++; }
};
const eq = (got: unknown, want: unknown, label: string) =>
  check(JSON.stringify(got) === JSON.stringify(want), label, `got ${JSON.stringify(got)}, want ${JSON.stringify(want)}`);

const { outline, holes, nets, parts } = board;

// --- the physical board, as EAGLE describes it ---
eq(outline.r, 35, 'the board is 70 mm across');
eq(holes.length, 2, 'two mounting holes');
check(holes.every((h) => h.d === 3.2), 'both are M3 clearance');
eq(parts.length, 54, '54 components placed');
eq(nets.length, 42, '42 nets carry copper');

// --- every segment sits on the board ---
const off = nets.flatMap((n) => [...n.top, ...n.bot]).filter(([x1, y1, x2, y2]) =>
  [[x1, y1], [x2, y2]].some(([x, y]) => Math.hypot(x - outline.cx, y - outline.cy) > outline.r + 0.5));
eq(off.length, 0, 'no trace escapes the board outline');

const viasOff = nets.flatMap((n) => n.vias).filter(([x, y]) =>
  Math.hypot(x - outline.cx, y - outline.cy) > outline.r);
eq(viasOff.length, 0, 'no via sits outside the board either');

// --- totals the panel prints ---
const segments = nets.reduce((s, n) => s + n.top.length + n.bot.length, 0);
const vias = nets.reduce((s, n) => s + n.vias.length, 0);
eq(segments, 754, 'segment count');
eq(vias, 34, 'via count');
check(Math.abs(nets.reduce((s, n) => s + n.mm, 0) - 1321) < 1, 'about 1321 mm of copper');

// --- the nets the chapter leans on ---
const byName = Object.fromEntries(nets.map((n) => [n.name, n]));
check(byName['GND'] !== undefined, 'GND exists');
check(byName['GND'].mm > byName['+5V'].mm, 'ground carries more copper than the 5V rail');
eq(byName['+5V'].vias.length, 7, '+5V changes layer seven times — the chapter says so');
eq(byName['IN'].vias.length, 0, 'IN never changes layer — the other case the chapter shows');
check(nets.every((n) => n.mm > 0), 'every net that made the cut has length');

// --- widths are real EAGLE track widths, not zeros ---
const widths = new Set(nets.flatMap((n) => [...n.top, ...n.bot]).map(([, , , , w]) => w));
check([...widths].every((w) => w > 0 && w < 2), 'track widths are plausible in mm', `${[...widths].sort().join(', ')}`);

console.log(fail === 0 ? '\nAll assertions passed.' : `\n${fail} failing assertion(s).`);
process.exit(fail === 0 ? 0 : 1);
